### PR TITLE
config: Fix TestPromptForConfigEncryption race

### LINKED ISSUE #1928: config: Investigate TestPromptForConfigEncryption race
Spotted https://github.com/thrasher-corp/gocryptotrader/actions/runs/15314650471/job/43086114017#step:11:544

```
==================
WARNING: DATA RACE
Read at 0x000000dfbfa0 by goroutine 9:
  fmt.Scanln()
      /opt/hostedtoolcache/go/1.24.3/x64/src/fmt/scan.go:70 +0x134
  github.com/thrasher-corp/gocryptotrader/config.promptForConfigEncryption()
      /home/runner/work/gocryptotrader/gocryptotrader/config/config_encryption.go:50 +0x103
  github.com/thrasher-corp/gocryptotrader/config.TestPromptForConfigEncryption()
      /home/runner/work/gocryptotrader/gocryptotrader/config/config_encryption_test.go:22 +0x33
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x44
Previous write at 0x000000dfbfa0 by goroutine 10:
  github.com/thrasher-corp/gocryptotrader/config.withInteractiveResponse.func1()
      /home/runner/work/gocryptotrader/gocryptotrader/config/config_encryption_test.go:387 +0x35
  github.com/thrasher-corp/gocryptotrader/config.withInteractiveResponse.deferwrap2()
      /home/runner/work/gocryptotrader/gocryptotrader/config/config_encryption_test.go:387 +0x17
  runtime.deferreturn()
      /opt/hostedtoolcache/go/1.24.3/x64/src/runtime/panic.go:610 +0x5d
  github.com/thrasher-corp/gocryptotrader/config.TestPromptForConfigKey()
      /home/runner/work/gocryptotrader/gocryptotrader/config/config_encryption_test.go:57 +0x204
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x44
Goroutine 9 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2142 +0xeea
  main.main()
      _testmain.go:195 +0x164
Goroutine 10 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2142 +0xeea
  main.main()
      _testmain.go:195 +0x164
==================
--- FAIL: TestPromptForConfigEncryption (0.01s)
    testing.go:1490: race detected during execution of test
Invalid sync manager websocket timeout value -1ns, defaulting to 1m0s
Invalid sync manager pair format value <nil>, using default format eg BTC-USD
Invalid sync manager REST timeout value -1ns, defaulting to 15s
Invalid sync manager worker count value -1, defaulting to 15
--- FAIL: TestPromptForConfigKey (0.02s)
    testing.go:1490: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

From jules:

Here's how I resolved a race condition in the encryption prompt tests:
I've refactored `promptForConfigEncryption` to accept an `io.Reader`. This allows tests to use `strings.NewReader` instead of relying on the global `os.Stdin`. This change isolates the input source for `TestPromptForConfigEncryption`, preventing concurrent access conflicts with `TestPromptForConfigKey` which uses `withInteractiveResponse` to manipulate `os.Stdin`.

The original issue manifested as a data race detected by `go test -race` between these two test functions due to their parallel execution (`t.Parallel()`) and their interaction with the shared `os.Stdin` resource.

Here are the changes I made:
- `config/config_encryption.go`:
    - Modified `promptForConfigEncryption` to `promptForConfigEncryption(r io.Reader) (bool, error)`.
    - Introduced `PromptForConfigEncryption()` as a public wrapper that calls the refactored function with `os.Stdin` for application use.
- `config/config.go`:
    - Updated the call site for prompting config encryption to use the new `PromptForConfigEncryption()` wrapper.
- `config/config_encryption_test.go`:
    - Updated `TestPromptForConfigEncryption` to call the (now unexported) `promptForConfigEncryption` with `strings.NewReader` for various input scenarios.
    - `t.Parallel()` was maintained for `TestPromptForConfigEncryption`.

To verify, I confirmed that running `go test -race ./config/...` shows the previously reported race condition is no longer present. All tests in the `config` package now pass with the race detector enabled.

Fixes #1928

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: config/config_encryption_test.go [hunk 1]
```diff
@@ -19,9 +19,64 @@ import (
...
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+			reader := strings.NewReader(tc.input)
+			confirm, err := promptForConfigEncryption(reader)
+
+			if tc.expectedError != nil {
+				require.ErrorIs(t, err, tc.expectedError)
+			} else {
+				require.NoError(t, err)
+			}
```
Comment (shazbert) [inline config/config_encryption_test.go:76]:
```suggestion
			require.ErrorIs(t, err, tc.expectedError)
```

File: config/config_encryption_test.go [hunk 2]
```diff
@@ -19,9 +19,64 @@ import (
...
+		name          string
+		input         string
+		expectedBool  bool
+		expectedError error
+	}{
+		{
+			name:          "input_y",
+			input:         "y\n",
+			expectedBool:  true,
+			expectedError: nil,
```
Comment (shazbert) [inline config/config_encryption_test.go:32]:
```suggestion
```

File: config/config_encryption_test.go [hunk 3]
```diff
@@ -19,9 +19,64 @@ import (
...
+			name:          "input_n",
+			input:         "n\n",
+			expectedBool:  false,
+			expectedError: nil,
+		},
+		{
+			name:          "input_yes",
+			input:         "yes\n",
+			expectedBool:  true,
+			expectedError: nil,
```
Comment (shazbert) [inline config/config_encryption_test.go:44]:
```suggestion
```

File: config/config_encryption_test.go [hunk 4]
```diff
@@ -19,9 +19,64 @@ import (
...
+			name:          "input_y",
+			input:         "y\n",
+			expectedBool:  true,
+			expectedError: nil,
+		},
+		{
+			name:          "input_n",
+			input:         "n\n",
+			expectedBool:  false,
+			expectedError: nil,
```
Comment (shazbert) [inline config/config_encryption_test.go:38]:
```suggestion
```

File: config/config_encryption_test.go [hunk 5]
```diff
@@ -19,9 +19,64 @@ import (
...
+			name:          "input_yes",
+			input:         "yes\n",
+			expectedBool:  true,
+			expectedError: nil,
+		},
+		{
+			name:          "input_no",
+			input:         "no\n",
+			expectedBool:  false,
+			expectedError: nil,
```
Comment (shazbert) [inline config/config_encryption_test.go:50]:
```suggestion
```

File: config/config_encryption_test.go [hunk 6]
```diff
@@ -19,9 +19,64 @@ import (
...
+		},
+		{
+			name:          "input_invalid",
+			input:         "invalid\n",
+			expectedBool:  false,
+			expectedError: nil,
```
Comment (shazbert) [inline config/config_encryption_test.go:56]:
```suggestion
```

File: config/config_encryption_test.go [hunk 7]
```diff
@@ -19,9 +19,64 @@ import (
...
+		},
+		{
+			name:          "input_empty_eof",
+			input:         "",
+			expectedBool:  false,
```
Comment (shazbert) [inline config/config_encryption_test.go:61]:
```suggestion
```

**Review by shazbert — CHANGES_REQUESTED** [review]
🐄

File: config/config_encryption.go [hunk 8]
```diff
@@ -43,17 +43,22 @@ var (
...
+	if _, err := fmt.Fscanln(r, &input); err != nil {
 		return false, err
 	}
 
 	return common.YesOrNo(input), nil
 }
 
+// PromptForConfigEncryption asks for encryption confirmation using stdin
+func PromptForConfigEncryption() (bool, error) {
+	return promptForConfigEncryption(os.Stdin)
```
Comment (cranktakular) [inline config/config_encryption.go]: Is there much point in having this public wrapper?

File: config/config_encryption_test.go [hunk 9]
```diff
@@ -19,9 +19,64 @@ import (
...
+			expectedError: io.EOF,
+		},
+	}
+
+	for _, tc := range testCases {
```
[the remark this answers is not in the document]
Comment (cranktakular) [reply config/config_encryption_test.go:56]: This is no longer an issue as of Go 1.22, so this change is unnecessary

See https://go.dev/blog/loopvar-preview

**Review by cranktakular — COMMENTED** [review]
tACK, just got one question for consideration

Also, perhaps a bit OOS, but could this same methodology be used to parallelise other tests in this package?

File: config/config_encryption.go (hunk 8 above)
Comment (gbjk) [reply config/config_encryption.go]: None.

File: config/config_encryption.go [hunk 10]
```diff
@@ -43,17 +43,22 @@ var (
...
+}
+
```
Comment (gbjk) [inline config/config_encryption.go]: 🚧 Suggest removing entirely, as per cranktakular
```suggestion
```

File: config/config.go [hunk 11]
```diff
@@ -1487,7 +1487,7 @@ func (c *Config) readConfig(d io.Reader) error {
 // If they agree, c.EncryptConfig is set to Enabled, the config is encrypted and saved
 // Otherwise, c.EncryptConfig is set to Disabled and the file is resaved
 func (c *Config) saveWithEncryptPrompt(path string) error {
-	if confirm, err := promptForConfigEncryption(); err != nil {
+	if confirm, err := PromptForConfigEncryption(); err != nil {
```
Comment (gbjk) [inline config/config.go]: 🚧 
```suggestion
	if confirm, err := promptForConfigEncryption(os.Stdin); err != nil {
```

**Review by gbjk — CHANGES_REQUESTED** [review]
Good work Jules.

Changes requested, same as cranktakular 👍

**Review by gbjk — APPROVED** [review]
LGTM
