### PR TITLE
exchanges: Fix race, improve error handling in ValidateKline and assertify related tests

### LINKED ISSUE #1918: exchanges: Fix ValidateKline race
Spotted here: https://github.com/thrasher-corp/gocryptotrader/actions/runs/15133081308/job/42538462355#step:11:289

```
==================
WARNING: DATA RACE
Write at 0x00c0002db8f8 by goroutine 219:
  github.com/thrasher-corp/gocryptotrader/currency.(*PairsManager).Load()
      /home/runner/work/gocryptotrader/gocryptotrader/currency/manager.go:431 +0x3c6
  github.com/thrasher-corp/gocryptotrader/internal/testing/exchange.UpdatePairsOnce()
      /home/runner/work/gocryptotrader/gocryptotrader/internal/testing/exchange/exchange.go:215 +0x1f2
  github.com/thrasher-corp/gocryptotrader/exchanges/okx.TestUpdateTickers()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/okx/okx_test.go:3345 +0x69
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x44

Previous read at 0x00c0002db8f8 by goroutine 238:
  github.com/thrasher-corp/gocryptotrader/exchanges.(*Base).ValidateKline()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/exchange.go:1149 +0x1a4
  github.com/thrasher-corp/gocryptotrader/exchanges.(*Base).GetKlineRequest()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/exchange.go:1498 +0x30c
  github.com/thrasher-corp/gocryptotrader/exchanges/okx.(*Okx).GetHistoricCandles()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/okx/okx_wrapper.go:1996 +0x1cd
  github.com/thrasher-corp/gocryptotrader/exchanges/okx.TestGetHistoricCandles()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/okx/okx_test.go:3875 +0x81d
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x44

Goroutine 219 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2142 +0xeea
  github.com/thrasher-corp/gocryptotrader/exchanges/okx.TestMain()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/okx/okx_test.go:75 +0x104
  main.main()
      _testmain.go:825 +0x171

Goroutine 238 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.3/x64/src/testing/testing.go:2142 +0xeea
  github.com/thrasher-corp/gocryptotrader/exchanges/okx.TestMain()
      /home/runner/work/gocryptotrader/gocryptotrader/exchanges/okx/okx_test.go:75 +0x104
  main.main()
      _testmain.go:825 +0x171
==================
--- FAIL: TestGetHistoricTrades (2.51s)
    testing.go:1490: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

We're directly accessing the currency pairs map in `ValidateKline` which causes a 🏎️ so this uses the CurrencyPairs helpers which utilise a mutex, also assertifies the related tests

Fixes #1918 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: exchanges/exchange.go [hunk 1]
```diff
@@ -1143,18 +1143,23 @@ func (b *Base) FormatExchangeKlineInterval(in kline.Interval) string {
 // ValidateKline confirms that the requested pair, asset & interval are
 // supported and/or enabled by the requested exchange.
 func (b *Base) ValidateKline(pair currency.Pair, a asset.Item, interval kline.Interval) error {
```
Comment (shazbert) [inline exchanges/exchange.go:1145]: Unexport as its not part of IBOTExchange

suggestion: Change name to something like `VerifyKlineParameters` as we are not validating a kline directly

File: exchanges/exchange.go [hunk 2]
```diff
@@ -1143,18 +1143,23 @@ func (b *Base) FormatExchangeKlineInterval(in kline.Interval) string {
...
-	var err error
-	if b.CurrencyPairs.IsAssetEnabled(a) != nil {
-		err = common.AppendError(err, fmt.Errorf("%w %v", asset.ErrNotEnabled, a))
-	} else if !b.CurrencyPairs.Pairs[a].Enabled.Contains(pair, true) {
-		err = common.AppendError(err, fmt.Errorf("%w in enabled pairs %v", currency.ErrPairNotFound, pair))
+	var errs error
+	if err := b.CurrencyPairs.IsAssetEnabled(a); err != nil {
+		errs = common.AppendError(errs, err)
```
Comment (shazbert) [inline exchanges/exchange.go:1148]: suggestion: All these errors can be returned straight away as this will precipitate failures down stream and not have all these if else spaghetts.

File: exchanges/exchange.go [hunk 3]
```diff
@@ -1143,18 +1143,23 @@ func (b *Base) FormatExchangeKlineInterval(in kline.Interval) string {
...
+	} else {
+		ok, err := b.CurrencyPairs.IsPairEnabled(pair, a)
```
Comment (shazbert) [inline exchanges/exchange.go:1150]:
```suggestion
		ok, err := b.IsPairEnabled(pair, a)
```

**Review by shazbert — CHANGES_REQUESTED** [review]
🐱 meow

File: exchanges/exchange_test.go [hunk 4]
```diff
@@ -2242,266 +2233,148 @@ func TestHasAssetTypeAccountSegregation(t *testing.T) {
...
-
-	if r.RequestFormatted.String() != "BTCUSDT" {
-		t.Fatalf("received: '%v' but expected: '%v'", r.RequestFormatted.String(), "BTCUSDT")
-	}
-
-	if len(r.RangeHolder.Ranges) != 15 { // 15 request at max 100 candles == 1440 1 min candles.
-		t.Fatalf("received: '%v' but expected: '%v'", len(r.RangeHolder.Ranges), 15)
-	}
+	r, err := b.GetKlineExtendedRequest(p, asset.Spot, kline.OneHour, start, end)
+	require.NoError(t, err, "GetKlineExtendedRequest must not error")
```
Comment (gbjk) [inline exchanges/exchange_test.go:2367]: 🦍 May be omitted
```suggestion
	require.NoError(t, err)
```

**Review by gbjk — APPROVED** [review]
Good work. Nothing but a bunch of super-nitpicks which are optional.

**Review by gbjk — APPROVED** [review]

**Review by shazbert — APPROVED** [review]
ch ACK. thanks!
