### PR TITLE
script: initial implementation of error insertion on return

### LINKED ISSUE #969: gctscript status "OK" after error had happened and no more processing
# New Issue

## Context

I'm running several gctscripts scenarios. The problem is that if there is an error happened in the script it stops the processing.
However, the status of the script is "OK" and I couldn't find a proper way to restart the script.

* Operating System:
Linux mshogin 5.14.0-1038-oem 42-Ubuntu SMP Thu May 19 05:03:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* GoCryptoTrader version (`gocryptotrader -version`):
GoCryptoTrader v0.1 amd64 go1.17.10 pre-release.

## Expected Behavior

It could be helpful to have the status "FAILED".

## Current Behavior

After the error had happened the script status is the following

```
gctcli  script status
{
 "status": "2 of 10 virtual machines running",
 "scripts": [
  {
   "uuid": "5e7aec45-6722-4e38-9975-0c4b90ef725d",
   "name": "alpha.gct",
   "next_run": "2022-06-02 22:02:37.761560319 +0200 CEST m=+5005.488771720"
  }
 ]
}
```

```
gctcli  script query --uuid 5e7aec45-6722-4e38-9975-0c4b90ef725d                                    
{
 "status": "ok",
 "script": {
  "uuid": "5e7aec45-6722-4e38-9975-0c4b90ef725d",
  "name": "alpha.gct",
  "next_run": "2022-06-02 22:02:37.761560319 +0200 CEST m=+5005.488771720"
 },

```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. set the timer="5s"
2. exch.ordersubmit(... 'sell' ...)

### Failure Logs

[ERROR] | 02/06/2022 22:02:28 | GCT Script: (ACTION) RunCtx Runtime Error: FTX unsuccessful HTTP status code: 400 raw response: {"success":false,"error":"Not enough balances"}
        at -
        at -
        at (main):55:3
        at (main):63:1

### Notes
Yes, I'm going to add a balance checker to prevent this error in the future, but there could be other errors, and having the script status could help to restart the strategy in a proper way.
At the moment, I use the cron job 

```
#!/bin/bash

set -x
set -e

uuid=$(gctcli script status | grep -B1 alpha | grep UUID | head -n 1 | awk -F'"' '{print $4}')
gctcli script execute alpha 
gctcli script stop --uuid $uuid
```

### PR DESCRIPTION
**Pull request by shazbert**
# PR Description

resolves #969 

As per an excellent suggestion by @mshogin 

* Add error handling potential to certain calling functions via script and updated documentation and examples.

Also:

* Add further context awareness for verbosity created by script.
* Add further context awareness of account details so scripts can handle or manage their own credentials.

I have left some error returns as a runtime error for ease of finding issues in the script if:
a) There is an argument count issue.
b) There is a type issue.

~~This requires a merge of #956 due to the fact of a circular dependency issue when importing exchange package for credentials.~~

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: gctscript/modules/gct/common.go [hunk 1]
```diff
@@ -59,6 +59,26 @@ func WriteAsCSV(args ...objects.Object) (objects.Object, error) {
 		case indicators.OHLCV:
 			temp, err = convertOHLCV(args[i])
 			front = true
+		case "scriptContext":
```
Comment (gloriousCode) [inline gctscript/modules/gct/common.go:62]: To be clear, when you're outputting to a CSV, you're saying that you can either provide the ctx _or_ a filename? It may be good to update the csv.gct commentary to highlight this

**Review by gloriousCode — CHANGES_REQUESTED** [review]
This is nice. Allowing me to handle issues from commands is good 🎉

File: gctscript/modules/gct/errors.go [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+import (
+	"fmt"
+
+	objects "github.com/d5/tengo/v2"
+)
+
+// errorResponse is a helper function to apply error details to a return object
+// for better script side error handling
+func errorResponse(format string, a ...interface{}) (objects.Object, error) {
```
[the remark this answers is not in the document]
Comment (shazbert) [reply gctscript/modules/gct/errors.go:11]: You make a good point what I will do is check the data that goes into the function to actually contain something. Because if it is ever implemented and misconfigured then it should return an error as you suggest.

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Lovely update, thanks! I've tested all the example scripts now + tested the new subaccount context feature 🎉 Please just fix up the ded tests

File: gctscript/modules/gct/exchange.go [hunk 3]
```diff
@@ -252,23 +268,24 @@ func ExchangeAccountInfo(args ...objects.Object) (objects.Object, error) {
...
 func ExchangeOrderQuery(args ...objects.Object) (objects.Object, error) {
-	if len(args) < 2 {
+	if len(args) < 3 {
 		return nil, objects.ErrWrongNumArguments
 	}
 
-	exchangeName, ok := objects.ToString(args[0])
+	scriptCtx, ok := objects.ToInterface(args[0]).(*Context)
+	if !ok {
+		return nil, fmt.Errorf(ErrParameterConvertFailed, scriptCtx)
```
Comment (gloriousCode) [inline gctscript/modules/gct/exchange.go:282]: Pretty minor, but this seems like a good time for `common.GetAssertError()` instead

File: gctscript/vm/vm.go [hunk 4]
```diff
@@ -176,21 +171,18 @@ func (vm *VM) CompileAndRun() {
...
 			return
 		}
-		vm.runner()
-	} else {
-		err = vm.Shutdown()
-		if err != nil {
-			log.Error(log.GCTScriptMgr, err)
+
+		if vm.T > 0 {
+			log.Error(log.GCTScriptMgr, "Repeat timer cannot be under 1 nano second")
```
Comment (gloriousCode) [inline gctscript/vm/vm.go:180]: You made this a bit weird. You have if`vm.T >= time.Nanosecond {` aka  `vm.T > 0`,  followed by an actual `if vm.T > 0 {` The purpose of the test `TestVMWithRunnerInvalidTimer` was to error on an invalid timer which you've impacted.
Please review your changes

**Review by gloriousCode — CHANGES_REQUESTED** [review]

File: gctscript/vm/vm.go (hunk 4 above)
Comment (shazbert) [reply gctscript/vm/vm.go:180]: Good catch! Yeah, I have half a mind to remove the timer functionality completely in a future PR as we can dictate for loops and sleeps script side anyway.

File: gctscript/modules/gct/errors.go [hunk 5]
```diff
@@ -29,3 +30,10 @@ func errorResponsef(format string, a ...interface{}) (objects.Object, error) {
 		Value: &objects.String{Value: fmt.Sprintf(format, a...)},
 	}, nil
 }
+
+func constructRuntimeError(argPosition int, funcName, expectedType string, whatYouGot interface{}) error {
```
Comment (gloriousCode) [inline gctscript/modules/gct/errors.go:34]: `whatYouGot` 😄

Comment (gloriousCode) [reply gctscript/modules/gct/errors.go:34]: also please add dedicated test. Probably only need to just verify its return of a `common.ErrTypeAssertFailure`

File: gctscript/modules/gct/exchange.go [hunk 6]
```diff
@@ -670,38 +685,38 @@ func exchangeOHLCV(args ...objects.Object) (objects.Object, error) {
...
 	startTime, ok := objects.ToTime(args[5])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, startTime)
+		return nil, constructRuntimeError(6, ohlcvFunc, "string", args[5])
 	}
 
 	endTime, ok := objects.ToTime(args[6])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, endTime)
+		return nil, constructRuntimeError(5, ohlcvFunc, "time.Time", args[6])
```
Comment (gloriousCode) [inline gctscript/modules/gct/exchange.go:714]:
```suggestion
		return nil, constructRuntimeError(7, ohlcvFunc, "time.Time", args[6])
```

File: gctscript/modules/gct/exchange.go [hunk 7]
```diff
@@ -403,63 +439,69 @@ func ExchangeOrderCancel(args ...objects.Object) (objects.Object, error) {
...
+	orderSide, ok := objects.ToString(args[5])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, orderSide)
+		return nil, constructRuntimeError(6, orderSubmitFunc, "string", args[5])
 	}
-	orderPrice, ok := objects.ToFloat64(args[5])
+	orderPrice, ok := objects.ToFloat64(args[6])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, orderPrice)
+		return nil, constructRuntimeError(7, orderSubmitFunc, "string", args[6])
```
Comment (gloriousCode) [inline gctscript/modules/gct/exchange.go:472]:
```suggestion
		return nil, constructRuntimeError(7, orderSubmitFunc, "float64", args[6])
```

File: gctscript/modules/gct/exchange.go [hunk 8]
```diff
@@ -403,63 +439,69 @@ func ExchangeOrderCancel(args ...objects.Object) (objects.Object, error) {
...
 	}
-	orderAmount, ok := objects.ToFloat64(args[6])
+	orderAmount, ok := objects.ToFloat64(args[7])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, orderAmount)
+		return nil, constructRuntimeError(8, orderSubmitFunc, "string", args[7])
```
Comment (gloriousCode) [inline gctscript/modules/gct/exchange.go:476]:
```suggestion
		return nil, constructRuntimeError(8, orderSubmitFunc, "float64", args[7])
```

File: gctscript/modules/gct/exchange.go [hunk 9]
```diff
@@ -495,65 +536,67 @@ func ExchangeDepositAddress(args ...objects.Object) (objects.Object, error) {
 
 	exchangeName, ok := objects.ToString(args[0])
 	if !ok {
-		return nil, fmt.Errorf(ErrParameterConvertFailed, exchangeName)
+		return nil, constructRuntimeError(1, depositAddressFunc, "*gct.Context", args[0])
```
Comment (gloriousCode) [inline gctscript/modules/gct/exchange.go:539]:
```suggestion
		return nil, constructRuntimeError(1, depositAddressFunc, "string", args[0])
```

File: gctscript/modules/gct/gct.go [hunk 10]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+	if len(args) < 3 || len(args) > 7 {
+		return nil, objects.ErrWrongNumArguments
+	}
+
+	ctx, ok := objects.ToInterface(args[0]).(*Context)
+	if !ok {
+		return nil, constructRuntimeError(1, setAccountFunc, "*gct.Context", args[0])
+	}
+
+	apikey, ok := objects.ToInterface(args[1]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:63]:
```suggestion
	apikey, ok := objects.ToString(args[1])
```

File: gctscript/modules/gct/gct.go [hunk 11]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+		return nil, constructRuntimeError(2, setAccountFunc, "string", args[1])
+	}
+
+	if ctx.Value == nil {
+		ctx.Value = make(map[string]objects.Object)
+	}
+
+	ctx.Value["apikey"] = &objects.String{Value: apikey}
+
+	apisecret, ok := objects.ToInterface(args[2]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:74]:
```suggestion
	apisecret, ok := objects.ToString(args[2])
```

File: gctscript/modules/gct/gct.go [hunk 12]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+	if !ok {
+		return nil, constructRuntimeError(3, setAccountFunc, "string", args[2])
+	}
+
+	ctx.Value["apisecret"] = &objects.String{Value: apisecret}
+
+	if len(args) > 3 {
+		var subaccount string
+		subaccount, ok = objects.ToInterface(args[3]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:83]:
```suggestion
		subaccount, ok = objects.ToString(args[3])
```

File: gctscript/modules/gct/gct.go [hunk 13]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+		}
+
+		if subaccount != "" {
+			ctx.Value["subaccount"] = &objects.String{Value: subaccount}
+		}
+	}
+
+	if len(args) > 4 {
+		var clientID string
+		clientID, ok = objects.ToInterface(args[4]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:95]:
```suggestion
		clientID, ok = objects.ToString(args[4])
```

File: gctscript/modules/gct/gct.go [hunk 14]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+			return nil, constructRuntimeError(5, setAccountFunc, "string", args[4])
+		}
+		if clientID != "" {
+			ctx.Value["clientid"] = &objects.String{Value: clientID}
+		}
+	}
+
+	if len(args) > 5 {
+		var pemKey string
+		pemKey, ok = objects.ToInterface(args[5]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:106]:
```suggestion
		pemKey, ok = objects.ToString(args[5])
```

File: gctscript/modules/gct/gct.go [hunk 15]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+			return nil, constructRuntimeError(6, setAccountFunc, "string", args[5])
+		}
+		if pemKey != "" {
+			ctx.Value["pemkey"] = &objects.String{Value: pemKey}
+		}
+	}
+
+	if len(args) > 5 {
+		var oneTimePassword string
+		oneTimePassword, ok = objects.ToInterface(args[6]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:117]:
```suggestion
		oneTimePassword, ok = objects.ToString(args[6])
```

File: gctscript/modules/gct/gct.go [hunk 16]
```diff
@@ -8,3 +28,183 @@ func AllModuleNames() []string {
...
+	if len(args) != 2 {
+		return nil, objects.ErrWrongNumArguments
+	}
+
+	ctx, ok := objects.ToInterface(args[0]).(*Context)
+	if !ok {
+		return nil, constructRuntimeError(1, setSubAccountFunc, "*gct.Context", args[0])
+	}
+
+	sub, ok := objects.ToInterface(args[1]).(string)
```
Comment (gloriousCode) [inline gctscript/modules/gct/gct.go:141]:
```suggestion
	sub, ok := objects.ToString(args[1])
```

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Should be my last review 🎉

**Review by gloriousCode — APPROVED** [review]
tACK! Thanks for making those changes!

**Review by thrasher- — APPROVED** [review]
tACK - verbose, subaccount, set_account and error handling! Very nice addition, thanks for the suggestion @mshogin
