### PR TITLE
Okx: Fix authenticated websocket login

### LINKED ISSUE #1970: OKx order subscription
The order subscription channel of OKX will be disconnected after running for a period of time, and the order push message cannot be received

### PR DESCRIPTION
**Pull request by dazi005**
# PR Description

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1970 
if i use SendAuthenticatedWebsocketRequest,i will got err
image

e.Websocket.AuthConn.SendJSONMessage(ctx, request.Unset, op)   can login

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by thrasher-** [comment]
@codex please review

**Comment by dazi005** [comment]
[WARN]  | WEBSOCKET | 12/09/2025 22:25:43 | Okx websocket has been disconnected. Reason: websocket: close 4004: No data received in 30s.: connection fault ("wss://ws.okx.com:8443/ws/v5/private")
[ERROR] | WEBSOCKET | 12/09/2025 22:25:43 | exchange Okx websocket error - 'login-response' websocket response to request signature not matched with data {"event":"login","msg":"","code":"0","connId":"8fa135b4"}
[ERROR] | WEBSOCKET | 12/09/2025 22:25:43 | exchange Okx websocket error - websocket: close 4004: No data received in 30s.: connection fault ("wss://ws.okx.com:8443/ws/v5/private")

File: exchanges/okx/okx_websocket.go [hunk 1]
```diff
@@ -287,7 +287,7 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
 	e.Websocket.Wg.Add(1)
 	go e.wsReadData(ctx, e.Websocket.AuthConn)
 	e.Websocket.AuthConn.SetupPingHandler(request.Unset, websocket.PingHandler{
-		MessageType: gws.TextMessage,
+		MessageType: gws.PingMessage,
```
Comment (shazbert) [inline exchanges/okx/okx_websocket.go]: This needs to be reverted as it fails to send a correct ping message for auth connection and will make it unstable. I have added it to the diff.

File: exchanges/okx/okx_websocket.go [hunk 2]
```diff
@@ -311,8 +311,12 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
 			Sign:       base64.StdEncoding.EncodeToString(hmac),
 		},
 	}
+	op := WebsocketOp{
+		Op:   operationLogin,
+		Args: args,
+	}
 
-	return e.SendAuthenticatedWebsocketRequest(ctx, request.Unset, "login-response", operationLogin, args, nil)
+	return e.Websocket.AuthConn.SendJSONMessage(ctx, request.Unset, op)
```
Comment (shazbert) [inline exchanges/okx/okx_websocket.go]: Will need a response checker to validate correct state for trading ops. 

```diff
diff --git a/exchanges/okx/okx_types.go b/exchanges/okx/okx_types.go
index 86b79fa99..b950e9d85 100644
--- a/exchanges/okx/okx_types.go
+++ b/exchanges/okx/okx_types.go
@@ -3171,10 +3171,10 @@ type WebsocketLoginData struct {
        Sign       string `json:"sign"`
 }

-// WebsocketOp holds the operation and arguments
-type WebsocketOp struct {
-       Op   string `json:"op"`
-       Args any    `json:"args"`
+// WebsocketAuthLogin holds the operation and arguments
+type WebsocketAuthLogin struct {
+       Operation string               `json:"op"`
+       Arguments []WebsocketLoginData `json:"args"`
 }

 // SubscriptionInfo holds the channel and instrument IDs
diff --git a/exchanges/okx/okx_websocket.go b/exchanges/okx/okx_websocket.go
index 8af6df010..78db92db6 100644
--- a/exchanges/okx/okx_websocket.go
+++ b/exchanges/okx/okx_websocket.go
@@ -41,7 +41,7 @@ var (
        // See: https://www.okx.com/docs-v5/en/#error-code-websocket-public
        authConnErrorCodes = []string{
                "60007", "60022", "60023", "60024", "60026", "63999", "60032", "60011", "60009",
-               "60005", "60021", "60031", "50110",
+               "60005", "60021", "60031", "50110", "60033",
        }
 )

@@ -287,7 +287,7 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
        e.Websocket.Wg.Add(1)
        go e.wsReadData(ctx, e.Websocket.AuthConn)
        e.Websocket.AuthConn.SetupPingHandler(request.Unset, websocket.PingHandler{
-               MessageType: gws.PingMessage,
+               MessageType: gws.TextMessage,
                Message:     pingMsg,
                Delay:       time.Second * 20,
        })
@@ -303,20 +303,36 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
                return err
        }

-       args := []WebsocketLoginData{
-               {
-                       APIKey:     creds.Key,
-                       Passphrase: creds.ClientID,
-                       Timestamp:  ts,
-                       Sign:       base64.StdEncoding.EncodeToString(hmac),
+       op := WebsocketAuthLogin{
+               Operation: operationLogin,
+               Arguments: []WebsocketLoginData{
+                       {
+                               APIKey:     creds.Key,
+                               Passphrase: creds.ClientID,
+                               Timestamp:  ts,
+                               Sign:       base64.StdEncoding.EncodeToString(hmac),
+                       },
                },
        }
-       op := WebsocketOp{
-               Op:   operationLogin,
-               Args: args,
+
+       resp, err := e.Websocket.AuthConn.SendMessageReturnResponse(ctx, request.Unset, "login-response", op)
+       if err != nil {
+               return err
+       }
+
+       var intermediary struct {
+               Code    int64  `json:"code,string"`
+               Message string `json:"msg"`
+       }
+       if err := json.Unmarshal(resp, &intermediary); err != nil {
+               return err
+       }
+
+       if intermediary.Code == 0 {
+               return nil
        }

-       return e.Websocket.AuthConn.SendJSONMessage(ctx, request.Unset, op)
+       return getStatusError(intermediary.Code, intermediary.Message)
 }

 // wsReadData sends msgs from public and auth websockets to data handler
```

**Review by shazbert — CHANGES_REQUESTED** [review]
Thanks for opening this PR. I have tested the endpoints and they now screen out sending ID's.

Please apply this diff below if there are any issues or need help let me know! Nice work!

**Comment by dazi005** [comment]
image
Does this method also need to be adjusted in the same way as above?

**Comment by dazi005** [comment]
image
Now I can login without any problem, but it will still disconnect after a while and will not reconnect automatically

**Comment by dazi005** [comment]
image
Using it this way, there's no disconnection. I'll observe it for a few more days

**Comment by dazi005** [comment]
image
ping stop

**Comment by shazbert** [comment]
> Does this method also need to be adjusted in the same way as above?

Yeah I think so here's a diff:

```diff
diff --git a/exchanges/okx/okx_business_websocket.go b/exchanges/okx/okx_business_websocket.go
index 3e965bab1..27e0c2a0e 100644
--- a/exchanges/okx/okx_business_websocket.go
+++ b/exchanges/okx/okx_business_websocket.go
@@ -2,16 +2,12 @@ package okx

 import (
        "context"
-       "encoding/base64"
-       "fmt"
        "net/http"
-       "strconv"
        "strings"
        "time"

        gws "github.com/gorilla/websocket"
        "github.com/thrasher-corp/gocryptotrader/common"
-       "github.com/thrasher-corp/gocryptotrader/common/crypto"
        "github.com/thrasher-corp/gocryptotrader/currency"
        "github.com/thrasher-corp/gocryptotrader/encoding/json"
        "github.com/thrasher-corp/gocryptotrader/exchange/websocket"
@@ -55,15 +51,12 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
        dialer.WriteBufferSize = 8192

        e.Websocket.Conn.SetURL(okxBusinessWebsocketURL)
-       err := e.Websocket.Conn.Dial(ctx, &dialer, http.Header{})
-       if err != nil {
+       if err := e.Websocket.Conn.Dial(ctx, &dialer, http.Header{}); err != nil {
                return err
        }
-       e.Websocket.Wg.Add(1)
-       go e.wsReadData(ctx, e.Websocket.Conn)
+       e.Websocket.Wg.Go(func() { e.wsReadData(ctx, e.Websocket.Conn) })
        if e.Verbose {
-               log.Debugf(log.ExchangeSys, "Successful connection to %v\n",
-                       e.Websocket.GetWebsocketURL())
+               log.Debugf(log.ExchangeSys, "Successful connection to %v\n", e.Websocket.GetWebsocketURL())
        }
        e.Websocket.Conn.SetupPingHandler(request.UnAuth, websocket.PingHandler{
                MessageType: gws.TextMessage,
@@ -71,8 +64,7 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
                Delay:       time.Second * 20,
        })
        if e.Websocket.CanUseAuthenticatedEndpoints() {
-               err = e.WsSpreadAuth(ctx)
-               if err != nil {
+               if err := e.authenticateConnection(ctx, e.Websocket.Conn); err != nil { // auth conn not used as business ws uses single conn
                        log.Errorf(log.ExchangeSys, "Error connecting auth socket: %s\n", err.Error())
                        e.Websocket.SetCanUseAuthenticatedEndpoints(false)
                }
@@ -80,36 +72,6 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
        return nil
 }

-// WsSpreadAuth will connect to Okx's Private websocket connection and Authenticate with a login payload.
-func (e *Exchange) WsSpreadAuth(ctx context.Context) error {
-       if !e.Websocket.CanUseAuthenticatedEndpoints() {
-               return fmt.Errorf("%v AuthenticatedWebsocketAPISupport not enabled", e.Name)
-       }
-       creds, err := e.GetCredentials(ctx)
-       if err != nil {
-               return err
-       }
-       e.Websocket.SetCanUseAuthenticatedEndpoints(true)
-       ts := time.Now().Unix()
-       signPath := "/users/self/verify"
-       hmac, err := crypto.GetHMAC(crypto.HashSHA256,
-               []byte(strconv.FormatInt(ts, 10)+http.MethodGet+signPath),
-               []byte(creds.Secret),
-       )
-       if err != nil {
-               return err
-       }
-       args := []WebsocketLoginData{
-               {
-                       APIKey:     creds.Key,
-                       Passphrase: creds.ClientID,
-                       Timestamp:  ts,
-                       Sign:       base64.StdEncoding.EncodeToString(hmac),
-               },
-       }
-       return e.SendAuthenticatedWebsocketRequest(ctx, request.Unset, "login-response", operationLogin, args, nil)
-}
-
 // GenerateDefaultBusinessSubscriptions returns a list of default subscriptions to business websocket.
 func (e *Exchange) GenerateDefaultBusinessSubscriptions() ([]subscription.Subscription, error) {
        var subs []string
diff --git a/exchanges/okx/okx_websocket.go b/exchanges/okx/okx_websocket.go
index 78db92db6..b4ede0916 100644
--- a/exchanges/okx/okx_websocket.go
+++ b/exchanges/okx/okx_websocket.go
@@ -244,16 +244,13 @@ func (e *Exchange) WsConnect() error {
        var dialer gws.Dialer
        dialer.ReadBufferSize = 8192
        dialer.WriteBufferSize = 8192
-
-       err := e.Websocket.Conn.Dial(ctx, &dialer, http.Header{})
-       if err != nil {
+       if err := e.Websocket.Conn.Dial(ctx, &dialer, http.Header{}); err != nil {
                return err
        }
-       e.Websocket.Wg.Add(1)
-       go e.wsReadData(ctx, e.Websocket.Conn)
+
+       e.Websocket.Wg.Go(func() { e.wsReadData(ctx, e.Websocket.Conn) })
        if e.Verbose {
-               log.Debugf(log.ExchangeSys, "Successful connection to %v\n",
-                       e.Websocket.GetWebsocketURL())
+               log.Debugf(log.ExchangeSys, "Successful connection to %v\n", e.Websocket.GetWebsocketURL())
        }
        e.Websocket.Conn.SetupPingHandler(request.Unset, websocket.PingHandler{
                MessageType: gws.TextMessage,
@@ -261,8 +258,7 @@ func (e *Exchange) WsConnect() error {
                Delay:       time.Second * 20,
        })
        if e.Websocket.CanUseAuthenticatedEndpoints() {
-               err = e.WsAuth(ctx)
-               if err != nil {
+               if err := e.WsAuth(ctx); err != nil {
                        log.Errorf(log.ExchangeSys, "Error connecting auth socket: %s\n", err.Error())
                        e.Websocket.SetCanUseAuthenticatedEndpoints(false)
                }
@@ -275,24 +271,25 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
        if !e.AreCredentialsValid(ctx) || !e.Websocket.CanUseAuthenticatedEndpoints() {
                return fmt.Errorf("%v AuthenticatedWebsocketAPISupport not enabled", e.Name)
        }
-       creds, err := e.GetCredentials(ctx)
-       if err != nil {
-               return err
-       }
        var dialer gws.Dialer
-       err = e.Websocket.AuthConn.Dial(ctx, &dialer, http.Header{})
-       if err != nil {
+       if err := e.Websocket.AuthConn.Dial(ctx, &dialer, http.Header{}); err != nil {
                return err
        }
-       e.Websocket.Wg.Add(1)
-       go e.wsReadData(ctx, e.Websocket.AuthConn)
+       e.Websocket.Wg.Go(func() { e.wsReadData(ctx, e.Websocket.AuthConn) })
        e.Websocket.AuthConn.SetupPingHandler(request.Unset, websocket.PingHandler{
                MessageType: gws.TextMessage,
                Message:     pingMsg,
                Delay:       time.Second * 20,
        })
+       return e.authenticateConnection(ctx, e.Websocket.AuthConn)
+}
+
+func (e *Exchange) authenticateConnection(ctx context.Context, conn websocket.Connection) error {
+       creds, err := e.GetCredentials(ctx)
+       if err != nil {
+               return err
+       }

-       e.Websocket.SetCanUseAuthenticatedEndpoints(true)
        ts := time.Now().Unix()
        signPath := "/users/self/verify"
        hmac, err := crypto.GetHMAC(crypto.HashSHA256,
@@ -315,7 +312,7 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
                },
        }

-       resp, err := e.Websocket.AuthConn.SendMessageReturnResponse(ctx, request.Unset, "login-response", op)
+       resp, err := conn.SendMessageReturnResponse(ctx, request.Unset, "login-response", op)
        if err != nil {
                return err
        }
```

**Comment by shazbert** [comment]
> Now I can login without any problem, but it will still disconnect after a while and will not reconnect automatically

Have you subscribed to anything on that connection?

**Comment by shazbert** [comment]
@dazi005 I am having no connection issues here currently after an hour. Will keep it running today and see if there is anything that comes up.

**Comment by dazi005** [comment]
I subscribed, and after about 3 hours, the log will prompt disconnection, and ping will not continue, but my completed orders will still be pushed to me through socket, and the orders are also submitted to the exchange through socket, not http, haha

**Comment by dazi005** [comment]
panic: sync: negative WaitGroup counter

goroutine 11105 [running]:
sync.(*WaitGroup).Add(0xc0003760f8, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:118 +0x23a
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:156
github.com/thrasher-corp/gocryptotrader/exchanges/okx.(*Exchange).wsReadData(0xc0002bec08, {0x1efab98, 0x2bdadc0}, {0x1f05710, 0xc00060e460})
        /home/ubuntu/go/src/github.com/gocryptotrader/exchanges/okx/okx_websocket.go:342 +0xf6
created by github.com/thrasher-corp/gocryptotrader/exchanges/okx.(*Exchange).WsConnect in goroutine 235
        /home/ubuntu/go/src/github.com/gocryptotrader/exchanges/okx/okx_websocket.go:253 +0x196


I monitored for 2 hours and the following error occurred

**Comment by shazbert** [comment]
> panic: sync: negative WaitGroup counter
> I monitored for 2 hours and the following error occurred

@dazi005 😆 Yeah I got that as well after about 2 hours. I will have a check to see what happened soon. I think the core instability might just be an okx feature; but saying that we might have a problem with the ping routines like you suggest. Will add in more logging and see what is going on. Thanks!

**Comment by shazbert** [comment]
@dazi005 Please apply diff

```diff
diff --git a/exchange/websocket/connection.go b/exchange/websocket/connection.go
index 45f2be508..290a1577e 100644
--- a/exchange/websocket/connection.go
+++ b/exchange/websocket/connection.go
@@ -234,15 +234,12 @@ func (c *connection) SetupPingHandler(epl request.EndpointLimit, handler PingHan
                return
        }
        c.Wg.Go(func() {
-               ticker := time.NewTicker(handler.Delay)
                for {
                        select {
                        case <-c.shutdown:
-                               ticker.Stop()
                                return
-                       case <-ticker.C:
-                               err := c.SendRawMessage(context.TODO(), epl, handler.MessageType, handler.Message)
-                               if err != nil {
+                       case <-time.After(handler.Delay):
+                               if err := c.SendRawMessage(context.TODO(), epl, handler.MessageType, handler.Message); err != nil {
                                        log.Errorf(log.WebsocketMgr, "%v websocket connection: ping handler failed to send message [%s]: %v", c.ExchangeName, handler.Message, err)
                                        return
                                }
diff --git a/exchanges/okx/okx_websocket.go b/exchanges/okx/okx_websocket.go
index 61ea80d4f..4c8b3fe6b 100644
--- a/exchanges/okx/okx_websocket.go
+++ b/exchanges/okx/okx_websocket.go
@@ -282,7 +282,6 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
                Delay:       time.Second * 20,
        })
        return e.authenticateConnection(ctx, e.Websocket.AuthConn)
-
 }

 func (e *Exchange) authenticateConnection(ctx context.Context, conn websocket.Connection) error {
@@ -328,12 +327,10 @@ func (e *Exchange) authenticateConnection(ctx context.Context, conn websocket.Co
        }

        return getStatusError(intermediary.Code, intermediary.Message)
-
 }

 // wsReadData sends msgs from public and auth websockets to data handler
 func (e *Exchange) wsReadData(ctx context.Context, ws websocket.Connection) {
-       defer e.Websocket.Wg.Done()
        for {
                resp := ws.ReadMessage()
                if resp.Raw == nil {
```

**Review by shazbert — APPROVED** [review]
@dazi005 Thanks! Changes ACK.

**Comment by dazi005** [comment]
I have started it for more than an hour now, and everything is normal. I will continue to monitor it for a while. If there are any questions, I will reply here. Nice and thank you

**Comment by shazbert** [comment]
> I have started it for more than an hour now, and everything is normal. I will continue to monitor it for a while. If there are any questions, I will reply here. Nice and thank you

Thanks for working with me on this @dazi005 , moving from this I will add support later for websocket multiconnection so `business` related functionality will automatically connect as well. Then we can start to scale subscriptions to connections as there is a limit to the amount we can manage per connection at the moment. I think it's capped at ~200 which is not ideal. 🚀

File: exchanges/okx/okx_business_websocket.go [hunk 3]
```diff
@@ -55,61 +51,28 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
...
 		return err
 	}
-	e.Websocket.Wg.Add(1)
-	go e.wsReadData(ctx, e.Websocket.Conn)
+	e.Websocket.Wg.Go(func() { e.wsReadData(ctx, e.Websocket.Conn) })
+
 	if e.Verbose {
-		log.Debugf(log.ExchangeSys, "Successful connection to %v\n",
-			e.Websocket.GetWebsocketURL())
+		log.Debugf(log.ExchangeSys, "Successful connection to %v\n", e.Websocket.GetWebsocketURL())
```
Comment (gbjk) [inline exchanges/okx/okx_business_websocket.go]: 🦍 Optional pedantic nitpick, but that newline isn't needed.
```suggestion
		log.Debugf(log.ExchangeSys, "Successful connection to %v", e.Websocket.GetWebsocketURL())
```

File: exchanges/okx/okx_business_websocket.go [hunk 4]
```diff
@@ -55,61 +51,28 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
...
 	}
 	e.Websocket.Conn.SetupPingHandler(request.UnAuth, websocket.PingHandler{
 		MessageType: gws.TextMessage,
 		Message:     pingMsg,
 		Delay:       time.Second * 20,
 	})
 	if e.Websocket.CanUseAuthenticatedEndpoints() {
-		err = e.WsSpreadAuth(ctx)
-		if err != nil {
+		if err := e.authenticateConnection(ctx, e.Websocket.Conn); err != nil { // auth conn not used as business ws uses single conn
```
Comment (gbjk) [inline exchanges/okx/okx_business_websocket.go]: 🐒 Nitpick:
```suggestion
		if err := e.authenticateConnection(ctx, e.Websocket.Conn); err != nil { // business WS uses same conn for public and private
```

File: exchanges/okx/okx_business_websocket.go [hunk 5]
```diff
@@ -55,61 +51,28 @@ func (e *Exchange) WsConnectBusiness(ctx context.Context) error {
...
 			log.Errorf(log.ExchangeSys, "Error connecting auth socket: %s\n", err.Error())
```
Comment (gbjk) [inline exchanges/okx/okx_business_websocket.go]: 🐒  This error is factually incorrect now.
We also don't need to use `.Error()` because [fmt pkg docs](https://pkg.go.dev/fmt):
> 4. If an operand implements the error interface, the Error method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any).
```suggestion
			log.Errorf(log.ExchangeSys, "Error authenticating business websocket: %s", err)
```

File: exchanges/okx/okx_websocket.go [hunk 6]
```diff
@@ -245,24 +245,20 @@ func (e *Exchange) WsConnect() error {
...
+	if err := e.Websocket.Conn.Dial(ctx, &dialer, http.Header{}); err != nil {
 		return err
 	}
-	e.Websocket.Wg.Add(1)
-	go e.wsReadData(ctx, e.Websocket.Conn)
+	e.Websocket.Wg.Go(func() { e.wsReadData(ctx, e.Websocket.Conn) })
 	if e.Verbose {
-		log.Debugf(log.ExchangeSys, "Successful connection to %v\n",
-			e.Websocket.GetWebsocketURL())
+		log.Debugf(log.ExchangeSys, "Successful connection to %v\n", e.Websocket.GetWebsocketURL())
```
Comment (gbjk) [inline exchanges/okx/okx_websocket.go]:
```suggestion
		log.Debugf(log.ExchangeSys, "Successful connection to %v", e.Websocket.GetWebsocketURL())
```

**Review by gbjk — APPROVED** [review]
Good work 👍 

Nothing but optional 🐒 nitpicks and 🦍 super nitpicks from me.

**Review by gbjk — APPROVED** [review]

**Comment by dazi005** [comment]
I restarted 3 times, and each time it took about 3 hours, the ping would stop.

**Comment by dazi005** [comment]
[WARN]  | WEBSOCKET | 18/09/2025 11:37:47 | Okx websocket has been disconnected. Reason: websocket: close 1001 (going away): CloudFlare WebSocket proxy restarting: connection fault ("wss://ws.okx.com:8443/ws/v5/private")

**Comment by dazi005** [comment]
image
image
I tried adding a method like this, and it ran for a long time but still didn't disconnect. I continue to monitor...

**Comment by shazbert** [comment]
@dazi005 I will run it today and monitor it and see if there is anything silly going on.

**Comment by dazi005** [comment]
image
[WARN]  | WEBSOCKET | 20/09/2025 16:30:11 | Okx websocket has been disconnected. Reason: websocket: close 1006 (abnormal closure): unexpected EOF: connection fault ("wss://ws.okx.com:8443/ws/v5/private")
line 954 and line 961  When the above error occurs, I added fmt log to these two lines of code but no output was found.

**Comment by shazbert** [comment]
@dazi005 

I have been running an instance for majority of the day will keep it running over night and see. Are you still seeing issues with the ping handler stopping?

**Comment by dazi005** [comment]
> @dazi005
> 
> I have been running an instance for majority of the day will keep it running over night and see. Are you still seeing issues with the ping handler stopping?

I changed to multisocket management according to bybit, and ran it for a day without finding any problems

**Comment by dazi005** [comment]
image

**Comment by shazbert** [comment]
> > @dazi005
> > I have been running an instance for majority of the day will keep it running over night and see. Are you still seeing issues with the ping handler stopping?
> 
> I changed to multisocket management according to bybit, and ran it for a day without finding any problems

@dazi005 Good news! I have also forcefully shutdown connections on my current instance and the ping handlers come back up on reconnection, will keep it running in the meantime. Is this PR okay to be merged?

**Comment by dazi005** [comment]
image

**Comment by dazi005** [comment]
I'll sort out the code and submit it, and you can see if there are any problems

**Comment by shazbert** [comment]
@dazi005 can confirm error occurs on ping handler:
```
[WARN]  | WEBSOCKET | 29/09/2025 13:54:48 | Okx websocket has been disconnected. Reason: websocket: close 4004: No data received in 30s.: connection fault ("wss://ws.okx.com:8443/ws/v5/public")
```
The current changes are broken and the addition of the multi-connection update adds a bit more on review toil due to the broad impacts it does. I will see if I can take a look at this ASAP and fix the ping handler because this will likely not be an isolated issue and seems to be the root cause.

**Comment by shazbert** [comment]
@dazi005 Can you please reset HEAD~ --hard^3 for the current merge and the previous 2 commits I have a fix incoming.

**Comment by shazbert** [comment]
@dazi005 

Could you please apply [this diff](https://gist.github.com/shazbert/9002ab97680b165f37e14bf2bff3aae3) to commit https://github.com/thrasher-corp/gocryptotrader/pull/2051/commits/d1c653f2fecb3ec08d75c87f09363275b9fa0947

**Comment by shazbert** [comment]
@dazi005 once you are certain of stability could you please also address the linter issues [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/18117537016/job/51556092552?pr=2051) that I created 😭 sorry.

**Comment by shazbert** [comment]
@dazi005 and this test issue: https://github.com/thrasher-corp/gocryptotrader/actions/runs/18117537021/job/51556092526?pr=2051#step:11:188 🙏

**Comment by dazi005** [comment]
> once you are certain of stability could you please also address the linter issues [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/18117537016/job/51556092552?pr=2051) that I created 😭 sorry.

So far, the ping has not stopped. There have been disconnections in the middle, but they will automatically reconnect, so the ping will continue to be sent.

**Comment by shazbert** [comment]
> > once you are certain of stability could you please also address the linter issues [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/18117537016/job/51556092552?pr=2051) that I created 😭 sorry.
> 
> So far, the ping has not stopped. There have been disconnections in the middle, but they will automatically reconnect, so the ping will continue to be sent.

@dazi005 Yeah that is expected with okx, great news! Do you need help with the linter and test fixes?

**Comment by dazi005** [comment]
> > > once you are certain of stability could you please also address the linter issues [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/18117537016/job/51556092552?pr=2051) that I created 😭 sorry.
> > 
> > 
> > So far, the ping has not stopped. There have been disconnections in the middle, but they will automatically reconnect, so the ping will continue to be sent.
> 
> @dazi005 Yeah that is expected with okx, great news! Do you need help with the linter and test fixes?

Haha, I am not very proficient in code, and my writing is not very good. Can you help me take a look? I am still learning. Thank you very much.

**Comment by shazbert** [comment]
@dazi005 You are doing a great job! Yes I will have a look. Do you have slack because we can chat there which might be easier. [Here's the link](https://join.slack.com/t/gocryptotrader/shared_invite/zt-38z8abs3l-gH8AAOk8XND6DP5NfCiG_g)

**Comment by shazbert** [comment]
@dazi005 Here's the fix for the final test issue.

```diff
diff --git a/exchange/websocket/manager_test.go b/exchange/websocket/manager_test.go
index fd732bc04..fab7487b5 100644
--- a/exchange/websocket/manager_test.go
+++ b/exchange/websocket/manager_test.go
@@ -1088,7 +1088,7 @@ func TestConnectionShutdown(t *testing.T) {
        t.Parallel()
        wc := connection{shutdown: make(chan struct{})}
        err := wc.Shutdown()
-       assert.NoError(t, err, "Shutdown should not error")
+       assert.ErrorIs(t, err, common.ErrNilPointer, "Shutdown should error correctly")

        err = wc.Dial(t.Context(), &gws.Dialer{}, nil)
        assert.ErrorContains(t, err, "malformed ws or wss URL", "Dial should error correctly")
```

File: exchange/websocket/connection.go [hunk 7]
```diff
@@ -368,8 +366,8 @@ func (c *connection) defaultGenerateMessageID(highPrec bool) int64 {
 
 // Shutdown shuts down and closes specific connection
 func (c *connection) Shutdown() error {
-	if c == nil || c.Connection == nil {
-		return nil
+	if err := common.NilGuard(c, c.Connection); err != nil {
```
Comment (gloriousCode) [inline exchange/websocket/connection.go:369]: Sorry this is incorrect.
```go
if err := common.NilGuard(c); err != nil {
    return err
}
if err := common.NilGuard(c.Connection); err != nil {
    return err
}
```

This is because `common.NilGuard` does not return on first nil - which would arguably be the best implementation. If we're guarding against nils, any nil is a problem. This is out-of-scope here though

If `c` is `nil`, `c.Connection` check will panic. Please update with my snippet above

File: exchange/websocket/manager.go [hunk 8]
```diff
@@ -682,11 +681,23 @@ func (m *Manager) shutdown() error {
...
 	m.subscriptions.Clear()
 
-	m.setState(disconnectedState)
-
 	close(m.ShutdownC)
+	m.setState(disconnectedState)
 	m.Wg.Wait()
 	m.ShutdownC = make(chan struct{})
+
+	// Field connections are persistent once set, so we need to reassign the shutdown channel
```
Comment (gloriousCode) [inline exchange/websocket/manager.go]: I think this comment isn't very helpful or clear and can just be removed. But this is optional

File: exchanges/okx/okx_websocket.go [hunk 9]
```diff
@@ -303,21 +299,38 @@ func (e *Exchange) WsAuth(ctx context.Context) error {
...
+	if err := json.Unmarshal(resp, &intermediary); err != nil {
+		return err
+	}
+
+	if intermediary.Code == 0 {
+		return nil
+	}
 
-	return e.SendAuthenticatedWebsocketRequest(ctx, request.Unset, "login-response", operationLogin, args, nil)
+	return getStatusError(intermediary.Code, intermediary.Message)
```
Comment (gloriousCode) [inline exchanges/okx/okx_websocket.go]:
```go
if intermediary.Code != 0 {
    return getStatusError(intermediary.Code, intermediary.Message)
}
return nil
```
Optional, but better code flow

File: exchange/websocket/manager.go [hunk 10]
```diff
@@ -633,15 +633,14 @@ func (m *Manager) Shutdown() error {
 }
 
 func (m *Manager) shutdown() error {
-	if !m.IsConnected() {
-		return fmt.Errorf("%v %w: %w", m.exchangeName, errCannotShutdown, ErrNotConnected)
-	}
-
-	// TODO: Interrupt connection and or close connection when it is re-established.
```
Comment (gloriousCode) [inline exchange/websocket/manager.go:640]: Is this no longer desired @shazbert ?
edit: you're a caller's problem xoxo

Comment (shazbert) [reply exchange/websocket/manager.go:640]: Not really that can be a callers problem
edit: no you! ❤️

File: exchange/websocket/connection.go [hunk 11]
```diff
@@ -240,15 +241,12 @@ func (c *connection) SetupPingHandler(epl request.EndpointLimit, handler PingHan
...
 		for {
 			select {
 			case <-c.shutdown:
-				ticker.Stop()
 				return
-			case <-ticker.C:
-				err := c.SendRawMessage(context.TODO(), epl, handler.MessageType, handler.Message)
-				if err != nil {
+			case <-time.After(handler.Delay):
+				if err := c.SendRawMessage(context.TODO(), epl, handler.MessageType, handler.Message); err != nil {
```
Comment (gbjk) [inline exchange/websocket/connection.go]: 🦍 Optional pedantic nitpick:
I'd say that context that context.Background is more appropriate here, since this is in a goro.
```suggestion
				if err := c.SendRawMessage(context.Background(), epl, handler.MessageType, handler.Message); err != nil {
```

File: exchange/websocket/manager.go [hunk 12]
```diff
@@ -682,11 +681,23 @@ func (m *Manager) shutdown() error {
...
+	m.setState(disconnectedState)
 	m.Wg.Wait()
 	m.ShutdownC = make(chan struct{})
+
+	// Field connections are persistent once set, so we need to reassign the shutdown channel
+	for _, conn := range []Connection{m.Conn, m.AuthConn} {
+		if conn == nil {
+			continue
+		}
+		underlying, ok := conn.(*connection)
```
Comment (gbjk) [inline exchange/websocket/manager.go]: 🚧 Change request:
This isn't actually the underlying though.
Naming of the range var is a bit up in the air.
I rarely want to do this to an interface type like this, so I'd fall back to treating it like an `any` when naming. `connInterface` or `connIface` works too
```suggestion
		conn, ok := connA.(*connection)
```

File: exchange/websocket/manager.go (hunk 8 above)
Comment (gbjk) [reply exchange/websocket/manager.go]: 🚧 Change request:
I agree with this comment. And I was left still wondering "_why do we need to?_".
What would happen if we didn't?
Why aren't we assigning `nil` to it?
So I'd actually want a better comment for future maintainers to understand the motivation for assigning the manager channel to it, which feels wrong to me.

File: exchange/websocket/connection.go (hunk 7 above)
Comment (gloriousCode) [reply exchange/websocket/connection.go:369]: Rather than have this updated, I have opened a pull request so this is addressed that way 🌈 

edit: you updated it anyway 😄 I've still made the PR

File: exchange/websocket/connection.go (hunk 11 above)
Comment (shazbert) [reply exchange/websocket/connection.go]: Disagree with this because we can pass on cancellations/deadlines and verbosity but no need to change it back.

**Review by shazbert — APPROVED** [review]
ch ACK.

File: exchange/websocket/manager.go (hunk 8 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: @dazi005 please let us know if you're happy to make this change

File: exchanges/okx/okx_types.go [hunk 13]
```diff
@@ -3171,6 +3171,12 @@ type WebsocketLoginData struct {
 	Sign       string `json:"sign"`
 }
 
+// WebsocketOp holds the operation and arguments
+type WebsocketOp struct {
+	Op   string `json:"op"`
+	Args any    `json:"args"`
```
[the remark this answers is not in the document]
Comment (ajonathan007) [reply exchanges/okx/okx_types.go]: compile

[the remark this answers is not in the document]
Comment (ajonathan007) [reply exchanges/okx/okx_types.go]: compil

[the remark this answers is not in the document]
Comment (shazbert) [reply exchanges/okx/okx_types.go]: @ajonathan007 What do you mean?
