### PR TITLE
backtester/engine: Fix TestStart race

### LINKED ISSUE #1987: backtester: Investigate TestStart race
Spotted here: https://github.com/thrasher-corp/gocryptotrader/actions/runs/16561869416/job/46833027347#step:11:92

```
==================
WARNING: DATA RACE
Write at 0x00c0006fe748 by goroutine 52:
  github.com/thrasher-corp/gocryptotrader/backtester/engine.(*dataChecker).Start()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live.go:79 +0x1a4
  github.com/thrasher-corp/gocryptotrader/backtester/engine.TestStart()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live_test.go:77 +0x151
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1851 +0x44

Previous read at 0x00c0006fe748 by goroutine 126:
  github.com/thrasher-corp/gocryptotrader/backtester/engine.(*dataChecker).SignalStopFromError()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live.go:122 +0x199
  github.com/thrasher-corp/gocryptotrader/backtester/engine.(*dataChecker).Start.func1()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live.go:83 +0x7c

Goroutine 52 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:2142 +0xeea
  main.main()
      _testmain.go:179 +0x164

Goroutine 126 (running) created at:
  github.com/thrasher-corp/gocryptotrader/backtester/engine.(*dataChecker).Start()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live.go:80 +0x244
  github.com/thrasher-corp/gocryptotrader/backtester/engine.TestStart()
      /home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live_test.go:71 +0xe5
  testing.tRunner()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /opt/hostedtoolcache/go/1.24.5/x64/src/testing/testing.go:1851 +0x44
==================
--- FAIL: TestStart (0.00s)
    live_test.go:78: 
        	Error Trace:	/home/runner/work/gocryptotrader/gocryptotrader/backtester/engine/live_test.go:78
        	Error:      	Target error should be in err chain:
        	            	expected: "subsystem already started"
        	            	in chain: 
        	Test:       	TestStart
    testing.go:1490: race detected during execution of test
--- FAIL: TestFetchLatestData (0.03s)
    testing.go:1490: race detected during execution of test
--- FAIL: TestSetupFromConfig (21.28s)
    testing.go:1490: race detected during execution of test
--- FAIL: TestExecuteStrategyFromConfig (40.46s)
    testing.go:1490: race detected during execution of test
FAIL
coverage: 73.4% of statements
FAIL	github.com/thrasher-corp/gocryptotrader/backtester/engine	41.027s
```

### PR DESCRIPTION
**Pull request by MathieuCesbron**
# PR Description

TestStart does 3 tests
test1 = Start() with no error
test2 = Start() on an already started struct
test3 = Start() on nil

Previously, test1 and test2 were on the same struct. Depending on the go scheduler, we could have test2 fail because the field "started" could go from 1 to 0 just after the atomic compare and swap. So we would Start() a second time on the same struct but the field "started" would already be back to 0.

Fixes #1987 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: backtester/engine/live_test.go [hunk 1]
```diff
@@ -65,20 +64,23 @@ func TestSetupLiveDataHandler(t *testing.T) {
...
-	close(dc.shutdown)
-	dc.wg.Wait()
-	atomic.CompareAndSwapUint32(&dc.started, 0, 1)
-	err = dc.Start()
+	close(dc1.shutdown)
+	dc1.wg.Wait()
+
+	dc2 := &dataChecker{
+		started: 1,
+	}
```
[the remark this answers is not in the document]
Comment (MathieuCesbron) [reply backtester/engine/live_test.go]: I pushed a new commit to divide the test function in 3 tests more clearly.

File: backtester/engine/live_test.go [hunk 2]
```diff
@@ -65,21 +64,33 @@ func TestSetupLiveDataHandler(t *testing.T) {
...
-	}
-	err := dc.Start()
-	assert.NoError(t, err)
+	t.Run("successful start", func(t *testing.T) {
+		t.Parallel()
+		dc := &dataChecker{
+			shutdown: make(chan bool),
+		}
+		err := dc.Start()
+		assert.NoError(t, err)
```
Comment (gbjk) [inline backtester/engine/live_test.go]: 🚧 I think this needs to be a require
```suggestion
		require.NoError(t, err)
```

File: backtester/engine/live_test.go [hunk 3]
```diff
@@ -65,21 +64,33 @@ func TestSetupLiveDataHandler(t *testing.T) {
...
+
+		close(dc.shutdown)
+		dc.wg.Wait()
```
Comment (gbjk) [inline backtester/engine/live_test.go]: 🚧 I think this needs to use `assert.Eventually` 🙂 
It's much cleaner that way than letting the test just timeout blindly on failure, especially since you can have a comment to explain the expectation.

Shout if you need help with this.

File: backtester/engine/live_test.go [hunk 4]
```diff
@@ -65,21 +64,33 @@ func TestSetupLiveDataHandler(t *testing.T) {
...
-	err = dc.Start()
-	assert.ErrorIs(t, err, engine.ErrSubSystemAlreadyStarted)
+	t.Run("already started", func(t *testing.T) {
+		t.Parallel()
+		dc := &dataChecker{
+			started: 1,
+		}
+		err := dc.Start()
+		assert.ErrorIs(t, err, engine.ErrSubSystemAlreadyStarted)
+	})
```
Comment (gbjk) [inline backtester/engine/live_test.go]: 🐒 Optional nitpick:
This doesn't feel like it needs to be in a t.Run at all.
And if it's not, we could just re-use the `dc` from above.
Can also fold the `err` into the `assert` line, since it's so simple.

File: backtester/engine/live_test.go [hunk 5]
```diff
@@ -65,21 +64,33 @@ func TestSetupLiveDataHandler(t *testing.T) {
...
 
-	var dh *dataChecker
-	err = dh.Start()
-	assert.ErrorIs(t, err, gctcommon.ErrNilPointer)
+	t.Run("nil pointer", func(t *testing.T) {
+		t.Parallel()
+		var dc *dataChecker
+		err := dc.Start()
+		assert.ErrorIs(t, err, gctcommon.ErrNilPointer)
```
Comment (gbjk) [inline backtester/engine/live_test.go]: 🐒 Optional nitpick
* Also think this can lose the subtest, which means I don't really think we need any sub-tests here at all.
* And prefer to move nil checks like this to be the first thing we do
```suggestion
		assert.ErrorIs(t, (*dataChecker)(nil).Start(), gctcommon.ErrNilPointer)
```

**Review by gbjk — CHANGES_REQUESTED** [review]
Great work and thank you for the contribution 🙏 

I've made one change request 🚧 
The rest are optional improvements and nitpicks 🐒 

If you're not inclined to make the changes or want help, reach out on slack and I can help by providing a patch.

File: backtester/engine/live_test.go (hunk 2 above)
Comment (MathieuCesbron) [reply backtester/engine/live_test.go]: Thanks, I agree it's better.

File: backtester/engine/live_test.go (hunk 3 above)
Comment (MathieuCesbron) [reply backtester/engine/live_test.go]: I agree that we should not call `wg.Wait()` in testing without `assert.Eventually` because it could wait forever. But right now it's everywhere in testing. If we want to change it, let's do it everywhere at once in another commit ?

File: backtester/engine/live_test.go (hunk 4 above)
Comment (MathieuCesbron) [reply backtester/engine/live_test.go]: We cannot re-use the `dc` from above because it could led to a data race. 

We could remove the `t.Run` because it only helps to give a name to the test and give structure but tell me if the added verbosity is worth it or not 👍

About folding the `err` in the `assert`, I could do it if you prefer, but it's like that for the entire file, e.g. testing the stop later: `err = dc.Stop() and assert.NoError(t, err)`. If we are gonna change it, let's do it everywhere at once in another commit ?

File: backtester/engine/live_test.go (hunk 5 above)
Comment (MathieuCesbron) [reply backtester/engine/live_test.go]: I agree we should move it in the first place 👍 

I will remove subtests then.

**Review by shazbert — APPROVED** [review]
ch ACK.

**Review by thrasher- — APPROVED** [review]
tACK, thank you for your contribution and for resolving this issue @MathieuCesbron  🚀 !
