### PR TITLE
Okx: Fix websocket candle subscription handling

### LINKED ISSUE #1979: How should I use the WebSocket of gocryptotrader?
`func TestOkx_Klines1(t *testing.T) {
	ex := new(okx.Exchange)
	ex.SetDefaults()

	enabled := true
	cfg := &config.Exchange{
		Name:          "Okx",
		Enabled:       true,
		Websocket:     &enabled,
		HTTPDebugging: true,
		Verbose:       true,
		Features: &config.FeaturesConfig{
			Supports: config.FeaturesSupportedConfig{
				Websocket: true,
				WebsocketCapabilities: protocol.Features{
					KlineFetching:   true,
					AutoPairUpdates: true,
					Subscribe:       true,
				},
			},
		},
		WebsocketTrafficTimeout: 15 * time.Second,
	}

	if err := ex.Setup(cfg); err != nil {
		t.Fatal("Setup failed:", err)
	}

	if err := ex.Websocket.Enable(); err != nil {
		t.Fatal("WebSocket Enable failed:", err)
	}

	time.Sleep(3 * time.Second)

	sub := &subscription.Subscription{
		Enabled:  true,
		Channel:  subscription.CandlesChannel,
		Asset:    asset.Spot,
		Pairs:    []currency.Pair{currency.NewPair(currency.BTC, currency.USDT)},
		Interval: kline.OneMin,
	}

	err := ex.Websocket.SubscribeToChannels(ex.Websocket.Conn, subscription.List{sub})
	if err != nil {
		t.Fatal(err)
	}

	for {
		select {
		case msg := <-ex.Websocket.DataHandler:
			fmt.Printf("✅ Received message: %T %+v\n", msg, msg)
		case <-time.After(30 * time.Second):
			fmt.Println("⏰ No data in 30s")
			if !ex.Websocket.IsConnected() {
				fmt.Println("🔌 Disconnected, reconnecting...")
				_ = ex.Websocket.Connect()
			}
		}
	}
}`

I would like to subscribe to Kline's events.，But it always prints: "No data in 30 seconds"

### PR DESCRIPTION
**Pull request by gbjk**
* Okx: Fix MarkPriceCandles not including Pair
* Fix panic in BusinessSubscribe when no pairs
* Fix websocket candle subscription handling

Note: This is aimed at a bare minimum footprint.
There's a lot of refactoring and driveby fixes that I wanted to do, but then this would become huge.
I tried 3 times to find a middle ground, but I've ended up being super targetted.
I'll raise a PR for a broader task of refactoring the candle handling at the same time as folding the business websocket logic into the main websocket.

TL;RA: There's a lot of out-of-scope here that we're all aware of. Please review this in isolation and don't bother to highlight OOS.

Fixes #1979

### CODE REVIEW

File: exchanges/okx/okx_business_websocket.go [hunk 1]
```diff
@@ -178,28 +180,32 @@ func (e *Exchange) handleBusinessSubscription(ctx context.Context, operation str
...
+			if len(subscriptions[i].Pairs) != 1 {
+				return currency.ErrCurrencyPairEmpty
+			}
+			arg.InstrumentID = subscriptions[i].Pairs[0]
 		}
-		instrumentFamilyInterface, okay := subscriptions[i].Params["instFamily"]
-		if okay {
-			instrumentFamily, _ = instrumentFamilyInterface.(string)
+
+		if strings.HasPrefix(arg.Channel, candle) || strings.HasPrefix(arg.Channel, indexCandlestick) || strings.HasPrefix(arg.Channel, markPrice) {
```
[the remark this answers is not in the document]
Comment (gloriousCode) [reply exchanges/okx/okx_business_websocket.go:197]: Excuse me Mr AI, the constants are defined eg `candle = "candle"`

File: exchanges/okx/okx_test.go [hunk 2]
```diff
@@ -6093,6 +6094,46 @@ func TestGenerateSubscriptions(t *testing.T) {
...
+			case websocket.KlineData:
+				got = got.Add(v.Pair)
+			case []CandlestickMarkPrice:
+				if len(v) > 0 {
+					got = got.Add(v[0].Pair)
+				}
+			}
+		default:
+		}
+		return len(got) == 3
```
Comment (gloriousCode) [inline exchanges/okx/okx_test.go:6129]: [nitpick] I think the thing that would make me happiest is to make it totally unambiguous about what you're expecting here. 
```go
return got.Contains(mainPair, true) &&
			got.Contains(currency.NewPairWithDelimiter("ETH", "USDT", "-"), true) &&
			got.Contains(currency.NewPairWithDelimiter("OKB", "USDT", "-"), true)
	
```
Or making `got` `got := make(map[currency.Pair]struct{})` to continue using the len check. 

This is only because of there being two `case` scenarios and expecting three results, and since its a simple `.Add` call, that data could be returned twice from one endpoint and not hit all three. Apologies if I'm not clear. I want it more explicit you're getting the data you want

File: exchanges/okx/okx_test.go [hunk 3]
```diff
@@ -6093,6 +6094,46 @@ func TestGenerateSubscriptions(t *testing.T) {
...
+	}
+
+	var got currency.Pairs
+	assert.Eventually(t, func() bool {
+		select {
+		case a := <-e.Websocket.DataHandler:
+			switch v := a.(type) {
+			case websocket.KlineData:
+				got = got.Add(v.Pair)
+			case []CandlestickMarkPrice:
```
Comment (gloriousCode) [inline exchanges/okx/okx_test.go:6122]: [bonus points] scrap `CandlestickMarkPrice` in function `wsHandleMarkPriceCandles` and change it to `websocket.KlineData`

```go
candles := make([]websocket.KlineData, len(m.Data))
	for x := range m.Data {
		candles[x] = websocket.KlineData{
			Pair:       m.Argument.InstrumentID,
			Timestamp:  time.UnixMilli(m.Data[x][0].Int64()),
			OpenPrice:  m.Data[x][1].Float64(),
			HighPrice:  m.Data[x][2].Float64(),
			LowPrice:   m.Data[x][3].Float64(),
			ClosePrice: m.Data[x][4].Float64(),
		}
	}
	e.Websocket.DataHandler <- candles
```

```suggestion
			case []kline.KlineData:
```

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Looks good, thanks!

File: exchanges/okx/okx_test.go (hunk 2 above)
Comment (gbjk) [reply exchanges/okx/okx_test.go:6129]: `pairs.Add` [ignores duplicates](https://github.com/thrasher-corp/gocryptotrader/blob/master/currency/pairs.go#L219)

Do you think we need a comment to explain it?
Normally I'd just add one, but it feels like once we're past this review, the comment would be self-evident

File: exchanges/okx/okx_test.go (hunk 3 above)
Comment (gbjk) [reply exchanges/okx/okx_test.go:6122]: Respectfully declining bonus mission, because:

> TL;RA: There's a lot of out-of-scope here that we're all aware of. Please review this in isolation and don't bother to highlight OOS.

If I start down that road, I *know* I'm going to end up shaving yaks, because I've taken 2 swings at `websocket.KlineData` already in the past.

**Comment by gbjk** [comment]
> Suggestion: Probably better to convert this over to multi connection websocket so consumer doesn't have to override the default connection.

Respectfully declining; Since this is a lite-weight version of addressing candle handling and okx business websocket.
I'll definitely do it. Just not in this PR.

File: exchanges/okx/okx_test.go (hunk 3 above)
Comment (gloriousCode) [reply exchanges/okx/okx_test.go:6122]: Can't believe you expected me to read, wow

That's fine by me

File: exchanges/okx/okx_test.go (hunk 2 above)
Comment (gloriousCode) [reply exchanges/okx/okx_test.go:6129]: I swear I checked that, but I'll look at what you've written and if so it should be fine. I modified your test have len == 5 match, which is what made me make my comment. I'll recheck before guiding what to do

Comment (gbjk) [reply exchanges/okx/okx_test.go:6129]: `len == 5` should have failed. It fails for me.
I don't see how it could pass ... We don't connect any other websocket, or any other subscriptions.
It seems impossible you could get 5. If you can reproduce I'll be very interested.

**Comment by shazbert** [comment]
> > Suggestion: Probably better to convert this over to multi connection websocket so consumer doesn't have to override the default connection.
> 
> Respectfully declining; Since this is a lite-weight version of addressing candle handling and okx business websocket. I'll definitely do it. Just not in this PR.

🚀 sounds good

**Comment by thrasher-** [comment]
@codex please review

File: exchanges/okx/okx_test.go (hunk 2 above)
Comment (gloriousCode) [reply exchanges/okx/okx_test.go:6129]: Unimportant now, but I remember what I did and it was modify currency.Pairs to []currency.Pair and check there. So in my investigation into your test, I screwed it up and then complained to you about that screwup. I don't know why you didn't fix my issues that you could not see 😭

File: exchanges/okx/okx_test.go [hunk 4]
```diff
@@ -6093,6 +6094,46 @@ func TestGenerateSubscriptions(t *testing.T) {
 	testsubs.EqualLists(t, exp, subs)
 }
 
+func TestWsCandles(t *testing.T) {
+	t.Parallel()
+	e := new(Exchange) //nolint:govet // Intentional shadow
+	require.NoError(t, testexch.Setup(e), "Setup must not error")
+
+	err := e.WsConnectBusiness(t.Context())
+	require.NoError(t, err, "WsBusinessConnect must not error")
```
Comment (thrasher-) [inline exchanges/okx/okx_test.go]:
```suggestion
	require.NoError(t, err, "WsConnectBusiness must not error")
```

File: exchanges/okx/okx_test.go [hunk 5]
```diff
@@ -6093,6 +6094,46 @@ func TestGenerateSubscriptions(t *testing.T) {
 	testsubs.EqualLists(t, exp, subs)
 }
 
+func TestWsCandles(t *testing.T) {
```
Comment (thrasher-) [inline exchanges/okx/okx_test.go]:
```suggestion
func TestBusinessWSCandleSubscriptions(t *testing.T) {
```

Comment (gbjk) [reply exchanges/okx/okx_test.go]: Fixed gbjk@8d450ab9f

File: exchanges/okx/okx_test.go (hunk 4 above)
Comment (gbjk) [reply exchanges/okx/okx_test.go]: Fixed gbjk@8d450ab9f

**Comment by gbjk** [comment]
@thrasher- Thanks.

Rebased and squashed.

File: exchanges/okx/okx_test.go [hunk 6]
```diff
@@ -6093,6 +6094,46 @@ func TestGenerateSubscriptions(t *testing.T) {
...
+			case []CandlestickMarkPrice:
+				if len(v) > 0 {
+					got = got.Add(v[0].Pair)
+				}
+			}
+		default:
+		}
+		return len(got) == 3
+	}, 4*time.Second, 100*time.Millisecond, "Should eventually get candles from the datahandler")
+}
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/okx/okx_test.go]: Concern understood and accepted.

Out of scope for this PR
