### PR TITLE
fix: giant batch for websocket/exchange stability, flake reduction, and direct test coverage

### LINKED ISSUE #567: Postrges test fails consistently
# New Issue

## Context

* Operating System: Linux Mint 20

* GoCryptoTrader version (`gocryptotrader -version`): 
GoCryptoTrader v0.1 amd64 go1.15.1 pre-release.

## Expected Behavior

Running go tests locally pass.
If the target environment is not available for some tests, they should be skipped.

## Current Behavior

tests consistently fail

## Failure Information (for bugs)
`make test` fails

### Steps to Reproduce / Failure Logs

```
gocryptotrader$ go test -v ./database/models/postgres/
Unable to execute setup: parameter validation failed:
        Parameter is an empty string: psql.user
        Parameter is an empty string: psql.host
        Parameter is an empty string: psql.dbname
FAIL    github.com/thrasher-corp/gocryptotrader/database/models/postgres        0.005s
FAIL
```

### LINKED ISSUE #1430: When set kline.interval to OneMonth, AddPaddings error
# New Issue

## Context

When set kline.interval to OneMonth, AddPaddings error

```
ERROR candle open time is not UTC aligned when it should be 2023-12-17 00:00:00 +0000 UTC truncated at a 720h0m0s interval
```

* Operating System:

MacOS M1

* GoCryptoTrader version (`gocryptotrader -version`):

v0.0.0-20231220020127-f05f24da8b92

## Expected Behavior

Not get error, or provide a real OneMonth interval.

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

image

image

### LINKED ISSUE #1704: gateio perpetual contract setleverage
# New Issue
 I tested the perpetual contract of gateio, and the setleverage method was not implemented

### LINKED ISSUE #1708: exchanges/Kraken: Intermittent TestUpdateOrderbook failure
# New Issue

## Context

```
--- FAIL: TestUpdateOrderbook (4.71s)
    kraken_test.go:149: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:149
        	Error:      	Received unexpected error:
        	            	Kraken XBT/USD spot Reason: [orderbook data integrity compromised, rest sync timer lapse with active websocket connection]
        	Test:       	TestUpdateOrderbook
        	Messages:   	UpdateOrderbook spot asset should not error
  ```

Seen: https://github.com/thrasher-corp/gocryptotrader/actions/runs/11735853933/job/32694163351#step:10:537

### LINKED ISSUE #1730: exchanges/websocket: Improve log output
# New Issue

## Context

With multi-conn support, URL is empty:

```
[DEBUG] | EXCHANGE | 26/11/2024 10:58:59 | Set GateIO 'Subscriptions' to ticker, candles, orderbook, spot.balances, spot.cross_balances, spot.margin_balances
[DEBUG] | EXCHANGE | 26/11/2024 10:58:59 | GateIO Websocket: Enabled. (url: )
```

When multiple assets are disabled but one is enabled (e.g just futures enabled), we get this misleading output:

```
[WARN]  | WEBSOCKET | 26/11/2024 10:59:02 | GateIO websocket: no subscriptions generated
```

### LINKED ISSUE #1876: Allow verbosity in websocket testing
I have to hardcode `verbose: true` inside `stream.NewWebsocket()`/`websocket.NewManager()` because the only way to have a verbose websocket is for the exchange to be verbose. When testing a websocket, the normal path testcode follows is using `/testing/exchange/Setup` which overrides any local verbosity settings. If you then manually set the exchange to have verbosity, it is too late, the websocket has been setup and you can't set Verbose to true. This makes me sad. 

With Shazbert and gk actively changing the websocket, I figure I raise an issue rather than implement it and cause untold rebase issues for them. I hope they will sneak such a change in to suit me. Thanks

### LINKED ISSUE #1911: Websocket: Investigate initial connection fault
Observed in the wild on startup when connection has been established but during subscription:
```
2025-05-15 12:33:16 WRN GateIO websocket has been disconnected. Reason: websocket: close 1006 (abnormal closure): unexpected EOF: connection fault subLogger=WEBSOCKET
```

Then:
```
2025-05-15 12:33:16 ERR Error connecting websocket for GateIO: GateIO Error subscribing orderbook spot [CTC_USDT]: GateIO websocket timeout waiting for response with signature 148...
```

State refuses to switch to disconnected via `monitorConnection` routine and reconnection seems to be impossible.

### LINKED ISSUE #1994: Review Poloniex UpdateAccountBalances calculation
CoPilot raised the issue on UpdateAccountBalances that we could be doing more:

> The balance calculation is incomplete. Only Total is set, but Free and Hold amounts should also be calculated from the available balance data to provide complete account information.
```suggestion
		// If bal is a struct with fields Available and OnOrders, use them. Otherwise, set Free = Total, Hold = 0.
		var free, hold, total float64
		switch b := bal.(type) {
		case struct{ Available, OnOrders, BTCValue float64 }:
			free = b.Available
			hold = b.OnOrders
			total = b.Available + b.OnOrders
		case struct{ Available, OnOrders float64 }:
			free = b.Available
			hold = b.OnOrders
			total = b.Available + b.OnOrders
		case float64:
			total = b
			free = b
			hold = 0
		default:
			// fallback: try to use reflection or just set all to bal if possible
			total = 0
			free = 0
			hold = 0
		}
		subAccts[0].Balances.Set(curr, accounts.Balance{
			Total: total,
			Free:  free,
			Hold:  hold,
		})
```

_Originally posted by @Copilot in https://github.com/thrasher-corp/gocryptotrader/pull/1923#discussion_r2260328277_

### LINKED ISSUE #2058: Kraken: TestWsResubscribe test timed out after 10m0s
```
panic: test timed out after 10m0s
	running tests:
		TestWsResubscribe (9m57s)

goroutine 146 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:2682 +0x605
created by time.goFunc
	/opt/hostedtoolcache/go/1.25.1/x64/src/time/sleep.go:215 +0x45

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000082a80, {0x12a3a75, 0x11}, 0x12e86a0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:2005 +0x9fe
testing.runTests.func1(0xc000082a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:2477 +0x86
testing.tRunner(0xc000082a80, 0xc00003da58)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
testing.runTests(0xc000010060, {0x19c2080, 0x67, 0x67}, {0xc00003dbb8?, 0xf1b0f5?, 0x19d5860?})
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:2475 +0x96d
testing.(*M).Run(0xc0002ccc80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:2337 +0xed5
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestMain(0xc0002ccc80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:59 +0x10f
main.main()
	_testmain.go:261 +0x172

goroutine 20 [chan receive, 9 minutes]:
github.com/thrasher-corp/gocryptotrader/log.loggerWorker()
	/home/runner/work/gocryptotrader/gocryptotrader/log/logger_multiwriter.go:35 +0xb0
created by github.com/thrasher-corp/gocryptotrader/log.init.0 in goroutine 1
	/home/runner/work/gocryptotrader/gocryptotrader/log/logger_setup.go:233 +0x28

goroutine 5 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000082e00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateTradablePairs(0xc000082e00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:63 +0x27
testing.tRunner(0xc000082e00, 0x12e8610)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 6 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000083180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetCurrentServerTime(0xc000083180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:68 +0x3c
testing.tRunner(0xc000083180, 0x12e8480)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 7 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000083500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWrapperGetServerTime(0xc000083500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:74 +0x3f
testing.tRunner(0xc000083500, 0x12e8650)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 8 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000083880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateOrderExecutionLimits(0xc000083880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:81 +0x2f
testing.tRunner(0xc000083880, 0x12e85f0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 9 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0002e56c0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFetchTradablePairs(0xc0002e56c0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:102 +0x3c
testing.tRunner(0xc0002e56c0, 0x12e83b0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 10 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0002e5a40)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateTicker(0xc0002e5a40)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:108 +0x3c
testing.tRunner(0xc0002e5a40, 0x12e8600)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 11 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0002e5dc0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateTickers(0xc0002e5dc0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:118 +0x3f
testing.tRunner(0xc0002e5dc0, 0x12e8608)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 12 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000278000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateOrderbook(0xc000278000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:152 +0x3c
testing.tRunner(0xc000278000, 0x12e85f8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 13 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000278380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesBatchOrder(0xc000278380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:160 +0x3f
testing.tRunner(0xc000278380, 0x12e83c8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 14 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000278700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesEditOrder(0xc000278700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:178 +0x3c
testing.tRunner(0xc000278700, 0x12e83e8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 15 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000278a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesSendOrder(0xc000278a80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:186 +0x3f
testing.tRunner(0xc000278a80, 0x12e8420)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 16 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000279180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesCancelOrder(0xc000279180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:194 +0x3f
testing.tRunner(0xc000279180, 0x12e83e0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 34 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000279500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesGetFills(0xc000279500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:202 +0x3c
testing.tRunner(0xc000279500, 0x12e83f0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 35 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000279880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesTransfer(0xc000279880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:210 +0x3c
testing.tRunner(0xc000279880, 0x12e8428)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 36 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000279c00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesGetOpenPositions(0xc000279c00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:218 +0x3c
testing.tRunner(0xc000279c00, 0x12e83f8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 37 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017a000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesNotifications(0xc00017a000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:226 +0x3c
testing.tRunner(0xc00017a000, 0x12e8408)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 38 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017a380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesCancelAllOrders(0xc00017a380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:234 +0x3f
testing.tRunner(0xc00017a380, 0x12e83d0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 39 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017a700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFuturesAccountData(0xc00017a700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:242 +0x3c
testing.tRunner(0xc00017a700, 0x12e84b0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 40 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017aa80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesCancelAllOrdersAfter(0xc00017aa80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:250 +0x3f
testing.tRunner(0xc00017aa80, 0x12e83d8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 41 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017ae00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesOpenOrders(0xc00017ae00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:258 +0x3c
testing.tRunner(0xc00017ae00, 0x12e8410)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 42 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017b180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesRecentOrders(0xc00017b180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:266 +0x3c
testing.tRunner(0xc00017b180, 0x12e8418)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 43 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017b500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesWithdrawToSpotWallet(0xc00017b500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:274 +0x3c
testing.tRunner(0xc00017b500, 0x12e8430)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 44 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017b880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFuturesGetTransfers(0xc00017b880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:282 +0x3c
testing.tRunner(0xc00017b880, 0x12e8400)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 45 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc00017bc00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFuturesOrderbook(0xc00017bc00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:290 +0x3c
testing.tRunner(0xc00017bc00, 0x12e84d0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 46 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001ce000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFuturesMarkets(0xc0001ce000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:296 +0x3c
testing.tRunner(0xc0001ce000, 0x12e84c8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 47 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001ce380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFuturesTickers(0xc0001ce380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:302 +0x3c
testing.tRunner(0xc0001ce380, 0x12e84d8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 48 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001ce700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFuturesTradeHistory(0xc0001ce700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:308 +0x3f
testing.tRunner(0xc0001ce700, 0x12e84e0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 49 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cea80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetAssets(0xc0001cea80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:314 +0x3c
testing.tRunner(0xc0001cea80, 0x12e8450)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 50 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cee00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestSeedAssetTranslator(0xc0001cee00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:320 +0x3f
testing.tRunner(0xc0001cee00, 0x12e85c8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 51 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cf180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestSeedAssets(0xc0001cf180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:332 +0x2f
testing.tRunner(0xc0001cf180, 0x12e85d0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 52 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cf500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestLookupCurrency(0xc0001cf500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:342 +0x2f
testing.tRunner(0xc0001cf500, 0x12e8590)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 53 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cf880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetAssetPairs(0xc0001cf880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:351 +0x3f
testing.tRunner(0xc0001cf880, 0x12e8448)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 54 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001cfc00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTicker(0xc0001cfc00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:359 +0x3c
testing.tRunner(0xc0001cfc00, 0x12e8550)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 55 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e2000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTickers(0xc0001e2000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:365 +0x3c
testing.tRunner(0xc0001e2000, 0x12e8558)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 56 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e2380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetOHLC(0xc0001e2380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:371 +0x3f
testing.tRunner(0xc0001e2380, 0x12e8518)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 57 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e2700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetDepth(0xc0001e2700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:377 +0x3c
testing.tRunner(0xc0001e2700, 0x12e8498)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 58 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e2a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTrades(0xc0001e2a80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:383 +0x3f
testing.tRunner(0xc0001e2a80, 0x12e8570)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 59 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e2e00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetSpread(0xc0001e2e00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:391 +0x3f
testing.tRunner(0xc0001e2e00, 0x12e8548)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 60 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e3180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetBalance(0xc0001e3180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:403 +0x3c
testing.tRunner(0xc0001e3180, 0x12e8458)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 61 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e3500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetDepositMethods(0xc0001e3500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:410 +0x3c
testing.tRunner(0xc0001e3500, 0x12e8490)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 62 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e3880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTradeBalance(0xc0001e3880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:417 +0x3c
testing.tRunner(0xc0001e3880, 0x12e8560)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 63 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e3c00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetOpenOrders(0xc0001e3c00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:425 +0x2f
testing.tRunner(0xc0001e3c00, 0x12e8528)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 64 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e6000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetClosedOrders(0xc0001e6000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:433 +0x3c
testing.tRunner(0xc0001e6000, 0x12e8468)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 65 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e6380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestQueryOrdersInfo(0xc0001e6380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:441 +0x3c
testing.tRunner(0xc0001e6380, 0x12e85b8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 66 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e6700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTradesHistory(0xc0001e6700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:449 +0x3c
testing.tRunner(0xc0001e6700, 0x12e8578)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 67 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e6a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestQueryTrades(0xc0001e6a80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:457 +0x3c
testing.tRunner(0xc0001e6a80, 0x12e85c0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 68 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e6e00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestOpenPositions(0xc0001e6e00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:464 +0x2f
testing.tRunner(0xc0001e6e00, 0x12e85a0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 69 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e7180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetLedgers(0xc0001e7180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:472 +0x3f
testing.tRunner(0xc0001e7180, 0x12e8510)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 70 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e7500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestQueryLedgers(0xc0001e7500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:481 +0x32
testing.tRunner(0xc0001e7500, 0x12e85b0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 71 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e7880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetTradeVolume(0xc0001e7880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:488 +0x3c
testing.tRunner(0xc0001e7880, 0x12e8568)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 72 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e7c00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestOrders(0xc0001e7c00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:496 +0x3f
testing.tRunner(0xc0001e7c00, 0x12e85a8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 73 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e8000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestCancelExistingOrder(0xc0001e8000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:517 +0x3c
testing.tRunner(0xc0001e8000, 0x12e8390)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 74 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e8380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFeeByTypeOfflineTradeFee(0xc0001e8380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:537 +0x3f
testing.tRunner(0xc0001e8380, 0x12e84a8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 75 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e8700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetFee(0xc0001e8700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:551 +0x3f
testing.tRunner(0xc0001e8700, 0x12e84a0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 76 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e8a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestFormatWithdrawPermissions(0xc0001e8a80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:605 +0x2f
testing.tRunner(0xc0001e8a80, 0x12e83c0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 77 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e8e00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetActiveOrders(0xc0001e8e00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:612 +0x3f
testing.tRunner(0xc0001e8e00, 0x12e8440)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 78 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e9180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetOrderHistory(0xc0001e9180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:627 +0x3c
testing.tRunner(0xc0001e9180, 0x12e8530)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 79 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e9500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetOrderInfo(0xc0001e9500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:642 +0x3c
testing.tRunner(0xc0001e9500, 0x12e8538)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 80 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e9880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestSubmitOrder(0xc0001e9880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:652 +0x3f
testing.tRunner(0xc0001e9880, 0x12e85e0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 81 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc0001e9c00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestCancelExchangeOrder(0xc0001e9c00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:675 +0x3c
testing.tRunner(0xc0001e9c00, 0x12e8388)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 82 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000450000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestCancelBatchExchangeOrder(0xc000450000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:699 +0x3f
testing.tRunner(0xc000450000, 0x12e8380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 83 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000450380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestCancelAllExchangeOrders(0xc000450380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:718 +0x3f
testing.tRunner(0xc000450380, 0x12e8378)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 84 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000450700)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestUpdateAccountInfo(0xc000450700)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:734 +0x3c
testing.tRunner(0xc000450700, 0x12e85e8)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 85 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000450a80)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestModifyOrder(0xc000450a80)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:748 +0x3f
testing.tRunner(0xc000450a80, 0x12e8598)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 86 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000450e00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWithdraw(0xc000450e00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:755 +0x3f
testing.tRunner(0xc000450e00, 0x12e8628)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 87 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000451180)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWithdrawFiat(0xc000451180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:780 +0x3f
testing.tRunner(0xc000451180, 0x12e8638)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 88 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000451500)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWithdrawInternationalBank(0xc000451500)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:800 +0x3f
testing.tRunner(0xc000451500, 0x12e8640)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 89 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000451880)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetCryptoDepositAddress(0xc000451880)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:821 +0x3c
testing.tRunner(0xc000451880, 0x12e8470)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 90 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000451c00)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestGetDepositAddress(0xc000451c00)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:838 +0x3c
testing.tRunner(0xc000451c00, 0x12e8488)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 91 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000460000)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWithdrawStatus(0xc000460000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:853 +0x3c
testing.tRunner(0xc000460000, 0x12e8648)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 92 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc000460380)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1708 +0x50c
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWithdrawCancel(0xc000460380)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:868 +0x3c
testing.tRunner(0xc000460380, 0x12e8630)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 107 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f392bbc3e00, 0x72)
	/opt/hostedtoolcache/go/1.25.1/x64/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc000366620, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000366600, {0xc0005df300, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_unix.go:165 +0x453
net.(*netFD).Read(0xc000366600, {0xc0005df300, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/fd_posix.go:68 +0x4b
net.(*conn).Read(0xc00060c038, {0xc0005df300, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/net.go:196 +0xad
crypto/tls.(*atLeastReader).Read(0xc0008da300, {0xc0005df300, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:816 +0x84
bytes.(*Buffer).ReadFrom(0xc0000ad7a8, {0x13fe560, 0xc0008da300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/bytes/buffer.go:217 +0x10f
crypto/tls.(*Conn).readFromUntil(0xc0000ad508, {0x13fe840, 0xc00060c038}, 0x5)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:838 +0x1d6
crypto/tls.(*Conn).readRecordOrCCS(0xc0000ad508, 0x0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:627 +0x346
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0xc0000ad508, {0xc0005da000, 0x1000, 0x0?})
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:1392 +0x2cc
bufio.(*Reader).fill(0xc0008e5da0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/bufio/bufio.go:113 +0x2a4
bufio.(*Reader).ReadSlice(0xc0008e5da0, 0xa)
	/opt/hostedtoolcache/go/1.25.1/x64/src/bufio/bufio.go:380 +0x85
bufio.(*Reader).ReadLine(0xc0008e5da0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/bufio/bufio.go:409 +0x34
net/textproto.(*Reader).readLineSlice(0xc000733040, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/textproto/reader.go:64 +0xda
net/textproto.(*Reader).ReadLine(...)
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/textproto/reader.go:44
net/http.ReadResponse(0xc0008e5da0, 0xc0002c23c0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/http/response.go:161 +0x165
github.com/gorilla/websocket.(*Dialer).DialContext(0xc0007b4a80, {0x1402bd0, 0x19f8300}, {0x12a5a3b, 0x13}, 0xc000797920)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/client.go:372 +0x293a
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*connection).Dial(0xc0009fcbe0, {0x1402bd0, 0x19f8300}, 0xc0007b4a80, 0xc000797920)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/connection.go:146 +0x1d2
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.(*Exchange).WsConnect(0xc0002dac08)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_websocket.go:103 +0x20e
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect(0xc00064a780)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:443 +0x842
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).Connect(0xc00064a780)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:414 +0x96
github.com/thrasher-corp/gocryptotrader/internal/testing/exchange.SetupWs({0x140b6f0, 0xc00079a000}, {0x14133d0, 0xc0002dac08})
	/home/runner/work/gocryptotrader/gocryptotrader/internal/testing/exchange/exchange.go:203 +0x305
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.TestWsResubscribe(0xc00079a000)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_test.go:986 +0xe5
testing.tRunner(0xc00079a000, 0x12e86a0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.1/x64/src/testing/testing.go:1997 +0x9d3

goroutine 98 [select, 9 minutes]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).observeData(0xc00064a960, 0xc00088e1e8)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:920 +0x105
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorData-fm.(*Manager).monitorData.func1()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:915 +0x39
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorFrame(0xc00064a960, 0xc00064aa58, 0xc0000380a0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:906 +0xbd
created by github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect in goroutine 93
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:436 +0x50b

goroutine 99 [select]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).observeTraffic(0xc00064a960, 0xc0000e29a0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:1005 +0xe9
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorTraffic.func1()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:1001 +0x39
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorFrame(0xc00064a960, 0xc00064aa58, 0xc0000380b0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:906 +0xbd
created by github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect in goroutine 93
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:437 +0x693

goroutine 94 [select, 9 minutes]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).observeData(0xc00064a780, 0xc0009ce028)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:920 +0x105
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorData-fm.(*Manager).monitorData.func1()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:915 +0x39
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorFrame(0xc00064a780, 0xc00064a878, 0xc000648180)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:906 +0xbd
created by github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect in goroutine 107
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:436 +0x50b

goroutine 95 [select]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).observeTraffic(0xc00064a780, 0xc0002ee070)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:1005 +0xe9
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorTraffic.func1()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:1001 +0x39
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorFrame(0xc00064a780, 0xc00064a878, 0xc000648190)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:906 +0xbd
created by github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect in goroutine 107
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:437 +0x693

goroutine 28 [select]:
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.(*Exchange).wsReadData(0xc0002da908, {0x1402bd0, 0x19f8300}, 0xc00063d7a0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_websocket.go:153 +0x226
created by github.com/thrasher-corp/gocryptotrader/exchanges/kraken.(*Exchange).WsConnect in goroutine 93
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_websocket.go:110 +0x36f

goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x7f392bbc3c00, 0x72)
	/opt/hostedtoolcache/go/1.25.1/x64/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc0007b45a0, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0007b4580, {0xc000140c00, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/internal/poll/fd_unix.go:165 +0x453
net.(*netFD).Read(0xc0007b4580, {0xc000140c00, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/fd_posix.go:68 +0x4b
net.(*conn).Read(0xc00033b910, {0xc000140c00, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/net/net.go:196 +0xad
crypto/tls.(*atLeastReader).Read(0xc0008da5b8, {0xc000140c00, 0x1300, 0x1300})
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:816 +0x84
bytes.(*Buffer).ReadFrom(0xc0000ac628, {0x13fe560, 0xc0008da5b8})
	/opt/hostedtoolcache/go/1.25.1/x64/src/bytes/buffer.go:217 +0x10f
crypto/tls.(*Conn).readFromUntil(0xc0000ac388, {0x13fe840, 0xc00033b910}, 0x5)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:838 +0x1d6
crypto/tls.(*Conn).readRecordOrCCS(0xc0000ac388, 0x0)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:627 +0x346
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:589
crypto/tls.(*Conn).Read(0xc0000ac388, {0xc000129000, 0x1000, 0x0?})
	/opt/hostedtoolcache/go/1.25.1/x64/src/crypto/tls/conn.go:1392 +0x2cc
bufio.(*Reader).fill(0xc0008e4660)
	/opt/hostedtoolcache/go/1.25.1/x64/src/bufio/bufio.go:113 +0x2a4
bufio.(*Reader).Peek(0xc0008e4660, 0x2)
	/opt/hostedtoolcache/go/1.25.1/x64/src/bufio/bufio.go:152 +0xc5
github.com/gorilla/websocket.(*Conn).read(0xc00093a840, 0x2)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:371 +0x53
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc00093a840)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:809 +0x11b
github.com/gorilla/websocket.(*Conn).NextReader(0xc00093a840)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:1009 +0x134
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00093a840)
	/home/runner/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:1093 +0x2f
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*connection).ReadMessage(0xc00020cd20)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/connection.go:270 +0x5f
github.com/thrasher-corp/gocryptotrader/exchanges/kraken.(*Exchange).wsFunnelConnectionData(0xc0002da908, {0x14090c8, 0xc00020cd20}, 0xc00063d7a0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_websocket.go:140 +0x1c6
created by github.com/thrasher-corp/gocryptotrader/exchanges/kraken.(*Exchange).WsConnect in goroutine 93
	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/kraken/kraken_websocket.go:111 +0x4dd

goroutine 30 [select]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*connection).SetupPingHandler.func2()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/connection.go:239 +0x10a
sync.(*WaitGroup).Go.func1()
	/opt/hostedtoolcache/go/1.25.1/x64/src/sync/waitgroup.go:239 +0x5e
created by sync.(*WaitGroup).Go in goroutine 93
	/opt/hostedtoolcache/go/1.25.1/x64/src/sync/waitgroup.go:237 +0x87

goroutine 31 [select]:
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).observeConnection(0xc00064a960, 0xc0002e20e0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:949 +0x10b
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorConnection.func1()
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:944 +0x39
github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).monitorFrame(0xc00064a960, 0x0, 0xc0006c61f0)
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:906 +0xbd
created by github.com/thrasher-corp/gocryptotrader/exchange/websocket.(*Manager).connect in goroutine 93
	/home/runner/work/gocryptotrader/gocryptotrader/exchange/websocket/manager.go:452 +0xb13
FAIL	github.com/thrasher-corp/gocryptotrader/exchanges/kraken	600.236s
```

### LINKED ISSUE #2146: websocket/manager: Exported subscription functions require mutex protection
Problems with these funcs specifically but may be more:

* UnsubscribeChannels
* SubscribeToChannels
* RemoveSubscriptions
* AddSuccessfulSubscriptions
* AddSubscriptions
* FlushSubscriptions

See conversation: https://github.com/thrasher-corp/gocryptotrader/pull/2109#discussion_r2633174745

Some ideas for mitigation:

* RWMutex for websocket and connections list @gloriousCode has some ideas. 
* Or redesign how we handle connection Adding and removing subscriptions wrapper side shift that to manager if possible.

### LINKED ISSUE #2198: kucoin: intermittent rounding issue when fetching orderbook
There is a potential intermittent rounding issue with kucoin orderbooks when fetching the full book for websocket usage.

```
["999999999999999999","0.00001405"],["999999999999999999.9","0.00064"]
{Amount:0.00064 StrAmount: Price:1e+18 StrPrice: ID:0 Period:0 LiquidationOrders:0 OrderCount:0} {Amount:1.405e-05 StrAmount: Price:1e+18 StrPrice: ID:0 Period:0 LiquidationOrders:0 OrderCount:0}
panic: cannot load book for exchange Kucoin pair BTC-USDT asset spot for Asks: price duplication
```

This can be addressed in another PR.

_Originally posted by @shazbert in https://github.com/thrasher-corp/gocryptotrader/issues/2123#issuecomment-4000999656_

### PR DESCRIPTION
**Pull request by thrasher-**
## Summary

This PR batches targeted fixes across websocket lifecycle/concurrency, exchange wrappers, and test stability.
It also adds direct tests for newly modified helper logic and flaky paths.

## Issues addressed

- #1994 — Poloniex account balance mapping/handling fixes + tests
- #1704 — GateIO perpetual/futures `SetLeverage` support + validation tests
- #1730 — websocket manager logging improvements
- #1876 — websocket test verbosity improvements (`testexch` helper support + tests)
- #2198 — Kucoin rounded orderbook merge hardening + tests
- #1911 — websocket manager connection lifecycle hardening
- #1430 — kline OneMonth/add-padding alignment fixes + direct month-interval tests
- #2146 — websocket exported subscription-path mutex/locking hardening + race-focused tests
- #1708 — Kraken flaky test stability improvements (isolated exchange names, reduced shared-state bleed)
- Related stability work around #2058 (Kraken websocket test robustness)

## Additional fixes included

- Bybit options: filter non-`Trading` instruments in limits-loading path to reduce “unable to load limit” noise; added direct tests
- Postgres ORM test handling: skip cleanly when required `psql.*` config is missing; TODO/link aligned to #1818 
- GateIO websocket resubscribe test stabilisation for CI timing variance
- Adopted shared auth websocket precheck helper in touched exchange auth WS tests: `testexch.SkipTestIfCannotUseAuthenticatedWebsocket(t, e)`

## Validation

Targeted local runs completed for touched areas, including repeated and race-sensitive websocket/exchange tests where applicable (kraken, gateio, kucoin, bybit, kline, websocket manager/subscriptions), plus CI workflow reruns on branch updates.

## Linked issues

Closes #1994
Closes #1704
Closes #1730
Closes #1876
Closes #2198
Closes #1911
Closes #1430
Closes #2146
Closes #1708
Closes #2058
Closes #567

### CODE REVIEW

File: database/models/postgres/boil_main_test.go [hunk 1]
```diff
@@ -52,6 +68,13 @@ func TestMain(m *testing.M) {
 		os.Exit(-2)
 	}
 
+	missingPSQLConfig := missingPSQLConfigKeys()
+	if len(missingPSQLConfig) != 0 {
+		// TODO(#1818): Replace this hard exit skip once sqlboiler-generated postgres tests support explicit runtime skip handling.
+		fmt.Printf("Skipping postgres ORM tests due to missing config: %s (see https://github.com/thrasher-corp/gocryptotrader/issues/1818)\n", strings.Join(missingPSQLConfig, ", "))
+		os.Exit(0)
+	}
```
[the remark this answers is not in the document]
Comment (thrasher-) [reply database/models/postgres/boil_main_test.go:76]: Jarvis: Yep, intentional. This file is generated (`DO NOT EDIT`), and this is a small temporary hack until the ORM/SQLBoiler upgrade in #1818 is done.

File: exchange/websocket/manager.go [hunk 2]
```diff
@@ -479,64 +512,65 @@ func (m *Manager) connect(ctx context.Context) error {
 	var subscriptionError error
 
 	// TODO: Implement concurrency below.
-	for i := range m.connectionManager {
+	for i := range connectionManager {
```
Comment (shazbert) [inline exchange/websocket/manager.go]:
```suggestion
	for i, ws := range connectionManager {
```

Then remove the ws var below

File: exchange/websocket/manager.go [hunk 3]
```diff
@@ -840,6 +878,42 @@ func (m *Manager) GetWebsocketURL() string {
 	return m.runningURL
 }
 
+// GetConfiguredWebsocketURLs returns known websocket connection URLs.
+func (m *Manager) GetConfiguredWebsocketURLs() []string {
+	if err := common.NilGuard(m); err != nil {
```
Comment (shazbert) [inline exchange/websocket/manager.go:890]: If you are not using the error can just use ==

Can also add in an error for the return as an option.

File: exchange/websocket/subscriptions.go [hunk 4]
```diff
@@ -64,6 +64,40 @@ func (m *Manager) unsubscribe(store *subscription.Store, channels subscription.L
 	return unsub(channels)
 }
 
+func (m *Manager) managedWebsocket(conn Connection) (*websocket, bool) {
```
Comment (shazbert) [inline exchange/websocket/subscriptions.go:67]: suggestion: prefer error return instead of a bool because then if there is a nil conn or no association it can error out nicely.

File: exchange/websocket/subscriptions.go [hunk 5]
```diff
@@ -64,6 +64,40 @@ func (m *Manager) unsubscribe(store *subscription.Store, channels subscription.L
...
+	if conn == nil {
+		return nil, false
+	}
+	m.subscriptionsMu.RLock()
+	defer m.subscriptionsMu.RUnlock()
+	ws, ok := m.connections[conn]
+	return ws, ok
+}
+
+func (m *Manager) subscriptionStore(conn Connection) *subscription.Store {
```
Comment (shazbert) [inline exchange/websocket/subscriptions.go:77]: suggestion: In the functions here and below we should pivot using the `useMultiConnectionManagement` bool and return an error if not found.

File: exchange/websocket/subscriptions.go [hunk 6]
```diff
@@ -197,19 +206,22 @@ func (m *Manager) GetSubscription(key any) *subscription.Subscription {
 	if m == nil || key == nil {
 		return nil
 	}
-	for _, c := range m.connectionManager {
-		if c.subscriptions == nil {
+	for _, ws := range m.snapshotConnectionManager() {
+		m.subscriptionsMu.RLock()
+		store := ws.subscriptions
+		m.subscriptionsMu.RUnlock()
```
Comment (shazbert) [inline exchange/websocket/subscriptions.go]: This seems to release too early because it just shares a pointer, might be better to unlock on continue


```go
		m.subscriptionsMu.RLock()
		store := ws.subscriptions
		var sub *subscription.Subscription
		if store != nil {
			sub = store.Get(key)
		}
		m.subscriptionsMu.RUnlock()
		if sub != nil {
			return sub
		}
```

File: exchange/websocket/manager.go (hunk 2 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Addressed in https://github.com/thrasher-/gocryptotrader/commit/06d1dd9df1d2b2cac28996b46d874268674fbae2 — switched to the suggested range form (`for i, ws := range connectionManager`) and removed the redundant local assignment.

File: exchange/websocket/manager.go (hunk 3 above)
Comment (thrasher-) [reply exchange/websocket/manager.go:890]: Jarvis: Addressed across https://github.com/thrasher-/gocryptotrader/commit/06d1dd9df1d2b2cac28996b46d874268674fbae2 and https://github.com/thrasher-/gocryptotrader/commit/f2abfd39a799e790c65fdab8e838935f1b6a8daa — replaced NilGuard with direct `m == nil` check, and updated `GetConfiguredWebsocketURLs` to return `([]string, error)` so nil-manager returns an explicit error.

File: exchange/websocket/subscriptions.go (hunk 6 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go]: Jarvis: Addressed in https://github.com/thrasher-/gocryptotrader/commit/06d1dd9df1d2b2cac28996b46d874268674fbae2 — RLock now stays held through store access (`Get`/`List`) before unlock, and the same lifetime fix was applied in both `GetSubscription` and `GetSubscriptions`.

File: exchange/websocket/subscriptions.go (hunk 4 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go:67]: Jarvis: Good suggestion. For this PR I’ve kept the internal `(value, bool)` lookup shape because it matches Go’s map-lookup idiom and existing callsites already convert the `!ok` case into contextual errors where needed (for example connection-not-found paths). I’d prefer to keep this scoped here and do a dedicated pass if we want to standardise all helper lookups on error-return semantics.

File: exchange/websocket/subscriptions.go (hunk 5 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go:77]: Jarvis: Agreed this could be made more explicit. Current behaviour already routes by connection presence and falls back to manager-level storage when connection-scoped state is unavailable, so it’s functionally correct in both single- and multi-connection modes. I’ve kept that behaviour in this PR to avoid widening scope, but I’m happy to follow up with a dedicated refactor that pivots these helpers on `useMultiConnectionManagement` + explicit not-found errors.

File: exchange/websocket/manager.go [hunk 7]
```diff
@@ -879,9 +878,9 @@ func (m *Manager) GetWebsocketURL() string {
 }
 
 // GetConfiguredWebsocketURLs returns known websocket connection URLs.
-func (m *Manager) GetConfiguredWebsocketURLs() []string {
-	if err := common.NilGuard(m); err != nil {
-		return nil
+func (m *Manager) GetConfiguredWebsocketURLs() ([]string, error) {
+	if m == nil {
```
Comment (shazbert) [inline exchange/websocket/manager.go]: If you were going to return the error than you can use nilguard I suppose

File: exchanges/exchange.go [hunk 8]
```diff
@@ -1801,7 +1801,10 @@ func Bootstrap(ctx context.Context, b IBotExchange) error {
 			if w, err := b.GetWebsocket(); err == nil {
 				wsURL = w.GetWebsocketURL()
 				if wsURL == "" {
-					wsURL = strings.Join(w.GetConfiguredWebsocketURLs(), ",")
+					urls, getErr := w.GetConfiguredWebsocketURLs()
```
Comment (shazbert) [inline exchanges/exchange.go:1804]: Should return this error

File: exchange/websocket/subscriptions.go [hunk 9]
```diff
@@ -413,18 +432,41 @@ func (m *Manager) scaleConnectionsToSubscriptions(ctx context.Context, ws *webso
 	}
 
 	// Clean up any connections that have no subscriptions left to reduce resource usage
-	clean := make([]Connection, 0, len(ws.connections))
-	for _, conn := range ws.connections {
+	connections := m.snapshotManagedConnections(ws)
```
Comment (shazbert) [inline exchange/websocket/subscriptions.go:435]: This looks way over complicated than it needs to be, why not lock it out before here and just drop the stale connections, Just filter in place on ws.Connections and have one stale var slice which you can Shutdown on?

File: exchanges/bybit/bybit_options_limits_test.go [hunk 10]
```diff
@@ -0,0 +1,224 @@
...
+	assert.Equal(t, cSpot, queries[0].Get("category"), "UpdateOrderExecutionLimits should request the spot category")
+	assert.Empty(t, queries[0].Get("status"), "UpdateOrderExecutionLimits should not filter non-options instrument status")
+	assert.Equal(t, "1000", queries[0].Get("limit"), "UpdateOrderExecutionLimits should request the expected page size")
+}
+
+func newOptionsInstrumentInfoTestExchange(t *testing.T, name string, responses map[string][]optionInstrumentInfoResponse, queries *[]url.Values) *Exchange {
+	t.Helper()
+
+	return newInstrumentInfoTestExchange(t, name, cOption, responses, queries)
+}
```
Comment (shazbert) [inline exchanges/bybit/bybit_options_limits_test.go]: This func seems superfluous and can be removed.

File: exchanges/kline/kline.go [hunk 11]
```diff
@@ -133,6 +137,79 @@ func (i Interval) Duration() time.Duration {
...
+
+func nextIntervalStart(t time.Time, interval Interval) time.Time {
+	months := calendarIntervalMonths(interval)
+	if months == 0 {
+		return t.UTC().Round(0).Add(interval.Duration())
+	}
+	return alignIntervalStart(t, interval).AddDate(0, months, 0)
+}
+
+func intervalCount(start, end time.Time, interval Interval) uint64 {
```
Comment (shazbert) [inline exchanges/kline/kline.go:181]: Need to return error here. As there is potentially cooked incoming parameters.

File: exchanges/kucoin/kucoin_test.go [hunk 12]
```diff
@@ -2086,6 +2086,66 @@ func TestUpdateOrderbook(t *testing.T) {
...
+			name: "single",
+			levels: []orderbook.Level{
+				{Price: 9.99, Amount: 1},
+			},
+			exp: []orderbook.Level{
+				{Price: 9.99, Amount: 1},
+			},
+		},
+		{
+			name: "adjacentduplicatesmerge",
```
Comment (shazbert) [inline exchanges/kucoin/kucoin_test.go]: camel case name or spread them out

File: exchanges/kucoin/kucoin_wrapper.go [hunk 13]
```diff
@@ -390,6 +392,27 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, a asset
 	return orderbook.Get(e.Name, p, a)
 }
 
+func mergeRoundedOrderbookLevels(levels []orderbook.Level) []orderbook.Level {
```
Comment (shazbert) [inline exchanges/kucoin/kucoin_wrapper.go:398]: please commentary as to why this is used

File: exchanges/kucoin/kucoin_wrapper.go [hunk 14]
```diff
@@ -390,6 +392,27 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, a asset
...
+	if len(levels) < 2 {
+		return levels
+	}
```
Comment (shazbert) [inline exchanges/kucoin/kucoin_wrapper.go:401]: This optimisation is unrealistic and just adds in an extra check in a real running scenario.

File: exchanges/kucoin/kucoin_wrapper.go [hunk 15]
```diff
@@ -390,6 +392,27 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, a asset
...
+
+	merged := make([]orderbook.Level, 0, len(levels))
```
Comment (shazbert) [inline exchanges/kucoin/kucoin_wrapper.go]: why allocate when we can just filter in place and just merge on the existing?

File: exchange/websocket/manager.go (hunk 7 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Done in https://github.com/thrasher-/gocryptotrader/commit/6a295e2fa08680c52ebd745e7ec14773a7d158ab — switched this to common.NilGuard(m) so it follows the standard nil-pointer error path for the new ([]string, error) signature.

File: exchanges/exchange.go (hunk 8 above)
Comment (thrasher-) [reply exchanges/exchange.go:1804]: Jarvis: Keeping this non-fatal. This branch is only assembling verbose websocket URL output during bootstrap; returning getErr here would risk failing startup over diagnostic logging.

File: exchange/websocket/subscriptions.go (hunk 9 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go:435]: Jarvis: I left this block as-is for now. The two-phase snapshot/update flow is deliberate to avoid broadening the locking change in this PR, and I didn’t see a tiny safe simplification here worth extra churn.

File: exchanges/kline/kline.go (hunk 11 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:181]: Jarvis: I kept the current shape here. intervalCount is an internal helper and callers already validate inputs/use 0 as the invalid sentinel, so widening it to return errors would ripple more code than it buys.

File: exchanges/kucoin/kucoin_wrapper.go (hunk 13 above)
Comment (thrasher-) [reply exchanges/kucoin/kucoin_wrapper.go:398]: Jarvis: Done in https://github.com/thrasher-/gocryptotrader/commit/6a295e2fa08680c52ebd745e7ec14773a7d158ab — added a short why-comment above mergeRoundedOrderbookLevels explaining that KuCoin rounded books can emit adjacent duplicate-price levels before we load the local book.

File: exchanges/kucoin/kucoin_wrapper.go (hunk 15 above)
Comment (thrasher-) [reply exchanges/kucoin/kucoin_wrapper.go]: Jarvis: Done in https://github.com/thrasher-/gocryptotrader/commit/6a295e2fa08680c52ebd745e7ec14773a7d158ab — refactored mergeRoundedOrderbookLevels to merge/filter in place with a write index, removing the extra allocation while preserving behaviour.

**Comment by thrasher-** [comment]
Jarvis: Also fixed an additional GateIO test issue affecting both `master` and this branch. `TestFetchOrderbook` was assuming a margin-only pair existed, but GateIO currently returns an empty margin-minus-spot diff there. I kept live margin coverage by switching the happy-path test to a real available margin pair and moved the `errNoSpotInstrument` coverage into a deterministic synthetic test. Commit: https://github.com/thrasher-/gocryptotrader/commit/12d0f939966fe228d578656e02814e212bf832e7 Validation: `go test ./exchanges/gateio -run "TestFetchOrderbook$|TestFetchOrderbookNoSpotInstrument$|TestUpdateTradablePairs$|TestUpdateTicker$" -count=1 -v`, `go test ./exchanges/gateio -count=1`, `golangci-lint run ./exchanges/gateio`.

File: exchanges/kucoin/kucoin_test.go (hunk 12 above)
Comment (thrasher-) [reply exchanges/kucoin/kucoin_test.go]: Jarvis: Done in https://github.com/thrasher-/gocryptotrader/commit/ed369a7ce275fd8c1721850ffbf3e026f8875f66 — renamed the KuCoin table-test cases to camelCase for readability.

File: exchanges/bybit/bybit_options_limits_test.go (hunk 10 above)
Comment (thrasher-) [reply exchanges/bybit/bybit_options_limits_test.go]: Jarvis: Done in https://github.com/thrasher-/gocryptotrader/commit/ed369a7ce275fd8c1721850ffbf3e026f8875f66 — inlined cOption at the two callsites and removed the tiny wrapper helper.

File: exchanges/kucoin/kucoin_wrapper.go (hunk 14 above)
Comment (thrasher-) [reply exchanges/kucoin/kucoin_wrapper.go:401]: Jarvis: Keeping this as-is. The merge helper now normalises duplicate-price levels across both KuCoin REST and websocket orderbook ingestion paths, and the overhead here is just the early len guard plus a single pass over the already-fetched levels. I’d rather keep those paths consistent than special-case only this one.

Comment (shazbert) [reply exchanges/kucoin/kucoin_wrapper.go:401]: That makes sense now, I was being a silly billy.

**Comment by thrasher-** [comment]
@codex please review

**Comment by thrasher-** [comment]
Jarvis: Follow-up in https://github.com/thrasher-/gocryptotrader/commit/24e5338213e2f19542b0f1eadd86f4414b6fe607 — the OKX live copytrading tests were assuming the top-ranked public lead trader would also work for the current/history subposition endpoints, but OKX is currently returning some ranked traders that still work for stats/pnl endpoints while returning 60004 "Trader doesn't exist" for subpositions. I split the helper so the general public lead-trader tests keep using the ranked lookup, while the two subposition tests now probe ranked candidates until they find one with working subposition endpoints and skip with a clear reason if OKX exposes none.

File: exchange/websocket/manager.go [hunk 16]
```diff
@@ -405,6 +412,31 @@ func (m *Manager) createConnectionFromSetup(c *ConnectionSetup) *connection {
...
+}
+
+func (m *Manager) trackConnection(conn Connection, ws *websocket) {
+	m.subscriptionsMu.Lock()
+	defer m.subscriptionsMu.Unlock()
+	if m.connections == nil {
+		m.connections = make(map[Connection]*websocket)
+	}
+	m.connections[conn] = ws
+	ws.connections = append(ws.connections, conn)
```
Comment (gloriousCode) [inline exchange/websocket/manager.go]: I think this function needs to be a bit smarter. If this is called twice, it will add a single key to the map, but append 2 connections.
I think an error return would help with an `ok` check for the map

Then add a unit test to this function. The two above are just slice clones

File: exchange/websocket/manager.go [hunk 17]
```diff
@@ -840,6 +877,42 @@ func (m *Manager) GetWebsocketURL() string {
...
+	if err := common.NilGuard(m); err != nil {
+		return nil, err
+	}
+
+	m.m.Lock()
+	defer m.m.Unlock()
+
+	if m.useMultiConnectionManagement {
+		m.subscriptionsMu.RLock()
+		defer m.subscriptionsMu.RUnlock()
```
Comment (gloriousCode) [inline exchange/websocket/manager.go]: Why is this needed here? Perhaps a rename for this mutex since it does nothing with subscriptions here

File: exchange/websocket/manager.go [hunk 18]
```diff
@@ -858,11 +931,13 @@ func (m *Manager) SetProxyAddress(ctx context.Context, proxyAddr string) error {
 		log.Debugf(log.ExchangeSys, "%s websocket: removing websocket proxy", m.exchangeName)
 	}
 
+	m.subscriptionsMu.RLock()
```
Comment (gloriousCode) [inline exchange/websocket/manager.go]: Why is this needed here?  Perhaps a rename for this mutex since it does nothing with subscriptions here

File: exchange/websocket/manager.go [hunk 19]
```diff
@@ -1077,6 +1154,8 @@ func (m *Manager) GetConnection(messageFilter any) (Connection, error) {
 		return nil, ErrNotConnected
 	}
 
+	m.subscriptionsMu.RLock()
```
Comment (gloriousCode) [inline exchange/websocket/manager.go]: Why is this needed here?  Perhaps a rename for this mutex since it does nothing with subscriptions here

File: exchange/websocket/manager_test.go [hunk 20]
```diff
@@ -30,15 +30,84 @@ import (
...
+}
+
+// resetManagerForNextConnectAttempt waits for monitor goroutines to drain during test cleanup.
+// It intentionally avoids mutating ShutdownC directly.
+func resetManagerForNextConnectAttempt(t *testing.T, ws *Manager) {
+	t.Helper()
+	if ws == nil {
+		return
+	}
+	waitDone := make(chan struct{})
```
Comment (gloriousCode) [inline exchange/websocket/manager_test.go:74]: require.Eventually

File: exchange/websocket/subscriptions.go [hunk 21]
```diff
@@ -64,6 +64,40 @@ func (m *Manager) unsubscribe(store *subscription.Store, channels subscription.L
...
+func (m *Manager) subscriptionStore(conn Connection) *subscription.Store {
+	m.subscriptionsMu.RLock()
+	defer m.subscriptionsMu.RUnlock()
+	if ws, ok := m.connections[conn]; ok && conn != nil {
+		return ws.subscriptions
+	}
+	return m.subscriptions
+}
+
+func (m *Manager) initSubscriptionStore(conn Connection) *subscription.Store {
```
Comment (gloriousCode) [inline exchange/websocket/subscriptions.go:86]: Add test for this function

File: exchange/websocket/subscriptions.go [hunk 22]
```diff
@@ -64,6 +64,40 @@ func (m *Manager) unsubscribe(store *subscription.Store, channels subscription.L
...
 }
 
+func (m *Manager) managedWebsocket(conn Connection) (*websocket, bool) {
+	if conn == nil {
+		return nil, false
+	}
+	m.subscriptionsMu.RLock()
+	defer m.subscriptionsMu.RUnlock()
+	ws, ok := m.connections[conn]
+	return ws, ok
```
Comment (gloriousCode) [inline exchange/websocket/subscriptions.go]:
```suggestion
	return m.connections[conn]
```

File: exchange/websocket/subscriptions.go (hunk 5 above)
Comment (gloriousCode) [reply exchange/websocket/subscriptions.go:77]: Yes this function will need another look. If I send in a conn and get an unrelated m.subscriptions in return, its not the best.
I suppose its all preexisting to this PR anyway

File: exchanges/bybit/bybit_options_limits_test.go [hunk 23]
```diff
@@ -0,0 +1,218 @@
...
+	}))
+	t.Cleanup(server.Close)
+
+	require.NoError(t, ex.SetHTTPClient(server.Client()), "SetHTTPClient must not error")
+	require.NoError(t, ex.API.Endpoints.SetRunningURL(exchange.RestSpot.String(), server.URL), "SetRunningURL must not error")
+
+	return ex
+}
+
+type optionInstrumentInfoResponse struct {
```
Comment (gloriousCode) [inline exchanges/bybit/bybit_options_limits_test.go]: Do we really need to introduce this instead of just reusing `InstrumentInfo`? Adds burden if the struct changes

File: exchanges/gateio/ws_ob_resub_manager_test.go [hunk 24]
```diff
@@ -80,7 +80,14 @@ func TestResubscribe(t *testing.T) {
 	require.NoError(t, err)
 	err = m.Resubscribe(t.Context(), e, conn, "ob.BTC_USDT.50", currency.NewBTCUSDT(), asset.Spot)
 	require.NoError(t, err)
-	assert.True(t, m.IsResubscribing(currency.NewBTCUSDT(), asset.Spot))
+	assert.Eventually(t,
```
Comment (gloriousCode) [inline exchanges/gateio/ws_ob_resub_manager_test.go:99]:
```suggestion
	assert.True(t, m.IsResubscribing(currency.NewBTCUSDT(), asset.Spot))
	assert.Eventually(t,
```
Since you're looking to see if it both does resubscribe and change state to it no longer subscribing.
Maybe even two assert.Eventually

File: exchanges/kline/kline.go [hunk 25]
```diff
@@ -133,6 +137,79 @@ func (i Interval) Duration() time.Duration {
...
+	case OneYear:
+		return 12
+	default:
+		return 0
+	}
+}
+
+// alignIntervalStart keeps calendar-based intervals pinned to real UTC month
+// boundaries instead of Unix epoch duration buckets.
+func alignIntervalStart(t time.Time, interval Interval) time.Time {
```
Comment (gloriousCode) [inline exchanges/kline/kline.go:159]: Add test. While we test for coverage, its important to have individual functions tested to ensure that the logic that we design for is actually what is returned. If this function, or calling functions or the test design changes where its not testing this function specifically, we need to ensure that the function meets our expectations

File: exchanges/kline/kline.go [hunk 26]
```diff
@@ -133,6 +137,79 @@ func (i Interval) Duration() time.Duration {
...
+	}
+
+	year, month, _ := t.Date()
+	monthIndex := int(month) - 1
+	monthIndex -= monthIndex % months
+
+	return time.Date(year, time.Month(monthIndex+1), 1, 0, 0, 0, 0, time.UTC)
+}
+
+func nextIntervalStart(t time.Time, interval Interval) time.Time {
```
Comment (gloriousCode) [inline exchanges/kline/kline.go:173]: Add test

File: exchanges/kline/kline.go (hunk 11 above)
Comment (gloriousCode) [inline exchanges/kline/kline.go:181]: Add test

File: exchanges/kline/kline.go [hunk 27]
```diff
@@ -133,6 +137,79 @@ func (i Interval) Duration() time.Duration {
...
+	}
+
+	var count uint64
+	for current := start; current.Before(end); current = nextIntervalStart(current, interval) {
+		count++
+	}
+	return count
+}
+
+func intervalCountAsInt(start, end time.Time, interval Interval) (int, error) {
```
Comment (gloriousCode) [inline exchanges/kline/kline.go:205]: Add test

File: exchanges/kline/kline.go [hunk 28]
```diff
@@ -133,6 +137,79 @@ func (i Interval) Duration() time.Duration {
...
+	count := intervalCount(start, end, interval)
+	if count > uint64(^uint(0)>>1) {
+		return 0, fmt.Errorf("interval count exceeds max int: %d", count)
```
Comment (gloriousCode) [inline exchanges/kline/kline.go:208]: Use var errors, then use in the test

File: exchanges/kucoin/kucoin_wrapper.go [hunk 29]
```diff
@@ -390,6 +392,26 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, a asset
 	return orderbook.Get(e.Name, p, a)
 }
 
+// KuCoin's rounded books can emit adjacent levels that collapse to the same
```
Comment (gloriousCode) [inline exchanges/kucoin/kucoin_wrapper.go]:
```suggestion
// KuCoin's rounded books can emit adjacent levels that can be collapsed to the same
```
Otherwise, this function isn't necessary since it would already be collapsed

File: exchanges/okx/okx_test.go [hunk 30]
```diff
@@ -109,6 +112,53 @@ func syncLeadTraderUniqueID(t *testing.T) error {
...
+
+	loadLeadTraderSubPositionsOnce.Do(func() {
+		result, err := e.GetLeadTradersRanks(contextGenerate(), &LeadTraderRanksRequest{
+			InstrumentType: instTypeSwap,
+			SortType:       "pnl_ratio",
+			HasVacancy:     true,
+			Limit:          10,
+		})
+		if err != nil {
+			errSyncLeadTraderSubPositions = fmt.Errorf("GetLeadTradersRanks failed: %s", err)
```
Comment (gloriousCode) [inline exchanges/okx/okx_test.go]: Why use %s and lose the error? Use %w

File: exchange/websocket/manager.go (hunk 16 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Fixed in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557. `trackConnection` is now idempotent for an existing `Connection` key, so we no longer append the same connection twice while only keeping one map entry. I also added direct coverage for duplicate registration in `TestTrackConnection`.

File: exchange/websocket/manager_test.go (hunk 20 above)
Comment (thrasher-) [reply exchange/websocket/manager_test.go:74]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 — the timing-sensitive assertion now uses `require.Eventually` so the test waits for the async state change instead of assuming it has already happened.

File: exchange/websocket/subscriptions.go (hunk 21 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go:86]: Jarvis: Added direct coverage in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557. `TestInitSubscriptionStore` now covers the managed, unmanaged, and nil-connection cases around the store-init behaviour introduced here.

File: exchanges/gateio/ws_ob_resub_manager_test.go (hunk 24 above)
Comment (thrasher-) [reply exchanges/gateio/ws_ob_resub_manager_test.go:99]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 — this now uses eventual state assertions so the test checks the resubscribe transition/completion without depending on immediate scheduler timing.

File: exchanges/kline/kline.go (hunk 25 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:159]: Jarvis: Added direct helper coverage in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 via `TestAlignIntervalStart`.

File: exchanges/kline/kline.go (hunk 26 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:173]: Jarvis: Added direct helper coverage in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 via `TestNextIntervalStart`.

File: exchanges/kline/kline.go (hunk 11 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:181]: Jarvis: Added direct helper coverage in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 via `TestIntervalCount`.

File: exchanges/kline/kline.go (hunk 27 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:205]: Jarvis: Added direct helper coverage in https://github.com/thrasher-/gocryptotrader/commit/af6638c1763b90470eb60f7b9aee1b47ed036557 via `TestIntervalCountAsInt`.

File: exchanges/bybit/bybit_options_limits_test.go (hunk 23 above)
Comment (thrasher-) [reply exchanges/bybit/bybit_options_limits_test.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/57d0891e. I switched the fixture over to `InstrumentInfo`-backed responses instead of keeping a bespoke response shape in the test, so it stays aligned if `InstrumentInfo` changes.

File: exchanges/kline/kline.go (hunk 28 above)
Comment (thrasher-) [reply exchanges/kline/kline.go:208]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/d738219f. I moved the interval-count overflow path behind a package-level sentinel/helper and added direct coverage for that conversion path, so the test can assert it via `ErrorIs` instead of relying on string matching.

File: exchanges/okx/okx_test.go (hunk 30 above)
Comment (thrasher-) [reply exchanges/okx/okx_test.go]: Jarvis: Updated on the branch — this now uses `%w` in the test setup path so the wrapped error chain is preserved.

File: exchange/websocket/manager.go (hunk 17 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/470c151629f50c4d3eec8aa7d8b674749d266e17 — I renamed the mutex to `connectionManagerMu` so the name matches what it actually guards here (`connectionManager` / `connections`) rather than the subscription stores.

File: exchange/websocket/manager.go (hunk 18 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/470c151629f50c4d3eec8aa7d8b674749d266e17 — I renamed the mutex to `connectionManagerMu` so the name matches what it actually guards here (`connectionManager` / `connections`) rather than the subscription stores.

File: exchange/websocket/manager.go (hunk 19 above)
Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/470c151629f50c4d3eec8aa7d8b674749d266e17 — I renamed the mutex to `connectionManagerMu` so the name matches what it actually guards here (`connectionManager` / `connections`) rather than the subscription stores.

File: exchange/websocket/subscriptions.go (hunk 22 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/470c151629f50c4d3eec8aa7d8b674749d266e17 — I simplified this to a direct manager map lookup. Because this helper returns `(*websocket, bool)`, the final form is `ws := m.connections[conn]; return ws, ws != nil` rather than the one-value suggestion verbatim.

File: exchanges/kucoin/kucoin_wrapper.go (hunk 29 above)
Comment (thrasher-) [reply exchanges/kucoin/kucoin_wrapper.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/470c151629f50c4d3eec8aa7d8b674749d266e17 — I tweaked the wording to “can be collapsed to the same” to make the reason for the helper clearer. The helper still matters because the rounded feed can emit adjacent equal-price levels before the local book load.

File: exchange/websocket/subscriptions.go (hunk 5 above)
Comment (thrasher-) [reply exchange/websocket/subscriptions.go:77]: Jarvis: Agreed — the fallback to the manager-wide store when a connection is not tracked is pre-existing behaviour. I’ve left that broader routing cleanup out of this PR to keep this batch scoped.

File: exchange/websocket/subscriptions.go (hunk 22 above)
Comment (gloriousCode) [reply exchange/websocket/subscriptions.go]: My suggestion is still more appropriate since it returns two vars

Comment (thrasher-) [reply exchange/websocket/subscriptions.go]: Jarvis: I left this as-is intentionally. The bool here is meant to signal that we found a usable managed websocket, not merely that the map contains a key. With a pointer-valued map, comma-ok can return `(nil, true)` if a nil value ever slips into the map, and the current callsites treat `ok` as permission to dereference `ws` (`ws.setup`, `ws.subscriptions`, `ws.connections`). Keeping `return ws, ws != nil` preserves the stronger helper contract and centralises that guard in one place.

File: exchange/websocket/manager.go (hunk 16 above)
Comment (gloriousCode) [reply exchange/websocket/manager.go]: I think, to minimise scope of changes here, instead of deleting the connection and replacing it when it doesn't match, that we panic. Introducing deleting and replacing may give us some unexpected behaviour and I'd rather catch the scenario where this is happening (if it ever does). I liked the change where you don't re-add to the slice if it's already there.
Its a shaky helper func being introduced here, I don't want it too bogged down, but I also don't want it breaking things in weird ways like the replacement

Comment (thrasher-) [reply exchange/websocket/manager.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/86ec3852cf80e71c653e48d178e22f3ecf6f057a — I dropped the delete-and-replace path to keep the helper narrower. trackConnection is still idempotent for the same websocket, but if the same Connection is ever associated with a different websocket now it panics immediately so we catch the invariant violation instead of silently repairing it. TestTrackConnection was updated to cover both the duplicate same-websocket case and the conflicting different-websocket panic case.

File: internal/testing/exchange/exchange.go [hunk 31]
```diff
@@ -46,6 +46,10 @@ func Setup(e exchange.IBotExchange) error {
 	if err != nil {
 		return fmt.Errorf("GetExchangeConfig(%q) error: %w", eName, err)
 	}
+	if len(verbose) > 0 {
+		exchConf.Verbose = verbose[0]
+	}
```
Comment (shazbert) [inline internal/testing/exchange/exchange.go:51]:
```suggestion
	if len(verbose) > 0 && verbose[0] {
		exchConf.Verbose = true
	}
```

Might be better this way, so that we don't override with false and silence a true and false is a no op?

Comment (thrasher-) [reply internal/testing/exchange/exchange.go:51]: Jarvis: I left this as-is intentionally. The variadic here is an optional override, so if a caller passes a bool it should be honoured; making `Setup(e, false)` behave like “no override” would be surprising. Given the test config already defaults verbose to false and no current callers pass false, I don’t think the extra guard buys us anything.

File: exchange/websocket/subscriptions.go [hunk 32]
```diff
@@ -64,6 +64,40 @@ func (m *Manager) unsubscribe(store *subscription.Store, channels subscription.L
...
+func (m *Manager) subscriptionStore(conn Connection) *subscription.Store {
+	m.connectionManagerMu.RLock()
+	defer m.connectionManagerMu.RUnlock()
+	if ws, ok := m.connections[conn]; ok && conn != nil {
+		return ws.subscriptions
+	}
+	return m.subscriptions
+}
+
+func (m *Manager) initSubscriptionStore(conn Connection) *subscription.Store {
```
Comment (gloriousCode) [inline exchange/websocket/subscriptions.go:86]: Pedantic: change to `getSubscriptionStore`? There are paths here that don't init anything

Comment (thrasher-) [reply exchange/websocket/subscriptions.go:86]: Jarvis: I’d keep `initSubscriptionStore` here. It’s the get-or-create helper and is intentionally distinct from `subscriptionStore`, which is the read-only getter; even when a given call hits an already-initialised path, this helper still carries the “ensure store exists” contract, so `getSubscriptionStore` would blur that difference.
