### PR TITLE
Websocket reconnection fix

### LINKED ISSUE #540: Reconnection doesn't happen
# New Issue

If there are unexpected EOF aka DisconnectionErrors from a websocket connection, it does not reconnect.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:

* GoCryptoTrader version (`gocryptotrader -version`): master

## Expected Behavior
reconnect

## Current Behavior
does not reconnect.

```
Deribit websocket has been disconnected. Reason: websocket: close 1006 (abnormal closure): unexpected EOF
traffic monitor already running
Deribit websocket connection: ping handler failed to send message []
Deribit websocket: trafficMonitor shutdown err: Deribit websocket: cannot shutdown a disconnected websocket
<hangs>
```

## Failure Information (for bugs)

https://github.com/thrasher-corp/gocryptotrader/blob/627a1e38ea61955520994011a3be28c6b646d5bd/exchanges/websocket/wshandler/wshandler.go#L148-L159

https://github.com/thrasher-corp/gocryptotrader/blob/3bd3826ac2e95d535da878d0a7fc040ad20e5042/exchanges/stream/websocket.go#L331-L336

It seems that w.Connect() was removed. Is there a reason? @shazbert 

Could this hardcoded `false` for the `reconnect` arg be why? Is that intentional?
https://github.com/thrasher-corp/gocryptotrader/blob/3bd3826ac2e95d535da878d0a7fc040ad20e5042/exchanges/stream/websocket.go#L78

update: In an effort to try to simulate an unexpected disconnection, I just turned wifi off. However it looks like a different error when it comes to reconnecting.
```
<disconnect internet>
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
<if i reconnect here, it continues running>
Deribit websocket: running connection monitor cycle
Deribit websocket: has not received a traffic alert in 30s. Reconnecting
Deribit websocket: shutting down websocket
Deribit websocket: trafficMonitor shutdown err: write tcp 192.168.1.60:54251->193.72.79.190:443: write: can't assign requested address
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
<if I reconnect here, it doesn't ever connect>
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
Deribit websocket connection: sending message []
Deribit websocket connection: ping handler failed to send message []
Deribit websocket: running connection monitor cycle
Deribit websocket: running connection monitor cycle
```

Anyways I have turned verbose mode on and will wait until the next invalid EOF comes through from Deribit to see what happens.

### PR DESCRIPTION
**Pull request by shazbert**
# PR Description

Attempts to address an issue where it would not connect after losing connection. 

Adds in functionality to fix bug where Gateio was not subscribing to new enabled pairs due to an already subscribed check.

Add tests and increase code coverage.

Also, updated depends and ran a go mod tidy. 

@azhang Thanks for bringing this to our attention, this should be fixed now if you have a chance please test.

Fixes #540 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [x] Ran it, ipconfig /release -> saw that everything was erroring, ipconfig /renew -> everything reconnected in a nice snappy fashion. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: exchanges/stream/websocket.go [hunk 1]
```diff
@@ -513,32 +508,35 @@ func (w *Websocket) trafficMonitor() error {
...
-			select {
-			case <-w.ShutdownC:
-				trafficTimer.Stop()
-				w.setTrafficMonitorRunning(false)
-				w.Wg.Done()
-				return
-			case <-pause:
+			if w.IsConnected() {
+				// Routine pausing mechanism
+				go func(p chan struct{}) {
```
[the remark this answers is not in the document]
Comment (shazbert) [reply exchanges/stream/websocket.go:525]: spot on

**Comment by azhang** [comment]
Amazing! Thanks so much for the help! I will test as soon as I am able, but it might be a few days because I'll be traveling over the next week.

**Comment by shazbert** [comment]
FYI: Found a bug in Gateio on the subscription when enabling/disabling pairs will be updating that soon.

File: exchanges/stream/websocket.go [hunk 2]
```diff
@@ -854,6 +848,19 @@ func (w *Websocket) SubscribeToChannels(channels []ChannelSubscription) error {
...
+func (w *Websocket) fullSubscribeToChannels(channels []ChannelSubscription) error {
+	if len(channels) == 0 {
+		return fmt.Errorf("%s websocket: cannot subscribe no channels supplied",
+			w.exchangeName)
+	}
+	w.subscriptionMutex.Lock()
+	defer w.subscriptionMutex.Unlock()
+	return w.Subscriber(channels)
+}
+
```
Comment (gloriousCode) [inline exchanges/stream/websocket.go:863]: I think this could be solved without this function by not returning an error if something is already subscribed.
See here: 
https://github.com/thrasher-corp/gocryptotrader/pull/541/files#diff-c248a1ef42c669be711d82b5cadb3016R842

This would also fix another bug where if subscription 1/100 in the list of channels is already subscribed, then 99 channels don't get to subscribe because you're returning on error

File: exchanges/stream/websocket_test.go [hunk 3]
```diff
@@ -80,15 +168,10 @@ func TestTrafficMonitorTimeout(t *testing.T) {
 	}
 	ws.trafficTimeout = time.Second
 	ws.ShutdownC = make(chan struct{})
-	err = ws.trafficMonitor()
-	if err != nil {
-		t.Fatal(err)
-	}
+	ws.trafficMonitor()
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:171]: you could add a check to see if the traffic monitor is running with `w.IsTrafficMonitorRunning()`

File: exchanges/stream/websocket_test.go [hunk 4]
```diff
@@ -234,6 +344,27 @@ func TestWebsocket(t *testing.T) {
 	if err == nil {
 		t.Fatal("should not be connected to able to shut down")
 	}
+
+	ws.verbose = true
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:348]: does this need to remain?

File: exchanges/stream/websocket_test.go [hunk 5]
```diff
@@ -234,6 +344,27 @@ func TestWebsocket(t *testing.T) {
...
+	ws.connected = true
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:349]: Would be better to use the `ws.setConnectedStatus`

File: exchanges/stream/websocket_test.go [hunk 6]
```diff
@@ -355,7 +503,14 @@ func TestConnectionMonitorNoConnection(t *testing.T) {
 	ws.ShutdownC = make(chan struct{}, 1)
 	ws.exchangeName = "hello"
 	ws.trafficTimeout = 1
-	go ws.connectionMonitor()
+	ws.verbose = true
+	ws.Wg = &sync.WaitGroup{}
+	ws.connectionMonitor()
+	ws.connectionMonitor() // This one should exit
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:509]: You could add a check to `IsConnectionMonitorRunning`now that we can't rely on a returned error

File: exchanges/stream/websocket_test.go [hunk 7]
```diff
@@ -355,7 +503,14 @@ func TestConnectionMonitorNoConnection(t *testing.T) {
...
+	time.Sleep(time.Second)
+	ws.connected = true  // attempt shutdown when not enabled
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:511]: Any reason here not to use the lock functions? If they ever get flipped while this test is running you could get a data race

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Initial review nits, and then I'll test!
## 🦖

File: exchanges/stream/websocket_test.go (hunk 4 above)
Comment (shazbert) [reply exchanges/stream/websocket_test.go:348]: Debatable, it adds to the code coverage.

File: exchanges/stream/websocket.go (hunk 2 above)
Comment (shazbert) [reply exchanges/stream/websocket.go:863]: I see your point, but if we do get an error that means that subscription generation/regeneration for an exchange is broken. I would rather keep the error for implementation/integration issues for future devs. Debatable issue. @xtda @thrasher-

File: exchanges/stream/websocket_test.go [hunk 8]
```diff
@@ -112,20 +198,50 @@ func TestIsDisconnectionError(t *testing.T) {
...
+
+	wsWrong.enabled = true
+	wsWrong.connecting = true
+	wsWrong.Wg = &sync.WaitGroup{}
+	err = wsWrong.Connect()
+	if err == nil {
+		t.Fatal("error cannot be nil")
+	}
+
+	wsWrong.connecting = false
```
Comment (gloriousCode) [inline exchanges/stream/websocket_test.go:236]: two more to use the protected funcs with

File: exchanges/stream/websocket_test.go (hunk 4 above)
Comment (gloriousCode) [reply exchanges/stream/websocket_test.go:372]: It is only covering logging though 😄 but since the logs don't output unless you have -v on, I'll resolve this

File: exchanges/stream/websocket_test.go (hunk 8 above)
Comment (shazbert) [reply exchanges/stream/websocket_test.go:236]: Spotto

File: common/common.go [hunk 9]
```diff
@@ -54,7 +54,15 @@ func initialiseHTTPClient() {
 // NewHTTPClientWithTimeout initialises a new HTTP client with the specified
 // timeout duration
 func NewHTTPClientWithTimeout(t time.Duration) *http.Client {
-	h := &http.Client{Timeout: t}
+	tr := &http.Transport{
+		// Added IdleConnTimeout to reduce the time of idle connections which
+		// could potentially slow macOS reconnection when there is a sudden
+		// network disconnection/issue
+		IdleConnTimeout: time.Second * 15,
```
Comment (thrasher-) [inline common/common.go:61]: Very cool find, only request would be to use the t value so that the configurable value can be used for both idle connections and request timeouts

**Comment by thrasher-** [comment]
CI has picked up a 🐎 https://travis-ci.com/github/thrasher-corp/gocryptotrader/jobs/375995178#L366

File: common/common.go [hunk 10]
```diff
@@ -51,10 +51,18 @@ func initialiseHTTPClient() {
 	}
 }
 
-// NewHTTPClientWithTimeout initialises a new HTTP client with the specified
-// timeout duration
+// NewHTTPClientWithTimeout initialises a new HTTP client and its underlying
+// transport IdleConnTimeout with the specified timeout duration
 func NewHTTPClientWithTimeout(t time.Duration) *http.Client {
-	h := &http.Client{Timeout: t}
+	tr := &http.Transport{
```
Comment (thrasher-) [inline common/common.go:57]: There's 2 things left over to contend with:

1) If someone uses a proxy for an exchange, the transport settings here will be overwritten, making this ineffective
2) When an exchange is loaded in SetupDefaults, I think we should also upgrade the SetHTTPClientTimeout method to also adjust the transport IdleConnTimeout too so that both are in line with each other

File: exchanges/stream/websocket.go [hunk 11]
```diff
@@ -296,64 +288,66 @@ func (w *Websocket) connectionMonitor() {
...
+				w.setConnectionMonitorRunning(false)
+				return
 			}
-			if !timer.Stop() {
-				select {
-				case <-timer.C:
-				default:
+			select {
+			case err := <-w.ReadMessageErrors:
+				// check if this error is a disconnection error
```
Comment (gloriousCode) [inline exchanges/stream/websocket.go:323]: I think we can remove this comment

**Review by gloriousCode — CHANGES_REQUESTED** [review]
Just two really minor nits from me 🌞

File: exchanges/exchange_test.go [hunk 12]
```diff
@@ -1839,3 +1871,136 @@ func Test_FormatExchangeKlineInterval(t *testing.T) {
...
+}
+
+func TestKlineIntervalEnabled(t *testing.T) {
+	b := Base{}
+	if b.KlineIntervalEnabled(kline.EightHour) {
+		t.Fatal("unexpected value")
+	}
+}
+
+func TestFormatExchangeKlineINterval(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (shazbert) [reply exchanges/exchange_test.go:2001]: 😄

File: exchanges/stream/websocket.go (hunk 11 above)
Comment (shazbert) [reply exchanges/stream/websocket.go:323]: Good point will remove

**Review by xtda — APPROVED** [review]
tested websocket reconnection with the new transport idle timeout changes and was able to get reconnected with the problem exchanges from before (binance :D) 

Approved

**Review by gloriousCode — APPROVED** [review]
tick tACK,, front and back

**Review by thrasher- — CHANGES_REQUESTED** [review]
Thanks for making those changes, please rebase master + go mod tidy and then this LG2G

**Review by thrasher- — APPROVED** [review]
