### PR TITLE
dispatch: channel reuse fix

### LINKED ISSUE #1236: Dispatcher tries to return used channels that are `<-chan interface{}` as `chan interface` and fails
# New Issue

## Expected Behavior

Tickers, orderbooks and balance data can be accessed through a subscription using a multiplexer using the `dispatch` package.
Subscribing to a UUID of a ticker/orderbook/account provides a 'Pipe' that holds a channel which is provided through sync.Pool. When unsubscribing from the item's updates through releasing the pipe, the used channel is returned to the pool. On a subsequent subscription, Pool.Get() doesn't return a New() item, but it pops a used channel and returns it to the caller.

## Current Behavior

Currently, when unsubscribing, a `<-chan interface{}` is put into the Pool, while subscribing tries to get a `chan interface{}`. As the pool holds used items as `any` types, a type assertion error is produced when accessing a used channel of type `<-chan interface{}` as a `chan interface{}` in dispatch/dispatch.go:245 

```
	ch, ok := getResult.(chan interface{})
	if !ok {
		return nil, errTypeAssertionFailure
	}
```

### Steps to Reproduce

To reproduce, subscribe, unsubscribe and subscribe as per this (updated) test:

https://github.com/TaltaM/gocryptotrader/commit/387fca940b59801c2192eec4e6cc6b1479fd85f7

```
$ go test -v ./dispatch
=== RUN   TestGlobalDispatcher
--- PASS: TestGlobalDispatcher (0.00s)
<...snap...>
=== CONT  TestSubscribe
=== NAME  TestUnsubscribe
    dispatch_test.go:229: received: 'type assertion failure - <-chan interface {} is not a chan interface {}' but expected: '<nil>'
--- FAIL: TestUnsubscribe (0.00s)
<...snap...>
```

### PR DESCRIPTION
**Pull request by TaltaM**
# PR Description

When unsubscribing using the dispatcher, a `<-chan interface{}` is put in a pool. When subscribing results in getting a used channel as a `chan interface{}` from the pool, a type assertion error happens. 

One solution would be to store all used channels as bidirectional channels. Alternative solutions could be possible too.

Fixes #1236

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Added a section to the dispatch test 'TestUnsubscribe' that would fail with the current code:

```
=== NAME  TestUnsubscribe
    dispatch_test.go:229: received: 'type assertion failure' but expected: '<nil>'
```

But passes with the proposed solution.

- [x] go test ./... -race
- [ ] golangci-lint run
- [x] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: dispatch/dispatch_types.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ type Mux struct {
 // Pipe defines an outbound object to the desired routine
 type Pipe struct {
 	// Channel to get all our lovely information
-	C <-chan interface{}
+	C chan interface{}
```
Comment (shazbert) [inline dispatch/dispatch_types.go:75]: Could un-export the field `c` just for protection reasons, below is a diff for changes. Let me know what you think. You can adjust the names if you want. 

```diff
diff --git a/dispatch/dispatch_test.go b/dispatch/dispatch_test.go
index d9e5fa664..6711bced1 100644
--- a/dispatch/dispatch_test.go
+++ b/dispatch/dispatch_test.go
@@ -426,7 +426,7 @@ func TestMux(t *testing.T) {
                        return
                }
                errChan <- nil
-       }(pipe.C, errChan, &wg)
+       }(pipe.c, errChan, &wg)

        wg.Wait()

@@ -506,7 +506,7 @@ func TestMuxPublish(t *testing.T) {
                }
        }(mux)

-       <-pipe.C
+       <-pipe.Wait()

        // Shut down dispatch system
        err = d.stop()
diff --git a/dispatch/dispatch_types.go b/dispatch/dispatch_types.go
index a4b149d6d..68091d108 100644
--- a/dispatch/dispatch_types.go
+++ b/dispatch/dispatch_types.go
@@ -72,9 +72,14 @@ type Mux struct {
 // Pipe defines an outbound object to the desired routine
 type Pipe struct {
        // Channel to get all our lovely information
-       C chan interface{}
+       c chan interface{}
        // ID to tracked system
        id uuid.UUID
        // Reference to multiplexer
        m *Mux
 }
+
+// Wait returns a channel to wait on for data
+func (p *Pipe) Wait() <-chan interface{} {
+       return p.c
+}
diff --git a/dispatch/mux.go b/dispatch/mux.go
index ecd983069..c597d0797 100644
--- a/dispatch/mux.go
+++ b/dispatch/mux.go
@@ -38,7 +38,7 @@ func (m *Mux) Subscribe(id uuid.UUID) (Pipe, error) {
                return Pipe{}, err
        }

-       return Pipe{C: ch, id: id, m: m}, nil
+       return Pipe{c: ch, id: id, m: m}, nil
 }

 // Unsubscribe returns channel to the pool for the full signature set
@@ -83,5 +83,5 @@ func (m *Mux) GetID() (uuid.UUID, error) {

 // Release returns the channel to the communications pool to be reused
 func (p *Pipe) Release() error {
-       return p.m.Unsubscribe(p.id, p.C)
+       return p.m.Unsubscribe(p.id, p.c)
 }
diff --git a/engine/rpcserver.go b/engine/rpcserver.go
index 0b51de192..769a1d0ea 100644
--- a/engine/rpcserver.go
+++ b/engine/rpcserver.go
@@ -714,7 +714,7 @@ func (s *RPCServer) GetAccountInfoStream(r *gctrpc.GetAccountInfoRequest, stream
        }()

        for {
-               data, ok := <-pipe.C
+               data, ok := <-pipe.Wait()
                if !ok {
                        return errDispatchSystem
                }
@@ -2188,7 +2188,7 @@ func (s *RPCServer) GetExchangeOrderbookStream(r *gctrpc.GetExchangeOrderbookStr
        }()

        for {
-               data, ok := <-pipe.C
+               data, ok := <-pipe.Wait()
                if !ok {
                        return errDispatchSystem
                }
@@ -2273,7 +2273,7 @@ func (s *RPCServer) GetTickerStream(r *gctrpc.GetTickerStreamRequest, stream gct
        }()

        for {
-               data, ok := <-pipe.C
+               data, ok := <-pipe.Wait()
                if !ok {
                        return errDispatchSystem
                }
@@ -2326,7 +2326,7 @@ func (s *RPCServer) GetExchangeTickerStream(r *gctrpc.GetExchangeTickerStreamReq
        }()

        for {
-               data, ok := <-pipe.C
+               data, ok := <-pipe.Wait()
                if !ok {
                        return errDispatchSystem
                }
diff --git a/exchanges/account/account_test.go b/exchanges/account/account_test.go
index 90fe5980a..8ba7cfc2d 100644
--- a/exchanges/account/account_test.go
+++ b/exchanges/account/account_test.go
@@ -213,7 +213,7 @@ func TestGetHoldings(t *testing.T) {
                for i := 0; i < 2; i++ {
                        c := time.NewTimer(time.Second)
                        select {
-                       case <-p.C:
+                       case <-p.Wait():
                        case <-c.C:
                        }
                }
```

**Review by shazbert — CHANGES_REQUESTED** [review]
Thanks for opening this PR with the fix nice catch! Just one suggestion.

File: dispatch/dispatch_types.go (hunk 1 above)
Comment (TaltaM) [reply dispatch/dispatch_types.go]: OK! I renamed Wait() to Channel() as it's more of a getter than a waiter.

**Review by shazbert — APPROVED** [review]
Thank you! 🚀

**Review by gloriousCode — APPROVED** [review]
tACK! Thank you for taking the time to understand the problem, coming up with a solution and writing a test to highlight the issue

**Review by thrasher- — APPROVED** [review]
Thanks for the PR and extended test coverage @TaltaM 💯 !
