### PR TITLE
Binance/BinanceUS: Fix various live test failures

### LINKED ISSUE #2010: Binance: TestGetHistoricTrades live panic due to API change
```
--- FAIL: TestGetHistoricTrades (11.70s)
    binance_test.go:1488:
                Error Trace:    C:/Programming/Go/src/github.com/thrasher-corp/gocryptotrader/exchanges/binance/binance_test.go:1488
                Error:          Not equal:
                                expected: 2134
                                actual  : 0
                Test:           TestGetHistoricTrades
                Messages:       GetHistoricTrades should return correct number of entries
database support is disabled
--- FAIL: TestGetAggregatedTradesBatched (57.67s)
    --- FAIL: TestGetAggregatedTradesBatched/batch_with_timerange (48.15s)
        binance_test.go:1577: GetAggregatedTradesBatched() expected 12130 entries, got 0
panic: runtime error: index out of range [-1] [recovered, repanicked]
```

### PR DESCRIPTION
**Pull request by gbjk**
* Fixes failures on `TestGetAggregatedTradesBatched` and `TestGetHistoricTrades`
* Refactors and simplifies `GetAggregatedTradesBatched` (hopefully)

Note: These fixes are for testing with `--tags mock_test_off`

Fixes #2010

- [x] Test fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: exchanges/binance/binance.go [hunk 1]
```diff
@@ -311,37 +309,33 @@ func (e *Exchange) batchAggregateTrades(ctx context.Context, arg *AggregatedTrad
...
 		}
-		lastIndex := len(additionalTrades)
-		if !arg.EndTime.IsZero() {
-			// get index for truncating to end time
-			lastIndex = sort.Search(len(additionalTrades), func(i int) bool {
-				return arg.EndTime.Before(additionalTrades[i].TimeStamp.Time())
-			})
+		switch len(additionalTrades) {
+		case 0, 1:
+			break // We only got the one we already have
```
Comment (shazbert) [inline exchanges/binance/binance.go]: break outer loop? or just rm to hit if case below?

File: exchanges/binance/binance_test.go [hunk 2]
```diff
@@ -1477,109 +1477,108 @@ func TestNewOrderTest(t *testing.T) {
 func TestGetHistoricTrades(t *testing.T) {
```
Comment (shazbert) [inline exchanges/binance/binance_test.go:1479]: This fails on a live test

File: exchanges/binance/binance_test.go [hunk 3]
```diff
@@ -1477,109 +1477,108 @@ func TestNewOrderTest(t *testing.T) {
...
-			break
-		}
+		require.WithinRange(t, r.Timestamp, start, end, "All trades must be within time range")
 	}
 }
 
+// TestGetAggregatedTradesBatched exercises TestGetAggregatedTradesBatched to ensure our date and limit scanning works correctly
+// This test is susceptible to failure if volumes change a lot, during wash trading or zero-fee periods
+// In live tests, 45 minutes is expected to return more than 1000 records
 func TestGetAggregatedTradesBatched(t *testing.T) {
```
Comment (shazbert) [inline exchanges/binance/binance_test.go:1498]: this fails on a live test

File: exchanges/binance/binance.go [hunk 4]
```diff
@@ -268,40 +268,38 @@ func (e *Exchange) GetAggregatedTrades(ctx context.Context, arg *AggregatedTrade
...
+	return resp, e.SendHTTPRequest(ctx, exchange.RestSpotSupplementary, path, spotDefaultRate, &resp)
 }
 
 // batchAggregateTrades fetches trades in multiple requests
-// first phase, hourly requests until the first trade (or end time) is reached
-// second phase, limit requests from previous trade until end time (or limit) is reached
-func (e *Exchange) batchAggregateTrades(ctx context.Context, arg *AggregatedTradeRequestParams, params url.Values) ([]AggregatedTrade, error) {
+// If no args.FromID is passed, requests are made intervals doubling from 10s until we get a viable starting position.
+// Once the starting set is found, we continue scanning until we have all the trades in the time window
+func (e *Exchange) batchAggregateTrades(ctx context.Context, args *AggregatedTradeRequestParams, params url.Values) ([]AggregatedTrade, error) {
```
Comment (shazbert) [inline exchanges/binance/binance.go:278]: Seems a bit backwards. I think this functionality should be in the wrapper file and only called in `GetHistoricTrades` , and GetAggregatedTrades get called without the batch handling and the added complexity and return exactly what it needs. Just to map to API. But not worth changing.

**Review by shazbert — CHANGES_REQUESTED** [review]
Just some nits for live testing ❤️

File: exchanges/binance/binance.go (hunk 4 above)
Comment (gbjk) [reply exchanges/binance/binance.go:278]: Agreed, but I'm not baking that big of a bite into this. Just fixing the bug. 👍

File: exchanges/binance/binance.go (hunk 1 above)
Comment (gbjk) [reply exchanges/binance/binance.go]: Jesus. Sorry about that. Awful code.

DriveBy remove comment on line 311, which I meant to remove a few times.

Fixed 05d8d3faa

File: exchanges/binance/binance_test.go (hunk 3 above)
Comment (gbjk) [reply exchanges/binance/binance_test.go:1498]: Thanks!
Could you be more specific?
Did it fail locally for you, and can you replicate now?

```
❯ go test -count=1 --tags mock_test_off -v  ./exchanges/binance/ -run TestGetAggregatedTradesBatched/
--- PASS: TestGetAggregatedTradesBatched (0.00s)
    --- PASS: TestGetAggregatedTradesBatched/custom_limit_with_start_time_set,_no_end_time (0.46s)
    --- PASS: TestGetAggregatedTradesBatched/batch_with_timerange (4.77s)
PASS
ok      github.com/thrasher-corp/gocryptotrader/exchanges/binance       8.984s
```

File: exchanges/binance/binance_test.go (hunk 2 above)
Comment (gbjk) [reply exchanges/binance/binance_test.go:1479]: Also can't replicate this.

File: exchanges/binance/binance.go [hunk 5]
```diff
@@ -310,38 +308,34 @@ func (e *Exchange) batchAggregateTrades(ctx context.Context, arg *AggregatedTrad
 	// other requests follow from the last aggregate trade id and have no time window
 	params.Del("startTime")
 	params.Del("endTime")
-	// while we haven't reached the limit
-	for ; arg.Limit == 0 || len(resp) < arg.Limit; fromID = resp[len(resp)-1].ATradeID {
+outer:
+	for ; args.Limit == 0 || len(resp) < args.Limit; fromID = resp[len(resp)-1].ATradeID {
 		// Keep requesting new data after last retrieved trade
 		params.Set("fromId", strconv.FormatInt(fromID, 10))
 		path := aggregatedTrades + "?" + params.Encode()
```
Comment (samuael) [inline exchanges/binance/binance.go:320]: THis is used only once and no need for declaring it here. COuld just replace it in the `SendHTTPRequest` method

Comment (gbjk) [reply exchanges/binance/binance.go:320]: Respectfully decline this suggestion:
It's just a bit too long to feel right to fold into that line.
It'd be too unclear and the whole line gets too long.

I made the change and looked at it before replying.

**Comment by thrasher-** [comment]
@codex please review

File: exchanges/binance/binance.go [hunk 6]
```diff
@@ -268,40 +268,38 @@ func (e *Exchange) GetAggregatedTrades(ctx context.Context, arg *AggregatedTrade
...
 			path := aggregatedTrades + "?" + params.Encode()
-			err := e.SendHTTPRequest(ctx,
-				exchange.RestSpotSupplementary, path, spotDefaultRate, &resp)
+			err := e.SendHTTPRequest(ctx, exchange.RestSpotSupplementary, path, spotDefaultRate, &resp)
 			if err != nil {
-				return resp, fmt.Errorf("%w %v", err, arg.Symbol)
+				return resp, fmt.Errorf("%w %v", err, args.Symbol)
 			}
 		}
 		fromID = resp[len(resp)-1].ATradeID
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/binance/binance.go]: @codex You're right. It also incorrectly kept moving start time by the new increment, instead of the other way around. And we need to protect against no end date and overflowing increment.

Fixed gbjk@a2b82b232

[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/binance/binance.go]: @codex Done; Please review

File: exchanges/binance/binance.go [hunk 7]
```diff
@@ -268,40 +268,42 @@ func (e *Exchange) GetAggregatedTrades(ctx context.Context, arg *AggregatedTrade
 	}
```
Comment (gloriousCode) [inline exchanges/binance/binance.go:269]: Hello friend, what affects binance affects binance in the US OF A! 
I have copied across your changes to binanceus in gist form for your eyeballs:
https://gist.github.com/gloriousCode/ed5170bea8f3f592ad895f49898535d3

Comment (gbjk) [reply exchanges/binance/binance.go:269]: Dude! Thank you so much 🫶

Fixed https://github.com/gbjk/gocryptotrader/commit/7d8661bf4

**Review by thrasher- — CHANGES_REQUESTED** [review]
Looks like BinanceUS tests are failing:

https://github.com/thrasher-corp/gocryptotrader/actions/runs/17791729939/job/50570112052#step:11:3081

File: exchanges/binance/binance.go (hunk 7 above)
Comment (gloriousCode) [reply exchanges/binance/binance.go:269]: [You thanked me too soon ](https://github.com/thrasher-corp/gocryptotrader/pull/2019#pullrequestreview-3236712285) (sorry)

**Comment by gbjk** [comment]
> Looks like BinanceUS tests are failing:

Huh. Can't replicate locally, with or without mocks. Will kick it to rerun.
Funny if it's a coincidence.

**Comment by gbjk** [comment]
> Looks like BinanceUS tests are failing:

@thrasher- Thanks for spotting that.
We lost the symbol formatting in the changes to binanceus.
I've fixed that, and also re-read the patch more carefully and verified the 59 minute clipping is not necessary.

File: exchanges/binanceus/binanceus_test.go [hunk 8]
```diff
@@ -1756,3 +1760,50 @@ func TestGetCurrencyTradeURL(t *testing.T) {
...
+			},
+		},
+		{
+			name: "custom limit with start time set, no end time",
+			args: &AggregatedTradeRequestParams{StartTime: start, Limit: 2042},
+			expFunc: func(t *testing.T, results []AggregatedTrade) {
+				t.Helper()
+				// 2000 records in was about 6 minutes in 2025; Adjust if Binance enters a phase of zero-fees or low-volume
+				require.Equal(t, 2042, len(results), "must return exactly the limit number of records")
+				assert.WithinDuration(t, results[len(results)-1].TimeStamp.Time(), start, 48*time.Hour, "last record should be within 20 minutes of start time")
```
Comment (gloriousCode) [inline exchanges/binanceus/binanceus_test.go]:
```suggestion
				assert.WithinDuration(t, results[len(results)-1].TimeStamp.Time(), start, 48*time.Hour, "last record should be within 48 hours of start time")
```
binanceus is the place for trading solo

File: exchanges/binanceus/binanceus.go [hunk 9]
```diff
@@ -203,84 +202,81 @@ func (e *Exchange) GetHistoricalTrades(ctx context.Context, hist HistoricalTrade
 // GetAggregateTrades to get compressed, aggregate trades. Trades that fill at the time, from the same order, with the same price will have the quantity aggregated.
 func (e *Exchange) GetAggregateTrades(ctx context.Context, agg *AggregatedTradeRequestParams) ([]AggregatedTrade, error) {
 	params := url.Values{}
-	symbol, err := e.FormatSymbol(agg.Symbol, asset.Spot)
-	if err != nil {
+	if s, err := e.FormatSymbol(agg.Symbol, asset.Spot); err != nil {
 		return nil, err
+	} else {
+		params.Set("symbol", s)
 	}
```
Comment (gloriousCode) [inline exchanges/binanceus/binanceus.go]: Lint is having issue here. My previous suggestion is invalid too though. Please fix lint

**Review by gloriousCode — CHANGES_REQUESTED** [review]
minor things. thanks for applying (and also fixing) my diff!

File: exchanges/binanceus/binanceus_test.go (hunk 8 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/f0aee15c8

File: exchanges/binanceus/binanceus.go (hunk 9 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus.go]: I did this on porpoise 🐬 
`s` is scoped.
I like scoping things.
They don't escape, grow up, and start a revenge ark on you.
And the GC gets to collect early.

File: exchanges/binanceus/binanceus_test.go (hunk 8 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus_test.go]: Reviewed all of the numbers with live results and updated accordingly.

Fixed https://github.com/gbjk/gocryptotrader/commit/7fd911d1b

If this turns out to be fragile can just widen the hole ....

File: exchanges/binanceus/binanceus.go (hunk 9 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus.go]: Sorry, I just spotted that this is a lint revive error.
How hateful 😡 

Fixed https://github.com/gbjk/gocryptotrader/commit/bef5158bf

**Review by gloriousCode — APPROVED** [review]
Thanks for making those changes!

**Comment by gbjk** [comment]
> Thanks for resolving this issue! Live tests are happy for candle stuff but there's one last live test which isn't happy, so please apply this patch:

Fixed https://github.com/gbjk/gocryptotrader/commit/185def555

> There's also a linter issue after rebasing

Fixed https://github.com/gbjk/gocryptotrader/commit/2c70d16f2

**Review by thrasher- — APPROVED** [review]
Changes tACK, thanks!

**Review by shazbert — APPROVED** [review]
Thanks!
