### PR TITLE
Deribit: Add futureComboPairToString func, remove redundant endpoints and fix test issues

### LINKED ISSUE #2099: Deribit: Invalid instrument name being sent intermittently
Spotted here: https://github.com/thrasher-corp/gocryptotrader/actions/runs/18964101185/job/54157296306?pr=2096#step:11:354

```
--- FAIL: TestGetOrderbookData (0.58s)
    deribit_test.go:788: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:788
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890351821452,"usOut":1761890351821530,"usDiff":78}
        	Test:       	TestGetOrderbookData
        	Messages:   	expected <nil>, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890351821452,"usOut":1761890351821530,"usDiff":78} currency pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestWSRetrieveLastTradesByInstrument (0.44s)
    deribit_test.go:704: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:704
        	Error:      	Received unexpected error:
        	            	code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"}
        	Test:       	TestWSRetrieveLastTradesByInstrument
        	Messages:   	expected <nil>, got code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"} currency asset future_combo pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestWSRetrieveLastTradesByInstrumentAndTime (0.75s)
    deribit_test.go:728: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:728
        	Error:      	Received unexpected error:
        	            	code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"}
        	Test:       	TestWSRetrieveLastTradesByInstrumentAndTime
        	Messages:   	expected <nil>, got code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"} currency pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetLastTradesByInstrumentAndTime (0.74s)
    deribit_test.go:716: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:716
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890352371020,"usOut":1761890352371126,"usDiff":106}
        	Test:       	TestGetLastTradesByInstrumentAndTime
        	Messages:   	expected <nil>, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890352371020,"usOut":1761890352371126,"usDiff":106} currency pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetLastTradesByInstrument (0.75s)
    deribit_test.go:692: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:692
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890353125236,"usOut":1761890353125325,"usDiff":89}
        	Test:       	TestGetLastTradesByInstrument
        	Messages:   	expected <nil>, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890353125236,"usOut":1761890353125325,"usDiff":89} currency asset future_combo pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetInstrumentData (0.70s)
    deribit_test.go:555: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:555
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890353953520,"usOut":1761890353953581,"usDiff":61}
        	Test:       	TestGetInstrumentData
        	Messages:   	expected nil, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890353953520,"usOut":1761890353953581,"usDiff":61} for asset type future_combo pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestWSRetrieveBookSummaryByInstrument (0.41s)
    deribit_test.go:344: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:344
        	Error:      	Received unexpected error:
        	            	code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"}
        	Test:       	TestWSRetrieveBookSummaryByInstrument
        	Messages:   	expected nil, got code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"} for pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestWSRetrieveMarkPriceHistory (0.62s)
    deribit_test.go:280: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:280
        	Error:      	Received unexpected error:
        	            	code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"}
        	Test:       	TestWSRetrieveMarkPriceHistory
        	Messages:   	expected <nil>, got code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"} currency pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetMarkPriceHistory (0.57s)
    deribit_test.go:262: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:262
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890355600251,"usOut":1761890355600325,"usDiff":74}
        	Test:       	TestGetMarkPriceHistory
        	Messages:   	expected nil, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890355600251,"usOut":1761890355600325,"usDiff":74} for pair ETH-USDC-FS-28NOV25_PERP
Deribit - [missing data between 2025-08-02 00:00:00 and 2025-10-24 08:00:00 missing data between 2025-10-31 06:00:00 and 2025-11-01 00:00:00]
--- FAIL: TestUpdateOrderbook (0.44s)
    deribit_test.go:141: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:141
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890356154096,"usOut":1761890356154172,"usDiff":76}
        	Test:       	TestUpdateOrderbook
        	Messages:   	asset type: future_combo
Deribit - [missing data between 2025-08-02 00:00:00 and 2025-10-24 08:00:00 missing data between 2025-10-31 06:00:00 and 2025-11-01 00:00:00]
--- FAIL: TestFetchRecentTrades (0.83s)
    deribit_test.go:160: 
        	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:160
        	Error:      	Received unexpected error:
        	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890356428856,"usOut":1761890356428932,"usDiff":76}
        	Test:       	TestFetchRecentTrades
        	Messages:   	expected nil, got Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890356428856,"usOut":1761890356428932,"usDiff":76} for asset type future_combo pair ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetRecentTrades (0.00s)
    --- FAIL: TestGetRecentTrades/future_combo_ETH-USDC-FS-28NOV25_PERP (0.13s)
        deribit_test.go:3418: 
            	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:3418
            	Error:      	Received unexpected error:
            	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890358667594,"usOut":1761890358667682,"usDiff":88}
            	Test:       	TestGetRecentTrades/future_combo_ETH-USDC-FS-28NOV25_PERP
            	Messages:   	GetRecentTrades must not error
Potential book issue for exchange Deribit pair BTC-PERPETUAL asset futures length Bids 259 length Asks 0
Deribit wss://www.deribit.com/ws/api/v2: Sending message: {"jsonrpc":"2.0","id":"019a38d9-56c1-709f-a94f-ae467afdd6a7","method":"public/get_instrument","params":{"instrument_name":"ETH-USDC-FS-28NOV25_PERP"}}
Deribit wss://www.deribit.com/ws/api/v2: Sending message: {"jsonrpc":"2.0","id":"019a38d9-56e3-709f-a54f-026a6b4ae82d","method":"public/get_instrument","params":{"instrument_name":"BTC_USDC-CCAL-7NOV25_31OCT25-114000"}}
Deribit wss://www.deribit.com/ws/api/v2: Sending message: {"jsonrpc":"2.0","id":"019a38d9-5717-709f-9e1c-073fe890d076","method":"public/get_instrument","params":{"instrument_name":"BTC-PERPETUAL"}}
Deribit wss://www.deribit.com/ws/api/v2: Received response [1/1]: {"jsonrpc":"2.0","id":"019a38d9-56c1-709f-a94f-ae467afdd6a7","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"usIn":1761890359159861,"usOut":1761890359159993,"usDiff":132,"testnet":false}
Deribit wss://www.deribit.com/ws/api/v2: Sending message: {"jsonrpc":"2.0","id":"019a38d9-573d-709f-aff8-388dbbcacded","method":"public/get_instrument","params":{"instrument_name":"ETH-26DEC25-5200-C"}}
Deribit wss://www.deribit.com/ws/api/v2: Received response [1/1]: {"jsonrpc":"2.0","id":"019a38d9-56e3-709f-a54f-026a6b4ae82d","result":{"price_index":"btc_usdc","kind":"option_combo","instrument_name":"BTC_USDC-CCAL-7NOV25_31OCT25-114000","maker_commission":0.0,"taker_commission":0.0,"instrument_type":"linear","expiration_timestamp":1761897600000,"creation_timestamp":1761739148000,"is_active":true,"contract_size":1.0,"tick_size":5.0,"instrument_id":541707,"min_trade_amount":0.01,"settlement_currency":"USDC","settlement_period":"month","base_currency":"BTC","counter_currency":"USDC","quote_currency":"USDC","tick_size_steps":[]},"usIn":1761890359210269,"usOut":1761890359210512,"usDiff":243,"testnet":false}
Deribit wss://www.deribit.com/ws/api/v2: Sending message: {"jsonrpc":"2.0","id":"019a38d9-576f-709f-8b86-59d94a2333a3","method":"public/get_instrument","params":{"instrument_name":"BTC_USDC"}}
Deribit wss://www.deribit.com/ws/api/v2: Received response [1/1]: {"jsonrpc":"2.0","id":"019a38d9-5717-709f-9e1c-073fe890d076","result":{"price_index":"btc_usd","kind":"future","instrument_name":"BTC-PERPETUAL","maker_commission":0.0,"taker_commission":0.0005,"instrument_type":"reversed","expiration_timestamp":32503708800000,"creation_timestamp":1534242287000,"is_active":true,"contract_size":10.0,"tick_size":0.5,"instrument_id":210838,"min_trade_amount":10.0,"future_type":"reversed","max_leverage":50,"max_liquidation_commission":0.0075,"block_trade_commission":2.5e-4,"block_trade_min_trade_amount":200000,"block_trade_tick_size":0.01,"settlement_currency":"BTC","settlement_period":"perpetual","base_currency":"BTC","counter_currency":"USD","quote_currency":"USD","tick_size_steps":[]},"usIn":1761890359260189,"usOut":1761890359260352,"usDiff":163,"testnet":false}
Deribit wss://www.deribit.com/ws/api/v2: Received response [1/1]: {"jsonrpc":"2.0","id":"019a38d9-573d-709f-aff8-388dbbcacded","result":{"price_index":"eth_usd","kind":"option","instrument_name":"ETH-26DEC25-5200-C","maker_commission":0.0003,"taker_commission":0.0003,"instrument_type":"reversed","expiration_timestamp":1766736000000,"creation_timestamp":1754576100000,"is_active":true,"option_type":"call","contract_size":1.0,"tick_size":0.0001,"strike":5.2e3,"instrument_id":496820,"min_trade_amount":1,"block_trade_commission":0.0003,"block_trade_min_trade_amount":250,"block_trade_tick_size":0.0001,"settlement_currency":"ETH","settlement_period":"month","base_currency":"ETH","counter_currency":"USD","quote_currency":"ETH","tick_size_steps":[{"tick_size":0.0005,"above_price":0.005}]},"usIn":1761890359313070,"usOut":1761890359313221,"usDiff":151,"testnet":false}
Deribit wss://www.deribit.com/ws/api/v2: Received response [1/1]: {"jsonrpc":"2.0","id":"019a38d9-576f-709f-8b86-59d94a2333a3","result":{"price_index":"btc_usdc","kind":"spot","instrument_name":"BTC_USDC","maker_commission":0.0,"taker_commission":0.0,"instrument_type":"linear","expiration_timestamp":32503708800000,"creation_timestamp":1682341202000,"is_active":true,"contract_size":0.0001,"tick_size":1.0,"instrument_id":254613,"min_trade_amount":0.0001,"block_trade_commission":0.0,"block_trade_min_trade_amount":1,"block_trade_tick_size":1.0,"base_currency":"BTC","counter_currency":"USDC","quote_currency":"USDC","tick_size_steps":[]},"usIn":1761890359360273,"usOut":1761890359360396,"usDiff":123,"testnet":false}
--- FAIL: TestWSRetrieveInstrumentData (0.00s)
    --- FAIL: TestWSRetrieveInstrumentData/future_combo_ETH-USDC-FS-28NOV25_PERP (0.12s)
        deribit_test.go:568: 
            	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:568
            	Error:      	Received unexpected error:
            	            	code: -32602 message: Invalid params {"param":"instrument_name","reason":"wrong format"}
            	Test:       	TestWSRetrieveInstrumentData/future_combo_ETH-USDC-FS-28NOV25_PERP
--- FAIL: TestGetBookSummaryByInstrument (0.00s)
    --- FAIL: TestGetBookSummaryByInstrument/ETH-USDC-FS-28NOV25_PERP (0.15s)
        deribit_test.go:325: 
            	Error Trace:	/Users/runner/work/gocryptotrader/gocryptotrader/exchanges/deribit/deribit_test.go:325
            	Error:      	Received unexpected error:
            	            	Deribit unsuccessful HTTP status code: 400 raw response: {"jsonrpc":"2.0","error":{"code":-32602,"data":{"reason":"wrong format","param":"instrument_name"},"message":"Invalid params"},"testnet":false,"usIn":1761890359569655,"usOut":1761890359569721,"usDiff":66}
            	Test:       	TestGetBookSummaryByInstrument/ETH-USDC-FS-28NOV25_PERP
            	Messages:   	GetBookSummaryByInstrument must not error
FAIL
coverage: 48.1% of statements
FAIL	github.com/thrasher-corp/gocryptotrader/exchanges/deribit	12.846s
```

### PR DESCRIPTION
**Pull request by thrasher-**
# PR Description

Adds a futureComboPairToString func similar to the others, removes redundant endpoints and fixes related tests

Fixes #2099 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: exchanges/deribit/deribit.go [hunk 1]
```diff
@@ -292,17 +292,6 @@ func (e *Exchange) GetHistoricalVolatility(ctx context.Context, ccy currency.Cod
...
 
-// GetCurrencyIndexPrice retrieves the current index price for the instruments, for the selected currency.
-func (e *Exchange) GetCurrencyIndexPrice(ctx context.Context, ccy currency.Code) (*IndexPrice, error) {
-	if ccy.IsEmpty() {
-		return nil, currency.ErrCurrencyCodeEmpty
-	}
-	params := url.Values{}
-	params.Set("currency", ccy.String())
-	var resp *IndexPrice
-	return resp, e.SendHTTPRequest(ctx, exchange.RestFutures, nonMatchingEPL, common.EncodeURLValues(getCurrencyIndexPrice, params), &resp)
```
Comment (shazbert) [inline exchanges/deribit/deribit.go:303]: getCurrencyIndexPrice const can be removed

**Review by shazbert — CHANGES_REQUESTED** [review]
One minor thing. Then this looks good.

File: exchanges/deribit/deribit.go [hunk 2]
```diff
@@ -2727,3 +2715,19 @@ func optionComboPairToString(pair currency.Pair) string {
 	// * length == 4 with USDC as second token)
 	return parts[0] + "_" + strings.Join(parts[1:], "-")
 }
+
+// futureComboPairToString formats a future combo pair to deribit request format
+// e.g. ETH-USDC-FS-28NOV25_PERP -> ETH_USDC-FS-28NOV25_PERP (linear)
+// e.g. BTC-FS-28NOV25_PERP -> BTC-FS-28NOV25_PERP (inverse, unchanged)
+func futureComboPairToString(pair currency.Pair) string {
```
Comment (gloriousCode) [inline exchanges/deribit/deribit.go:2722]: Hello human fellow. I have enlisted the aid of our robot ~masters~ friends to make this more efficient. May it bring you ~infinite compute~ happiness

```go

func futureComboPairToStringByAI(pair currency.Pair) string {
	p := pair.String()
	if len(p) == 0 {
		return p
	}
	// Fast path: need at least "BASE-USDC-..." and the base must be followed by '-'
	// Find first dash to separate BASE
	firstDash := -1
	for i := 0; i < len(p); i++ {
		if p[i] == '-' {
			firstDash = i
			break
		}
	}
	if firstDash <= 0 || firstDash+1 >= len(p) {
		// No delimiter or nothing after it; cannot be a combo needing underscore
		return p
	}
	// Verify second token is USDC: expect "-USDC-" right after first dash
	// Ensure we have room for "-USDC-"
	const usdcDelim = "-USDC-"
	if firstDash+len(usdcDelim) > len(p) {
		return p
	}
	if p[firstDash:firstDash+len(usdcDelim)] != usdcDelim {
		// Second token is not USDC; inverse combo or non-combo -> unchanged
		return p
	}
	// Replace the first '-' with '_' to insert underscore after base.
	// This is equivalent to "BASE-USDC-..." -> "BASE_USDC-..."
	// Avoid extra allocations by building result with exact capacity (+1 not needed, same length).
	var b strings.Builder
	b.Grow(len(p))
	b.WriteString(p[:firstDash])
	b.WriteByte('_')
	b.WriteString(p[firstDash+1:])
	return b.String()
}

```

My benchmarking
```go
func BenchmarkFutureComboPairToString(b *testing.B) {
	b.Run("spotTradablePair", func(b *testing.B) {
		b.RunParallel(func(pb *testing.PB) {
			for pb.Next() {
				_ = futureComboPairToString(spotTradablePair)
			}
		})
	})
	b.Run("futureComboTradablePair", func(b *testing.B) {
		b.RunParallel(func(pb *testing.PB) {
			for pb.Next() {
				_ = futureComboPairToString(futureComboTradablePair)
			}
		})
	})
}

func BenchmarkFutureComboPairToStringByAI(b *testing.B) {
	b.Run("AIspotTradablePair", func(b *testing.B) {
		b.RunParallel(func(pb *testing.PB) {
			for pb.Next() {
				_ = futureComboPairToStringByAI(spotTradablePair)
			}
		})
	})
	b.Run("AIfutureComboTradablePair", func(b *testing.B) {
		b.RunParallel(func(pb *testing.PB) {
			for pb.Next() {
				_ = futureComboPairToStringByAI(futureComboTradablePair)
			}
		})
	})
}
```

The results:

| Benchmark | N | ns/op | B/op | allocs/op |
|---|---:|---:|---:|---:|
| `BenchmarkFutureComboPairToString/spotTradablePair-10` | 83604164 | 13.98 | 24 | 2 |
| `BenchmarkFutureComboPairToString/futureComboTradablePair-10` | 29402456 | 40.56 | 96 | 3 |
| `BenchmarkFutureComboPairToStringByAI/AIspotTradablePair-10` | 172946692 | 7.928 | 8 | 1 |
| `BenchmarkFutureComboPairToStringByAI/AIfutureComboTradablePair-10` | 100000000 | 11.22 | 24 | 1 |


If the function is too unreadable, I'm happy to keep your version

Comment (thrasher-) [reply exchanges/deribit/deribit.go:2722]: Nice! Have a similar version but a bit more compacted with similar allocs/perf

Comment (gloriousCode) [reply exchanges/deribit/deribit.go:2722]: The robots will remember this
