### PR TITLE
kraken: handle authenticated websocket subscriptions without pairs

### LINKED ISSUE #1930: Kraken: Investigate ws auth subs issue
Auth subs are currently failing
```
[ERROR] | WEBSOCKET | 29/05/2025 09:39:33 | subscription failure: buffer size must be positive; Channel: myTrades Pair: [], buffer size must be positive; Channel: myOrders Pair: []
```

_Originally posted by @shazbert in https://github.com/thrasher-corp/gocryptotrader/pull/1926#pullrequestreview-2876699934_

### PR DESCRIPTION
**Pull request by thrasher-**
Fixes #1930.

Kraken authenticated websocket channels such as `myTrades` / `myOrders` (`ownTrades` / `openOrders`) do not include pairs, but the current subscribe path still waits for `len(s.Pairs)` responses and later assumes subscription status payloads always contain a `pair`, which can fail with `buffer size must be positive`.

This change:
- waits for one response when subscribing to authenticated no-pair channels
- validates no-pair subscription responses without trying to parse a pair
- falls back to channel-only matching in `wsProcessSubStatus` when Kraken omits `pair`

Validation:
- `go test ./exchanges/kraken -count=1`
- `golangci-lint run --verbose ./exchanges/kraken/...`
- `codespell` on touched files

### CODE REVIEW

**Comment by thrasher-** [comment]
@codex please review

File: exchanges/kraken/kraken_websocket.go [hunk 1]
```diff
@@ -792,6 +796,16 @@ func (e *Exchange) manageSubs(ctx context.Context, op string, subs subscription.
...
 	reqFmt := currency.PairFormat{Uppercase: true, Delimiter: "/"}
 
+	if len(s.Pairs) == 0 {
+		var errs error
+		for _, resp := range resps {
+			if err := e.getSubRespErr(resp, op); err != nil {
+				errs = common.AppendError(errs, fmt.Errorf("%w; Channel: %s", err, s.Channel))
+			}
+		}
+		return errs
```
Comment (shazbert) [inline exchanges/kraken/kraken_websocket.go]: There should only be one response here, we can return an error when the len of resps != 1 and then `return e.getSubRespErr(resp, op)`

File: exchanges/kraken/kraken_test.go [hunk 2]
```diff
@@ -1129,6 +1132,71 @@ func TestWsOwnTradesSub(t *testing.T) {
...
+	} {
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+
+			ex := new(Exchange)
+			require.NoError(t, testexch.Setup(ex), "Setup Instance must not error")
+			s := &subscription.Subscription{Channel: tc.channel, QualifiedChannel: tc.qualifiedChannel, Authenticated: true}
+			require.NoError(t, ex.Websocket.AddSubscriptions(nil, s), "authenticated subscription must be added in subscribing state")
+
+			ex.wsProcessSubStatus([]byte(`{"channelName":"` + tc.qualifiedChannel + `","event":"subscriptionStatus","status":"subscribed","subscription":{"name":"` + tc.qualifiedChannel + `"}}`))
```
Comment (shazbert) [inline exchanges/kraken/kraken_test.go]: `{"channelName":"ownTrades","event":"subscriptionStatus","reqid":3,"status":"subscribed","subscription":{"name":"ownTrades"}}`

There is a request ID being returned that seems to not be available here. Shame there is a race mentioned in the commentary where we could match directly. But that is out of scope.

File: exchanges/kraken/kraken_websocket.go (hunk 1 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/f8f62ede06c191b380e241a467ddcafce4f29d61 — pairless auth subs now require exactly one subscription response, so we fail fast if Kraken returns 0/multiple responses instead of iterating a slice that should only contain one entry. I also added regression coverage for the zero-response path.

File: exchanges/kraken/kraken_test.go (hunk 2 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_test.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/f8f62ede06c191b380e241a467ddcafce4f29d61 — added `reqid` to the authenticated subscription-status fixtures so they match the real payload shape more closely. Agreed the broader reqid/matching race is pre-existing and out of scope for this PR.

File: exchanges/kraken/kraken_websocket.go [hunk 3]
```diff
@@ -797,13 +797,13 @@ func (e *Exchange) handleSubResps(s *subscription.Subscription, resps [][]byte,
 	reqFmt := currency.PairFormat{Uppercase: true, Delimiter: "/"}
 
 	if len(s.Pairs) == 0 {
-		var errs error
-		for _, resp := range resps {
-			if err := e.getSubRespErr(resp, op); err != nil {
-				errs = common.AppendError(errs, fmt.Errorf("%w; Channel: %s", err, s.Channel))
-			}
+		if len(resps) != 1 {
+			return fmt.Errorf("expected 1 subscription response; got %d; Channel: %s", len(resps), s.Channel)
```
Comment (shazbert) [inline exchanges/kraken/kraken_websocket.go]: should use sentinel errors so that appropriate ErrorIs matching used.

Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/9428502496783b8ca1cbf939eaa5cfc0caaecf1a — switched the pairless response-count error to a sentinel-wrapped form so callers/tests can use ErrorIs instead of brittle string matching. The regression test now asserts both ErrorIs(errExpectedOneSubResponse) and the contextual count/channel text.

File: exchanges/kraken/kraken_test.go [hunk 4]
```diff
@@ -1129,6 +1132,89 @@ func TestWsOwnTradesSub(t *testing.T) {
 	assert.Empty(t, e.Websocket.GetSubscriptions(), "Should have successfully removed channel")
 }
 
+type mockAuthSubConnection struct {
+	websocket.Connection
+	responses [][]byte
+	expected  int
+}
+
+func (m *mockAuthSubConnection) SendMessageReturnResponses(_ context.Context, _ request.EndpointLimit, _, _ any, expected int) ([][]byte, error) {
```
Comment (gloriousCode) [inline exchanges/kraken/kraken_test.go]: Update to `TestManageSubs` and then use t.Run scenarios, sharing some setup between them

Can optionally be placed in `kraken_websocket_test.go` (You'll need to make it)

File: exchanges/kraken/kraken_websocket.go [hunk 5]
```diff
@@ -903,18 +910,25 @@ func (e *Exchange) wsProcessSubStatus(resp []byte) {
...
 	}
-	key := &subscription.Subscription{
-		// We don't use asset because it's either Empty or Spot, but not both
-		Channel: c,
-		Pairs:   currency.Pairs{pair},
+
+	keySub := &subscription.Subscription{Channel: c}
+	lookupKey := any(subscription.ChannelKey{Subscription: keySub})
+	pName, err := jsonparser.GetUnsafeString(resp, "pair")
+	if err == nil {
```
Comment (gloriousCode) [inline exchanges/kraken/kraken_websocket.go]:
```
if pName, err := jsonparser.GetUnsafeString(resp, "pair");  err == nil {
```
pName only used within if.

File: exchanges/kraken/kraken_websocket.go [hunk 6]
```diff
@@ -903,18 +910,25 @@ func (e *Exchange) wsProcessSubStatus(resp []byte) {
...
+		pair, err := currency.NewPairFromString(pName)
+		if err != nil {
+			return
```
Comment (gloriousCode) [inline exchanges/kraken/kraken_websocket.go:920]:
```suggestion
			log.Errorf(log.ExchangeSys, "%s error parsing websocket subscription pair %q: %s from message: %s", e.Name, pName, pErr, resp)
			return
```

File: exchanges/kraken/kraken_test.go (hunk 4 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_test.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/98fd1064881f87e0c088a7c9cd6e7a7ec13fd2d1 — I moved the authenticated no-pair manageSubs coverage into websocket-focused tests and folded it into TestManageSubs with t.Run scenarios/shared setup, keeping the success and single-response error paths together.

File: exchanges/kraken/kraken_websocket.go (hunk 5 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/98fd1064881f87e0c088a7c9cd6e7a7ec13fd2d1 — inlined the websocket pair lookup into the conditional since it’s only used there.

File: exchanges/kraken/kraken_websocket.go (hunk 6 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go:920]: Jarvis: Updated in https://github.com/thrasher-/gocryptotrader/commit/98fd1064881f87e0c088a7c9cd6e7a7ec13fd2d1 — applied the suggested parse-failure log/return path and added direct regression coverage to ensure an invalid websocket pair leaves the subscription state unchanged.

File: exchanges/kraken/kraken_test.go (hunk 4 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_test.go]: Jarvis: Correction — the reachable commit is https://github.com/thrasher-/gocryptotrader/commit/98fd10648ece1b134a12070a23808b4f62432eb8 (previous link had a bad SHA tail). The change summary above is otherwise unchanged.

File: exchanges/kraken/kraken_websocket.go (hunk 5 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go]: Jarvis: Correction — the reachable commit is https://github.com/thrasher-/gocryptotrader/commit/98fd10648ece1b134a12070a23808b4f62432eb8 (previous link had a bad SHA tail). The change summary above is otherwise unchanged.

File: exchanges/kraken/kraken_websocket.go (hunk 6 above)
Comment (thrasher-) [reply exchanges/kraken/kraken_websocket.go:920]: Jarvis: Correction — the reachable commit is https://github.com/thrasher-/gocryptotrader/commit/98fd10648ece1b134a12070a23808b4f62432eb8 (previous link had a bad SHA tail). The change summary above is otherwise unchanged.

**Review by gloriousCode — APPROVED** [review]
tACK!

**Comment by thrasher-** [comment]
image
🚀 All working!
