### PR TITLE
Config: Fix config version downgrade

### LINKED ISSUE #1769: Config Version Downgrade is irrational
_Originally posted by @gloriousCode in https://github.com/thrasher-corp/gocryptotrader/pull/1735#discussion_r1904882907_

# TL;DR

Config Downgrade is an irrational mess

# Problem

Downgrades are currently part of the usual upgrade path.
That's impossible. If the latest registered is less than the config version, there is no downgrade code available to run.
Additionally, downgrades need to stop *before* the target version.

# Solution
* Downgrades to a version need to be run on a branch that contains the existing current version
* Downgrades should not be invoked automatically
* Upgrade and Downgrade invoked from cmd/config should not use json marshalling, which will introduce stateful representation
* Upgrading to a specific version can be supported, but we won't ~brag about it~ highlight it specifically as a feature

### PR DESCRIPTION
**Pull request by gbjk**
* Config: Fix config version downgrade
* Config: Rename EncryptConfigFile to EncryptConfigData
* Config: Rename DecryptConfigFile to DecryptConfigData

Fixes #1769 and issue raised on #1735

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

### CODE REVIEW

**Comment by gbjk** [comment]
Pulling out the os.Exit and replacing with testable pathway.
Will push early tomorrow.

**Comment by gbjk** [comment]
That's better, and testable.
Ready for review.

File: cmd/config/config.go [hunk 1]
```diff
@@ -46,83 +49,59 @@ func main() {
...
-type encryptFunc func(string, []byte) ([]byte, error)
-
-func encryptWrapper(in, out string, key []byte, confirmKey bool, fn encryptFunc) error {
-	if len(key) == 0 {
-		var err error
-		if key, err = config.PromptForConfigKey(confirmKey); err != nil {
-			return err
+	switch cmd {
+	case "decrypt":
+		if data, err = jsonparser.Set(data, []byte("-1"), "encryptConfig"); err != nil {
```
Comment (shazbert) [inline cmd/config/config.go:75]: Suggestion: if its not encrypted it just adds this to the file and creates a new one, maybe in future error out on this case if its not encrypted.

**Review by shazbert — CHANGES_REQUESTED** [review]
Just one thing and a suggestion. Thanks you! 🙏

File: config/config.go [hunk 2]
```diff
@@ -1512,7 +1512,7 @@ func (c *Config) readConfig(d io.Reader) error {
 		}
 	}
 
-	if j, err = versions.Manager.Deploy(context.Background(), j); err != nil {
+	if j, err = versions.Manager.Deploy(context.Background(), j, -1); err != nil {
```
[the remark this answers is not in the document]
Comment (gbjk) [reply config/config.go]: Yeah, that's much better. Thanks.

Fixed https://github.com/gbjk/gocryptotrader/commit/c95defc82

File: cmd/config/config.go (hunk 1 above)
Comment (gbjk) [reply cmd/config/config.go:78]: Fixed https://github.com/gbjk/gocryptotrader/commit/7d0cb0e25

File: config/versions/versions.go [hunk 3]
```diff
@@ -59,7 +61,7 @@ type manager struct {
 var Manager = &manager{}
 
 // Deploy upgrades or downgrades the config between versions
-// version param -1 defaults to the latest version
+// version param LatestVersion defaults to the latest version
```
Comment (shazbert) [inline config/versions/versions.go:64]: revert?

**Review by shazbert — CHANGES_REQUESTED** [review]
Last thing on new changes and linter issue then looks good to go. Thanks!

File: config/versions/versions.go (hunk 3 above)
Comment (gbjk) [reply config/versions/versions.go]: No, this was deliberate. I think I can word it better though.

Fixed https://github.com/gbjk/gocryptotrader/commit/cc91852e0

**Comment by gbjk** [comment]
> Last thing on new changes and linter issue then looks good to go. Thanks!

Linter fixed :)

**Review by shazbert — APPROVED** [review]
tACK. Thank you.

File: cmd/config/config.go [hunk 4]
```diff
@@ -1,7 +1,7 @@
 package main
 
 import (
-	"errors"
+	"context"
```
Comment (gloriousCode) [inline cmd/config/config.go:4]: Have I done anything wrong?
```
config % go run . --edit --version=2 downgrade
GoCryptoTrader: config-helper tool

version in config file is higher than the latest available version ('99' > '2')
Switch back to the version of GoCryptoTrader containing config version '99' and run:
$ ./cmd/config downgrade 2 
Unable to downgrade config; Error: version in config file is higher than the latest available version
exit status 2
```

**Review by gloriousCode — APPROVED** [review]
tACK! tested both encrypted and unencrypted

😆 
```
go run . --edit --version=-21 downgrade
GoCryptoTrader: config-helper tool
2025/02/17 13:29:06 Running downgrade from config version 2
2025/02/17 13:29:06 Running downgrade from config version 1
2025/02/17 13:29:06 Running downgrade from config version 0
2025/02/17 13:29:06 Running downgrade from config version -1
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/thrasher-corp/gocryptotrader/config/versions.(*manager).Deploy(0x1029d4900, {0x1027f9b00, 0x1029fcbe0}, {0x14000400000, 0x757c6, 0x757c7}, 0xffffffffffffffeb)
	/Users/WIF/go/src/github.com/thrasher-corp/gocryptotrader/config/versions/versions.go:117 +0xd58
main.main()
	/Users/WIF/go/src/github.com/thrasher-corp/gocryptotrader/cmd/config/config.go:90 +0xa00
exit status 2
```

**Comment by gbjk** [comment]
@gloriousCode I know you didn't ask for it but ...

Fixed https://github.com/gbjk/gocryptotrader/commit/2184f0672

**Review by shazbert — APPROVED** [review]
tACK. Thanks!

**Review by thrasher- — CHANGES_REQUESTED** [review]
```
go run . upgrade --edit --in=../../config_example.json --out=../../config_example.json
GoCryptoTrader: config-helper tool
2025/02/19 17:30:43 Running upgrade to config version 0
2025/02/19 17:30:43 Running upgrade to config version 1
2025/02/19 17:30:43 Running upgrade to config version 2
2025/02/19 17:30:43 Version management finished
Success! File written to ../../config_example.json
```

```
go run . downgrade --version=1 --edit --in=../../config_example.json --out=../../config_example.json
GoCryptoTrader: config-helper tool
2025/02/19 17:31:12 Running downgrade from config version 2
2025/02/19 17:31:12 Version management finished
Success! File written to ../../config_example.json
```

Same above works for both an encrypted config!

An issue I found when testing this on a fresh config_example.json:

```
go run . downgrade --version=5 --edit --in=../../config_example.json --out=../../config_example.json
GoCryptoTrader: config-helper tool
2025/02/19 17:27:51 Running upgrade to config version 0
2025/02/19 17:27:51 Running upgrade to config version 1
2025/02/19 17:27:51 Running upgrade to config version 2
2025/02/19 17:27:51 Running upgrade to config version 3
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
github.com/thrasher-corp/gocryptotrader/config/versions.(*manager).Deploy(0xb30e80, {0x8ef1a0, 0xb784e0}, {0xc000380000, 0x32395, 0x32396}, 0x5)
       /go/src/github.com/thrasher-corp/gocryptotrader/config/versions/versions.go:117 +0x12cd
main.main()
        /go/src/github.com/thrasher-corp/gocryptotrader/cmd/config/config.go:94 +0xb52
exit status 2
```

At some point I want to add fuzzing to GCT, so this is a good thing to resolve even though it's a funny user request

**Comment by gbjk** [comment]
Thanks!

Fixed https://github.com/gbjk/gocryptotrader/commit/8b9dbe47f

**Review by thrasher- — APPROVED** [review]
tACK, thanks for fixing that!
