### PR TITLE
gateio: Update API fields due to widespread upgrade 

### LINKED ISSUE #2173: gateio: Fix TestUpdateOrderExecutionLimits failure
Automated CI failure report.

Details:
- Area: `gateio`
- Test: `TestUpdateOrderExecutionLimits`
- Error: `Messages: MinimumBaseAmount should be positive for JDON_USDT`
- Detected on latest master commit: https://github.com/thrasher-corp/gocryptotrader/commit/804ec7b39853f61c0179633451ea61aa056311b6
- Workflow run: https://github.com/thrasher-corp/gocryptotrader/actions/runs/21813668180
- Job: https://github.com/thrasher-corp/gocryptotrader/actions/runs/21813668180/job/62930812900

Log excerpt:
```text
2026-02-09T05:40:53.1155323Z --- FAIL: TestUpdateOrderExecutionLimits/usdtmarginedfutures (0.16s)
2026-02-09T05:38:47.7137982Z FAIL github.com/thrasher-corp/gocryptotrader/database/models/postgres 0.005s
2026-02-09T05:40:53.1155676Z gateio_test.go:2475:
2026-02-09T05:40:53.1155966Z Error Trace: /app/exchanges/gateio/gateio_test.go:2475
2026-02-09T05:40:53.1156278Z Error: "0" is not positive
2026-02-09T05:40:53.1156616Z Test: TestUpdateOrderExecutionLimits/usdtmarginedfutures
```

### PR DESCRIPTION
**Pull request by shazbert**
From article https://www.gate.com/announcements/article/48788 there is header context field switching as they upgrade their endpoints. 

- fix: update Gate.io websocket handling for size and amount conversions
- Added "X-Gate-Size-Decimal" header rest and websocket connection
- Updated futures and options processing to convert sizes and amounts to float64 where necessary.
- Ensured consistency in handling size and amount across various functions in the Gate.io exchange wrapper.

Closes #2173 

# PR Description

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by thrasher-** [comment]
@codex please review

File: exchanges/gateio/gateio.go [hunk 1]
```diff
@@ -933,6 +933,7 @@ func (e *Exchange) SendAuthenticatedHTTPRequest(ctx context.Context, ep exchange
 		headers["TIMESTAMP"] = strconv.FormatInt(timestamp.Unix(), 10)
 		headers["Accept"] = "application/json"
 		headers["SIGN"] = sig
+		headers["X-Gate-Size-Decimal"] = "1"
```
[the remark this answers is not in the document]
Comment (gloriousCode) [reply exchanges/gateio/gateio.go:936]: Not opposed to `"X-Gate-Size-Decimal"` being const. Not much for it either

File: exchanges/gateio/gateio_websocket.go [hunk 2]
```diff
@@ -91,7 +91,7 @@ func (e *Exchange) WsConnectSpot(ctx context.Context, conn websocket.Connection)
 	if err := e.CurrencyPairs.IsAssetEnabled(asset.Spot); err != nil {
 		return err
 	}
-	if err := conn.Dial(ctx, &gws.Dialer{}, http.Header{}); err != nil {
+	if err := conn.Dial(ctx, &gws.Dialer{}, http.Header{"X-Gate-Size-Decimal": []string{"1"}}); err != nil {
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_websocket.go]: For an update targetting 
> Gate will implement a phased upgrade for the USDT perpetual contract APIs

why are you updating spot websocket? I'm fine if its compatable, but please update the other connect funcs

File: exchanges/gateio/gateio_types.go [hunk 3]
```diff
@@ -496,8 +496,8 @@ type CurrencyPairDetail struct {
 	MinQuoteAmount  types.Number  `json:"min_quote_amount"`
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_types.go:496]: OOS: in validating things, we come across that the `Position` response is missing `trade_long_size` & `trade_short_size`

Comment (gloriousCode) [reply exchanges/gateio/gateio_types.go:496]: OOS: also missing `close_size` MyFuturesTrade and MyFuturesTradeTimeRange

Comment (gloriousCode) [reply exchanges/gateio/gateio_types.go:496]: OOS: missing `entry_size` from FuturesAutoDeleverage

File: exchanges/gateio/gateio_types.go [hunk 4]
```diff
@@ -760,26 +760,26 @@ type FuturesFundingRate struct {
...
+	LongShortTaker         types.Number `json:"lsr_taker"`
+	LongShortAccount       types.Number `json:"lsr_account"`
+	LongLiqSize            types.Number `json:"long_liq_size"`
+	ShortLiquidationSize   types.Number `json:"short_liq_size"`
+	OpenInterest           types.Number `json:"open_interest"`
+	ShortLiquidationUsd    types.Number `json:"short_liq_usd"`
+	MarkPrice              types.Number `json:"mark_price"`
+	TopLongShortSize       types.Number `json:"top_lsr_size"`
+	ShortLiquidationAmount types.Number `json:"short_liq_amount"`
+	LongLiquidiationAmount types.Number `json:"long_liq_amount"`
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_types.go]:
```suggestion
	LongLiquidationAmount types.Number `json:"long_liq_amount"`
```

File: exchanges/gateio/gateio.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (cranktakular) [reply exchanges/gateio/gateio.go:936]: Based on their plan, this won't change (outside of being rendered unnecessary). When also taking the short time horizon in mind, I think we shouldn't bother making it const.

File: exchanges/gateio/gateio_types.go [hunk 5]
```diff
@@ -496,8 +496,8 @@ type CurrencyPairDetail struct {
 	MinQuoteAmount  types.Number  `json:"min_quote_amount"`
 	MaxBaseAmount   types.Number  `json:"max_base_amount"`
 	MaxQuoteAmount  types.Number  `json:"max_quote_amount"`
-	AmountPrecision float64       `json:"amount_precision"`
-	PricePrecision  float64       `json:"precision"`
+	AmountPrecision types.Number  `json:"amount_precision"`
+	PricePrecision  types.Number  `json:"precision"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: Why do you believe that these fields need to be changed?

Neither the announcement nor the change log entry nor the endpoint description itself indicate that these fields would be sent as strings. Plus, they're integers representing the significant digits in order data, so I think they're best represented as uint8.

Similar concerns apply to the changes in PersonalTradingFee and SpotOrdersDetail (although this one may deserve a larger uint type).

File: exchanges/gateio/gateio_types.go [hunk 6]
```diff
@@ -633,7 +633,7 @@ type MarginCurrencyPairInfo struct {
 	ID             currency.Pair `json:"id"`
 	Base           currency.Code `json:"base"`
 	Quote          currency.Code `json:"quote"`
-	Leverage       float64       `json:"leverage"`
+	Leverage       types.Number  `json:"leverage"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:636]: Seems like this field is always returned as a string, so [going by our coding guidelines](https://github.com/thrasher-corp/gocryptotrader/blob/master/docs/CODING_GUIDELINES.md#type-usage), it should just be a float64 with a ",string" json tag.

This also applies to the changes in InsuranceBalance, LiquidationHistory, OptionAccount, ContractClosePosition, FuturesSubAccountBalance, WsFuturesTrades, and WsFuturesOrderbookTicker.

File: exchanges/gateio/gateio_types.go [hunk 7]
```diff
@@ -760,26 +760,26 @@ type FuturesFundingRate struct {
...
+	ShortLiquidationSize   types.Number `json:"short_liq_size"`
+	OpenInterest           types.Number `json:"open_interest"`
+	ShortLiquidationUsd    types.Number `json:"short_liq_usd"`
+	MarkPrice              types.Number `json:"mark_price"`
+	TopLongShortSize       types.Number `json:"top_lsr_size"`
+	ShortLiquidationAmount types.Number `json:"short_liq_amount"`
+	LongLiquidiationAmount types.Number `json:"long_liq_amount"`
+	OpenInterestUsd        types.Number `json:"open_interest_usd"`
+	TopLongShortAccount    types.Number `json:"top_lsr_account"`
+	LongLiquidationUSD     types.Number `json:"long_liq_usd"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:782]: Both concerns I outlined above apply here. Based on [the exchange's documentation](https://www.gate.com/docs/developers/apiv4/en/#futures-statistics), only LongLiqSize, ShortLiquidationSize, OpeNInterest, MarkPrice, and TopLongShortSize are returned as strings. And, since it seems to only be used in this endpoint, they should consistently return "0" for zero, meaning that float64 with the ",string" tag would suffice.

And, as a bit out of scope, two of these names are inconsistent ("LongLiqSize" vs "ShortLiquidationSize").

File: exchanges/gateio/gateio_types.go [hunk 8]
```diff
@@ -838,13 +838,13 @@ type DeliveryContract struct {
...
-	OrderSizeMax        int64        `json:"order_size_max"`
+	OrderSizeMin        types.Number `json:"order_size_min"`
+	OrderSizeMax        types.Number `json:"order_size_max"`
 	OrdersLimit         int64        `json:"orders_limit"`
 	OrderbookID         int64        `json:"orderbook_id"`
 	TradeID             int64        `json:"trade_id"`
-	TradeSize           int64        `json:"trade_size"`
-	PositionSize        int64        `json:"position_size"`
+	TradeSize           types.Number `json:"trade_size"`
+	PositionSize        types.Number `json:"position_size"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:858]: This DeliveryContract type wasn't changed by this new regime. This endpoint wasn't mentioned in the announcement, the endpoint's documentation still shows these fields returning as integers, and while a similar type (Contract) was mentioned in their changelog, this endpoint's actual type (Deliverycontract) wasn't.

Although, I understand this is less certain than CurrencyPairDetail was.

File: exchanges/gateio/gateio_types.go [hunk 9]
```diff
@@ -867,21 +867,21 @@ type OptionContract struct {
...
-	OrderSizeMax      int64        `json:"order_size_max"`
+	MarkPriceRound    types.Number `json:"mark_price_round"`
+	MakerFeeRate      types.Number `json:"maker_fee_rate"`
+	TakerFeeRate      types.Number `json:"taker_fee_rate"`
+	PriceLimitFeeRate types.Number `json:"price_limit_fee_rate"`
+	RefDiscountRate   types.Number `json:"ref_discount_rate"`
+	RefRebateRate     types.Number `json:"ref_rebate_rate"`
+	OrderPriceDeviate types.Number `json:"order_price_deviate"`
+	OrderSizeMin      types.Number `json:"order_size_min"`
+	OrderSizeMax      types.Number `json:"order_size_max"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:895]: These changes from string > types.Number seem fine enough (although I'd say it would be better to do float64 with ",string" instead), but the changes to other parameters face the same issues as the changes in DeliveryContract.

Similar concerns apply to the changes in MyOptionSettlement.

File: exchanges/gateio/gateio_types.go [hunk 10]
```diff
@@ -923,10 +923,10 @@ type OptionsTicker struct {
 	Name                  currency.Pair `json:"name"`
 	LastPrice             types.Number  `json:"last_price"`
 	MarkPrice             types.Number  `json:"mark_price"`
-	PositionSize          float64       `json:"position_size"`
-	Ask1Size              float64       `json:"ask1_size"`
+	PositionSize          types.Number  `json:"position_size"`
+	Ask1Size              types.Number  `json:"ask1_size"`
 	Ask1Price             types.Number  `json:"ask1_price"`
-	Bid1Size              float64       `json:"bid1_size"`
+	Bid1Size              types.Number  `json:"bid1_size"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:940]: These fields aren't indicated to be returned as strings, not in the announcement, changelog, nor in the documentation for the relevant endpoint.

Also, slightly out of scope, the Vega, Theta, Rho, Gamma, and Delta fields for this endpoint seem like they could be done as float64 with ",strong" json tags.

File: exchanges/gateio/gateio_types.go [hunk 11]
```diff
@@ -944,8 +944,8 @@ type OptionsTicker struct {
 
 // OptionsUnderlyingTicker represents underlying ticker
 type OptionsUnderlyingTicker struct {
-	TradePut   float64      `json:"trade_put"`
-	TradeCall  float64      `json:"trade_call"`
+	TradePut   types.Number `json:"trade_put"`
+	TradeCall  types.Number `json:"trade_call"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:959]: These fields aren't indicated to be returned as strings, not in the announcement, changelog, nor in the documentation for the relevant endpoint.

Similar concerns apply to the changes in UsersPositionForUnderlying, OptionOrderParam, OptionOrderResponse, OptionTradingHistory, FuturesInitial, SettlementHistoryItem, WsPositionClose, WsBalance, WsFuturesReduceRiskLimitNotification, WsOptionsTrades, WsOptionsUnderlyingPrice, WsOptionsMarkPrice, WsOptionsSettlement, WsOptionsContractCandlestick, WsOptionsOrderbookTicker, WsOptionsOrderbookSnapshot, WsOptionsOrder, WsOptionsUserTrade, WsOptionsLiquidates, WsOptionsUserSettlement, and WsOptionsPosition.

File: exchanges/gateio/gateio_types.go [hunk 12]
```diff
@@ -1825,7 +1824,7 @@ type DualModeResponse struct {
 }
 
 // number represents a number type for JSON marshaling with zero value as "0"
-type number float64
+type number types.Number
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: This change seems unnecessary.

Although, to be fair, this marshaller was unnecessary in the first place. float64 using the ",string" json tag marshals a value of 0 to the string "0".

File: exchanges/gateio/gateio_types.go [hunk 13]
```diff
@@ -1834,8 +1833,8 @@ func (n number) MarshalJSON() ([]byte, error) {
 // ContractOrderCreateParams represents future order creation parameters
 type ContractOrderCreateParams struct {
 	Contract                  currency.Pair `json:"contract"`
-	Size                      float64       `json:"size"`    // positive long, negative short
-	Iceberg                   int64         `json:"iceberg"` // required; can be zero
+	Size                      types.Number  `json:"size"`    // positive long, negative short
+	Iceberg                   types.Number  `json:"iceberg"` // required; can be zero
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: This change seems like it should break outgoing requests.

This struct is currently used for PlaceFuturesOrder, PlaceBatchFuturesOrders, and PlaceDeliveryOrder. The last of those needs Size and Iceberg to lack speech marks, while the first two require speech marks to be present.

If live testing finds out that both work anyway, feel free to keep this. But otherwise, I think this will need to be split out into two types in order for it to work properly.

File: exchanges/gateio/gateio_types.go [hunk 14]
```diff
@@ -1898,7 +1897,7 @@ type LiquidationHistoryItem struct {
 	FillPrice  types.Number `json:"fill_price"`
 	LiqPrice   types.Number `json:"liq_price"`
 	OrderID    int64        `json:"order_id"`
-	Left       int64        `json:"left"`
+	Left       types.Number `json:"left"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: A bit out of scope, our name for Left here could change to RemainingAmount, to be consistent with how we represent that field in other types.

File: exchanges/gateio/gateio_types.go [hunk 15]
```diff
@@ -1940,7 +1939,7 @@ type FuturesTrigger struct {
 type PriceTriggeredOrder struct {
 	Initial struct {
 		Contract string       `json:"contract"`
-		Size     float64      `json:"size"`
+		Size     types.Number `json:"size"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2029]: According to the announcement, this object wasn't updated by changing the type of this field, rather it was changed by adding a new field "amount" which has the string type.

However, I can't see that reflected in the documentation or changelogs (there it just seems like this object was unchanged), so you may want to double-check before acting on this.

File: exchanges/gateio/gateio_types.go [hunk 16]
```diff
@@ -2295,24 +2294,24 @@ type WsFuturesOrderbookUpdateEvent struct {
...
+	Price        types.Number  `json:"price"`
 	Refr         int64         `json:"refr"`
 	Refu         int64         `json:"refu"`
-	Size         float64       `json:"size"`
+	Size         types.Number  `json:"size"`
 	Status       string        `json:"status"`
 	Text         string        `json:"text"`
 	TimeInForce  string        `json:"tif"`
-	Tkfr         float64       `json:"tkfr"`
+	Tkfr         types.Number  `json:"tkfr"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: Within this type, I think you converted too many fields to types.Number (and that those converted fields should've just been given ",string" json tags, instead).

Based on the announcement, changelog, and documentation, it seems like out of the ones you changed, only Iceberg, Left, and Size are now returned as strings.

File: exchanges/gateio/gateio_types.go [hunk 17]
```diff
@@ -2322,60 +2321,60 @@ type WsFuturesUserTrade struct {
 	CreateTime types.Time    `json:"create_time_ms"`
 	Contract   currency.Pair `json:"contract"`
 	OrderID    string        `json:"order_id"`
-	Size       float64       `json:"size"`
+	Size       types.Number  `json:"size"`
 	Price      types.Number  `json:"price"`
 	Role       string        `json:"role"`
 	Text       string        `json:"text"`
-	Fee        float64       `json:"fee"`
+	Fee        types.Number  `json:"fee"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2391]: Similar to above, it seems like Size is returned as a string, and that it could be safely represented with just a ",string" json tag, while Fee is still returned as a number.

File: exchanges/gateio/gateio_types.go [hunk 18]
```diff
@@ -2322,60 +2321,60 @@ type WsFuturesUserTrade struct {
...
+	Leverage   types.Number `json:"leverage"`
+	LiqPrice   types.Number `json:"liq_price"`
+	Margin     types.Number `json:"margin"`
+	MarkPrice  types.Number `json:"mark_price"`
+	OrderID    int64        `json:"order_id"`
+	OrderPrice types.Number `json:"order_price"`
+	Size       types.Number `json:"size"`
+	Time       types.Time   `json:"time_ms"`
+	Contract   string       `json:"contract"`
+	User       string       `json:"user"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go]: Similar to above, out of the types you changed, only Left and Size seem to now be returned as strings, and they're safe to use the ",string" json tag for. 

Although, oddly enough, the changelog alone mentions an order_size field, which isn't present in the announcement or the documentation. You may want to do a live test to see what's up with that.

File: exchanges/gateio/gateio_types.go [hunk 19]
```diff
@@ -2322,60 +2321,60 @@ type WsFuturesUserTrade struct {
...
-	FillPrice    float64    `json:"fill_price"`
-	PositionSize int64      `json:"position_size"`
-	TradeSize    int64      `json:"trade_size"`
-	Time         types.Time `json:"time_ms"`
-	Contract     string     `json:"contract"`
-	User         string     `json:"user"`
+	EntryPrice   types.Number `json:"entry_price"`
+	FillPrice    types.Number `json:"fill_price"`
+	PositionSize types.Number `json:"position_size"`
+	TradeSize    types.Number `json:"trade_size"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2417]: Similar to above, I think only PositionSize and TradeSize should've been updated, and that both of those could suffice with a ",string" json tag.

File: exchanges/gateio/gateio_types.go [hunk 20]
```diff
@@ -2385,36 +2384,36 @@ type WsBalance struct {
...
+	Leverage           types.Number `json:"leverage"`
+	LeverageMax        types.Number `json:"leverage_max"`
+	LiqPrice           types.Number `json:"liq_price"`
+	MaintenanceRate    types.Number `json:"maintenance_rate"`
+	Margin             types.Number `json:"margin"`
+	Mode               string       `json:"mode"`
+	RealisedPnl        types.Number `json:"realised_pnl"`
+	RealisedPoint      types.Number `json:"realised_point"`
+	RiskLimit          types.Number `json:"risk_limit"`
+	Size               types.Number `json:"size"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2477]: Similarly to cases above, I believe that here only Size should've been changed, and that it could have been changed by simply adding a ",string" json tag.

File: exchanges/gateio/gateio_types.go [hunk 21]
```diff
@@ -2429,11 +2428,11 @@ type WsFuturesAutoOrder struct {
 	} `json:"trigger"`
 	Initial struct {
 		Contract     string       `json:"contract"`
-		Size         int64        `json:"size"`
+		Size         types.Number `json:"size"`
 		Price        types.Number `json:"price"`
 		TimeInForce  string       `json:"tif"`
 		Text         string       `json:"text"`
-		Iceberg      int64        `json:"iceberg"`
+		Iceberg      types.Number `json:"iceberg"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2498]: Based on the documentation's portrayal, I'd expect that these could be handled with ",string" json tags, rather than as types.Number types.

But I'd also want to add that the announcement and the changelog portray the update here differently from the documentation. The announcement says that the "size" field was kept intact, while a new "amount" field was added, and the changelog says that the (seemingly nonexistent) "position_size" and "trade_size" fields were affected. You may want to live test this to see what's up.

File: exchanges/gateio/gateio_types.go [hunk 22]
```diff
@@ -2464,73 +2463,73 @@ type WsOptionsTrades struct {
...
+	Price      types.Number `json:"price"`
+	UpdateTime types.Time   `json:"time_ms"`
 }
 
 // WsOptionsMarkPrice represents options mark price push data.
 type WsOptionsMarkPrice struct {
-	Contract   string     `json:"contract"`
-	Price      float64    `json:"price"`
-	UpdateTime types.Time `json:"time_ms"`
+	Contract   string       `json:"contract"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2544]: OOS, but told to leave it here since this will likely get merged first.

Our constant for this channel `optionsMarkPriceChannel` has a value different from the one in the documentation. We've got it as `options.mark_price` and they've got it as `options.mark_prices`. Please update our constant if it's wrong. If our constant's correct, consider adding a comment so this doesn't need to be reinvestigated in the future, i.e. `// Contrary to the documentation, this spelling is accepted by the API`

File: exchanges/gateio/gateio_types.go [hunk 23]
```diff
@@ -2464,73 +2463,73 @@ type WsOptionsTrades struct {
...
+	OrderPriceDeviate types.Number `json:"order_price_deviate"`
+	OrderPriceRound   types.Number `json:"order_price_round"`
+	OrderSizeMax      types.Number `json:"order_size_max"`
+	OrderSizeMin      types.Number `json:"order_size_min"`
+	OrdersLimit       types.Number `json:"orders_limit"`
+	RefDiscountRate   types.Number `json:"ref_discount_rate"`
+	RefRebateRate     types.Number `json:"ref_rebate_rate"`
+	StrikePrice       types.Number `json:"strike_price"`
+	Tag               string       `json:"tag"`
+	TakerFeeRate      types.Number `json:"taker_fee_rate"`
```
Comment (cranktakular) [inline exchanges/gateio/gateio_types.go:2587]: I think these fields were likely changed when they shouldn't have been. The example in the documentation shows all of these returned as numbers, however, the documentation also says that some of them are strings, so you may want to do a live test and see what gets returned.

**Review by cranktakular — CHANGES_REQUESTED** [review]
Got some changes I must request

File: exchanges/gateio/gateio_types.go (hunk 3 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:496]: FuturesAutoDeleverage, MyFuturesTrade and MyFuturesTradeTimeRange don't seem to have REST request functionality in GCT (or maybe I just can't see it).

File: exchanges/gateio/gateio_types.go (hunk 5 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go]: Changed them for consistency; unmarshalling a float to a float64, or types.Number is effectively the same (but slightly more performant to the types.Number). I can change these over to uint8 though.

File: exchanges/gateio/gateio_types.go (hunk 6 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:636]: Changed coding guidelines,` json ,string tags` add in reflection overhead and as such the types.Number should be used in all cases of that. Added some improvements for sub account balance.

File: exchanges/gateio/gateio_types.go (hunk 7 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:782]: Changed field. Updated coding guidelines.

File: exchanges/gateio/gateio_types.go (hunk 8 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:858]: Changed it because they might change it in the future, I could revert if you want but its still a negligible overhead.

File: exchanges/gateio/gateio_types.go (hunk 9 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:895]: Can revert but less work in future if exchange does shenanigans.

File: exchanges/gateio/gateio_types.go (hunk 10 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:940]: Faster using types.Number for strings. Standardised to types.Number.

File: exchanges/gateio/gateio_types.go (hunk 11 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:959]: I did a full standardisation, guidelines updated.

File: exchanges/gateio/gateio_types.go (hunk 12 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go]: removed

File: exchanges/gateio/gateio_types.go (hunk 13 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go]: Can't verify nice catch though, will split it out.

File: exchanges/gateio/gateio_types.go (hunk 15 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2029]: Cant test without doing a trigger order can circle back when that order is sent and response received. Keeping as is won't hurt it either.

File: exchanges/gateio/gateio_types.go (hunk 16 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go]: standardisation pass, code guidelines updated.

File: exchanges/gateio/gateio_types.go (hunk 17 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2391]: Faster using types.Number

File: exchanges/gateio/gateio_types.go (hunk 18 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go]: Faster using types.Number will update adhoc when I sub to that channel in the future.

File: exchanges/gateio/gateio_types.go (hunk 19 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2417]: standardisation/Faster using types.Number

File: exchanges/gateio/gateio_types.go (hunk 20 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2477]: standardisation/Faster using types.Number

File: exchanges/gateio/gateio_types.go (hunk 21 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2498]: I am not doing auto orders trading, when I do I will update.

File: exchanges/gateio/gateio_types.go (hunk 22 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2544]:
```
[DEBUG] | WEBSOCKET | 23/02/2026 15:44:46 | GateIO wss://op-ws.gateio.live/v4/ws: Sending message: {"time":1771821885,"id":8,"channel":"options.mark_prices","event":"subscribe","payload":["BTC_USDT-20260327-30000-P"]}
[DEBUG] | WEBSOCKET | 23/02/2026 15:44:46 | GateIO wss://op-ws.gateio.live/v4/ws: Received response [1/1]: {"time":1771821886,"id":8,"channel":"options.mark_prices","event":"subscribe","result":{"status":"success"}}
```

File: exchanges/gateio/gateio_types.go (hunk 23 above)
Comment (shazbert) [reply exchanges/gateio/gateio_types.go:2587]: They can stay as types.Number

File: exchanges/gateio/gateio.go [hunk 24]
```diff
@@ -3571,8 +3573,47 @@ func (e *Exchange) GetUserTransactionRateLimitInfo(ctx context.Context) ([]UserT
 	return resp, e.SendAuthenticatedHTTPRequest(ctx, exchange.RestSpot, spotAccountsEPL, http.MethodGet, "account/rate_limit", nil, nil, &resp)
 }
 
-// validate validates the ContractOrderCreateParams
-func (c *ContractOrderCreateParams) validate(isRest bool) error {
+// validate validates the FuturesOrderCreateParams
+func (c *FuturesOrderCreateParams) validate(isRest bool) error {
```
Comment (thrasher-) [inline exchanges/gateio/gateio.go:3577]: OOS but this is pretty much a clone of DeliveryOrderCreateParams so could be deduped

File: docs/CODING_GUIDELINES.md [hunk 25]
```diff
@@ -22,11 +22,9 @@ Refer to the [ADD_NEW_EXCHANGE.md](/docs/ADD_NEW_EXCHANGE.md) document for compr
 ### Type Usage
 
 - Use the most appropriate native Go types for struct fields:
-  - If the API returns numbers as strings, use float64 with the `json:",string"` tag.
-  - For timestamps, use `time.Time` if Go's JSON unmarshalling supports the format directly.
-- If native Go types are not supported directly, use the following built-in types:
-  - `types.Time` for Unix timestamps that require custom unmarshalling.
-  - `types.Number` for numerical float values where an exchange API may return either a `string` or `float64` value.
+  - If the API always returns a number as a bare JSON number, use `float64`.
+  - If the API returns a number as a quoted JSON string, or may return either a string or a bare number, use `types.Number` — **do not** use `float64` with the `json:",string"` tag.
```
Comment (thrasher-) [inline docs/CODING_GUIDELINES.md:26]: Great work on benchmarking this!

**Comment by thrasher-** [comment]
That dedupe cleanup! 🍆💦

File: exchanges/gateio/gateio_test.go [hunk 26]
```diff
@@ -3597,85 +3586,45 @@ func TestWebsocketSubmitOrders(t *testing.T) {
...
+		{contract: BTCUSDT, size: 1, timeInForce: iocTIF, text: "t-test", autoSize: "silly_billy", err: errInvalidAutoSize},
+		{contract: BTCUSDT, size: 1, timeInForce: iocTIF, text: "t-test", autoSize: "close_long", err: errInvalidOrderSize},
+		{contract: BTCUSDT, timeInForce: iocTIF, text: "t-test", autoSize: "close_long", isRest: true, err: errEmptyOrInvalidSettlementCurrency},
+		{contract: BTCUSDT, timeInForce: iocTIF, text: "t-test", autoSize: "close_long", settle: currency.NewCode("Silly"), err: errEmptyOrInvalidSettlementCurrency},
+		{contract: BTCUSDT, timeInForce: iocTIF, text: "t-test", autoSize: "close_long", settle: currency.USDT},
 	} {
-		payload, err := tc.number.MarshalJSON()
-		require.NoError(t, err, "MarshalJSON must not error")
-		assert.Equal(t, tc.expected, string(payload), "MarshalJSON should return expected value")
+		fp := &FuturesOrderCreateParams{
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_test.go]: t.Run
t.Parallel()

Comment (shazbert) [reply exchanges/gateio/gateio_test.go]: Could have given me a DIFF M8 rude!

Comment (shazbert) [reply exchanges/gateio/gateio_test.go]: [HOPE THIS SATISFIES!](https://github.com/thrasher-corp/gocryptotrader/pull/2158/commits/47b865297179ed8f7f9e82b95ade70bd6eccf6bc)

File: exchanges/gateio/gateio_test.go [hunk 27]
```diff
@@ -3597,85 +3586,55 @@ func TestWebsocketSubmitOrders(t *testing.T) {
...
-	t.Parallel()
+	// Test nil pointer cases separately since they can't be constructed from shared fields.
+	t.Run("nil-futures", func(t *testing.T) {
+		t.Parallel()
+		assert.ErrorIs(t, (*FuturesOrderCreateParams)(nil).validate(false), common.ErrNilPointer, "nil FuturesOrderCreateParams should error")
+	})
+	t.Run("nil-delivery", func(t *testing.T) {
+		t.Parallel()
+		assert.ErrorIs(t, (*DeliveryOrderCreateParams)(nil).validate(false), common.ErrNilPointer, "nil DeliveryOrderCreateParams should error")
+	})
```
Comment (thrasher-) [inline exchanges/gateio/gateio_test.go]:
```suggestion
	assert.ErrorIs(t, (*FuturesOrderCreateParams)(nil).validate(false), common.ErrNilPointer, "nil FuturesOrderCreateParams should error")
	assert.ErrorIs(t, (*DeliveryOrderCreateParams)(nil).validate(false), common.ErrNilPointer, "nil DeliveryOrderCreateParams should error")
```
Since these don't need to be parallelised

File: exchanges/gateio/gateio_test.go [hunk 28]
```diff
@@ -3597,85 +3586,55 @@ func TestWebsocketSubmitOrders(t *testing.T) {
...
+				Contract: tc.contract, Size: tc.size, TimeInForce: tc.timeInForce,
+				Text: tc.text, AutoSize: tc.autoSize, Settle: tc.settle,
+			}
+			assert.ErrorIsf(t, fp.validate(tc.isRest), tc.err, "FuturesOrderCreateParams validate should return expected error")
+
+			dp := &DeliveryOrderCreateParams{
+				Contract: tc.contract, Size: tc.size, TimeInForce: tc.timeInForce,
+				Text: tc.text, AutoSize: tc.autoSize, Settle: tc.settle,
+			}
+			assert.ErrorIsf(t, dp.validate(tc.isRest), tc.err, "DeliveryOrderCreateParams validate should return expected error")
```
Comment (thrasher-) [inline exchanges/gateio/gateio_test.go]:
```suggestion
			assert.ErrorIs(t, dp.validate(tc.isRest), tc.err, "DeliveryOrderCreateParams validate should return expected error")
```

File: exchanges/gateio/gateio_test.go [hunk 29]
```diff
@@ -3597,85 +3586,55 @@ func TestWebsocketSubmitOrders(t *testing.T) {
...
-		payload, err := tc.number.MarshalJSON()
-		require.NoError(t, err, "MarshalJSON must not error")
-		assert.Equal(t, tc.expected, string(payload), "MarshalJSON should return expected value")
+		t.Run(tc.name, func(t *testing.T) {
+			t.Parallel()
+			fp := &FuturesOrderCreateParams{
+				Contract: tc.contract, Size: tc.size, TimeInForce: tc.timeInForce,
+				Text: tc.text, AutoSize: tc.autoSize, Settle: tc.settle,
+			}
+			assert.ErrorIsf(t, fp.validate(tc.isRest), tc.err, "FuturesOrderCreateParams validate should return expected error")
```
Comment (thrasher-) [inline exchanges/gateio/gateio_test.go]:
```suggestion
			assert.ErrorIs(t, fp.validate(tc.isRest), tc.err, "FuturesOrderCreateParams validate should return expected error")
```
