### PR TITLE
Bitmex: Fix deprecated API endpoints and add config migration support

### LINKED ISSUE #1894: Bitmex: Investigate websocket connection issue
Bitmex has [deprecated the old multiplexing endpoint](https://blog.bitmex.com/api_announcement/api-update-remove-support-realtimemd/) as of 15th April.

At the very least, fix the test failure, but review the [new documentation on multiplexing](https://www.bitmex.com/app/wsAPI#Multiplexing) to see what we should implement in it's place.

We only moved to the realtimemd endpoint with #1586 in October 2024, and that was only for one use-case:
> * Bitmex: Handle subscription errors
>    This switches to multiplexing so that we know which errors belong to
>    which stream, particularly for the auth attempt

So we can regress the endpoint so long as we can handle associating responses

<details>
<summary>Example Test failure</summary>

[Seen here in our Unit Tests](https://github.com/thrasher-corp/gocryptotrader/actions/runs/14585580423/job/40910394904#step:11:243)

```
--- FAIL: TestSubscribe (0.61s)
    bitmex_test.go:1147: 
        	Error Trace:	/home/runner/work/gocryptotrader/gocryptotrader/internal/testing/exchange/exchange.go:195
        	            				/home/runner/work/gocryptotrader/gocryptotrader/exchanges/bitmex/bitmex_test.go:1147
        	Error:      	Received unexpected error:
        	            	Bitmex Error connecting Bitmex websocket connection: wss://www.bitmex.com/realtimemd &{503 Service Unavailable 503 HTTP/1.1 1 1 map[Alt-Svc:[h3=":443"; ma=86400] Cf-Cache-Status:[DYNAMIC] Cf-Ray:[9341d274eb10eaf0-ORD] Connection:[keep-alive] Content-Length:[19] Content-Type:[text/plain] Date:[Tue, 22 Apr 2025 02:51:55 GMT] Server:[cloudflare] Set-Cookie:[__cf_bm=UUGxx_gHGYRWuOOuNb9HMp1bYYo5HQGW5zYAWmzdu9I-1745290315-1.0.1.1-cM.GQak1x6gHa7ynVQctmUm9ni4A_1WP8o7oaVZ4dPht6CQK_hTzF3CPRX6_TeAfhzF98rD8aCfxsmsOs905qifti5I7IhATKX6LrCsH8pA; path=/; expires=Tue, 22-Apr-25 03:21:55 GMT; domain=.bitmex.com; HttpOnly; Secure; SameSite=None]] {0xc00251b200} 19 [] false false map[] 0xc000254640 <nil>} 503 Error: websocket: bad handshake
        	Test:       	TestSubscribe
        	Messages:   	WsConnect should not error
```
</details>

### PR DESCRIPTION
**Pull request by gbjk**
* Fix configured WS url ignored
* Fix user config for [deprecated www api sub-domain](https://blog.bitmex.com/api_announcement/change-of-websocket-endpoint/)
* Switch to `realtime` endpoint instead of [now deprecated realtimemd](https://blog.bitmex.com/api_announcement/api-update-remove-support-realtimemd/) and fix user config

Fixes #1894 

Whilst testing this manually I noticed authenticated WS is not working, and I noticed this error during cred validation:
`Bitmex unsuccessful HTTP status code: 400 raw response: {"error":{"message":"Body should not be included in a GET request.","name":"HTTPError"}}, authenticated request failed`

But I'll look into that separately.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: exchanges/bitmex/bitmex_websocket.go [hunk 1]
```diff
@@ -151,46 +128,47 @@ func (b *Bitmex) wsReadData() {
...
 		}
-		err = b.Websocket.Match.RequireMatchWithData(op+":"+streamID, msg)
+		return nil
+	case errMsg != "", success:
+		req, _, _, err := jsonparser.Get(respRaw, "request")
 		if err != nil {
-			return fmt.Errorf("%w: %s:%s", err, op, streamID)
+			return err
+		}
+		if err := b.Websocket.Match.RequireMatchWithData(string(req), respRaw); err != nil {
```
Comment (shazbert) [inline exchanges/bitmex/bitmex_websocket.go:152]: cool 😎

**Review by shazbert — APPROVED** [review]
Nothing from me; didn't test auth don't have keys. But this works well and master does not and is super sad. tACK.

File: exchanges/bitmex/bitmex_websocket.go [hunk 2]
```diff
@@ -151,46 +128,47 @@ func (b *Bitmex) wsReadData() {
...
+			return err
+		}
+
+		if b.Verbose {
+			log.Debugf(log.ExchangeSys, "%s successfully connected to websocket API at time: %s Limit: %d", b.Name, welcomeResp.Timestamp, welcomeResp.Limit.Remaining)
 		}
-		err = b.Websocket.Match.RequireMatchWithData(op+":"+streamID, msg)
+		return nil
+	case errMsg != "", success:
+		req, _, _, err := jsonparser.Get(respRaw, "request")
```
Comment (thrasher-) [inline exchanges/bitmex/bitmex_websocket.go:148]:
```suggestion
		var req any
		if op == "authKeyExpires" {
			req = op
		} else {
			reqBytes, _, _, err := jsonparser.Get(respRaw, "request")
			if err != nil {
				return err
			}
			req = string(reqBytes)
		}
		if err := b.Websocket.Match.RequireMatchWithData(req, respRaw); err != nil {
			return fmt.Errorf("%w: %s", err, op)
		}
		return nil
```

Since we explicitly set the match sig to be `authKeyExpires` and therefore need this logic to match it correctly

**Review by thrasher- — CHANGES_REQUESTED** [review]
Thanks for looking into this! Tests are happy again. Just one issue

File: exchanges/bitmex/bitmex_websocket.go (hunk 2 above)
Comment (gbjk) [reply exchanges/bitmex/bitmex_websocket.go]: Agreed. At first I thought we would treat it the same, but the Arguments are obviously sensitive.
Thanks for the suggestion!

Fixed https://github.com/gbjk/gocryptotrader/commit/91cf3d7f7f

**Comment by gbjk** [comment]
🔂 Squashed down already

**Review by thrasher- — APPROVED** [review]
Changes made result in a happy bing, nice work!🌞
