### PR TITLE
accounts: Move to instance methods, fix races and isolate tests

### LINKED ISSUE #1902: Bybit: Investigate TestPushData failure
Test failure Error: `cannot update balance for .spot.USDC out of sequence, cannot update balance for .spot.USDT out of sequence
`
<details>
<summary>Failure Details</summary>

```
Bybit exchange websocket ToRoutine channel buffer full; dropping messages
Bybit - [missing data between 2023-08-24 15:03:00 and 2023-08-24 15:04:00]
--- FAIL: TestPushData (0.00s)
    bybit_test.go:3230: 
        	Error Trace:	/home/runner/work/gocryptotrader/gocryptotrader/exchanges/bybit/bybit_test.go:3230
        	Error:      	Received unexpected error:
        	            	cannot update balance for .spot.USDC out of sequence, cannot update balance for .spot.USDT out of sequence
        	Test:       	TestPushData
        	Messages:   	wsHandleData should not error
```
</details>

Seen in [this CI run](https://github.com/thrasher-corp/gocryptotrader/actions/runs/14926487990/job/41932452598?pr=1901#step:11:539)

### PR DESCRIPTION
**Pull request by gbjk**
This PR moves the account service from being a global instance with package functions to being an instance pattern with an optional global instance. Most methods for accounts move to the exchange interface, since all account updates would require a working exchange.

Fixes #1902 ; The original motivation for this PR was to fix races on Bybit.

Also addresses issues with when running tests with -count=N+ where we need to be more careful about the implications of `init` functions.
Reduces boilerplate and complexity in all exchanges when interacting with exchanges.

* `exchanges/account` ➡️ `exchange/accounts`
* exchange interface
  * `UpdateAccountInfo`  ➡️ `UpdateAccountBalances`  
  * `GetCachedAccountInfo` ➡️ `GetCachedSubAccounts`
  * ⭐ `SubscribeAccountBalances`
  * ⭐ `GetCachedCurrencyBalances`
* Add `Accounts` to exchange base
* Replace global service proxy methods with instance methods
  * `account.Process` ➡️  `e.Accounts.Save`
  * `account.ProcessChange` ➡️ `e.Accounts.Update`
* Accounts api changes:
  * `Service` ➡️  `store`
  * Protect `account.global` with atomic.Pointer
  * `NewStore` and `GetStore`
  * `NewAccounts` and `MustNewAccounts`
  * `account.SubscribeToExchangeAccount` ➡️ `e.SubscribeAccountBalanc`
  * `a.Subscribe` also available on the Account instance
  * `account.GetExchangeAccounts` ➡️ `account.GetStore().GetExchangeAccounts`
  * ⭐ `a.CurrencyBalances`
  * ⭐ `a.SubAccounts`
  * `account.GetBalance` ➡️ `account.GetStore().GetBalance`
  * `service.Save` ➡️ `Accounts.Save`
  * `service.Update` ➡️ `Accounts.Update`
  * `SubAccounts` and `s.Merge`
  * `CurrencyBalances` with `b.Add` and `b.Set`
  * All updates to accounts can be monitored through Subscribe, replacing the complexity of protected balances
* Deprecated apiserver:
  * Remove `AllEnabledAccountInfo`
  * Update docs to harden warnings now time has passed
* rpcserver:
  * `GetAccountInfo` ➡️ `GetAccountBalances` 
  * `UpdateAccountInfo` ➡️ `UpdateAccountBalances`
  * `GetAccountInfoStream ` ➡️ `GetAccountBalancesStream`
* Dispatcher changes:
  * Start global dispatcher in exchange wrapper tests
  * Make `dispatcher. ErrDispatcherAlreadyRunning` public
  * Use `common.ErrNilPointer` for dispatcher and mux

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Breaking change

### CODE REVIEW

File: exchanges/account/account.go [hunk 1]
```diff
@@ -37,29 +31,65 @@ var (
...
 )
 
-// initAccounts adds a new empty shared account accounts entry for an exchange
-// must be called with s.mu locked
-func (s *Service) initAccounts(exch string) (*Accounts, error) {
-	id, err := s.mux.GetID()
+var global atomic.Pointer[Store]
+
+// NewStore returns a new store with the default global dispatcher mux
+func NewStore() *Store {
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/account/account.go]: Actually, I already had, and accidentally didn't push.

Fixed https://github.com/gbjk/gocryptotrader/commit/d6ad5ac68

**Comment by gbjk** [comment]
Considering options for map of exchange pointers, after discussing with shazbert

File: exchanges/account/account.go [hunk 2]
```diff
@@ -37,29 +31,65 @@ var (
...
+// NewAccounts returns an initialized Accounts store for use in isolation from a global exchange accounts Store
+func NewAccounts(exchange string, mux *dispatch.Mux) (*Accounts, error) {
+	id, err := mux.GetID()
+	if err != nil {
+		return nil, err
 	}
-	accounts := &Accounts{
-		ID:          id,
+	return &Accounts{
+		Exchange:    strings.ToLower(exchange),
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/account/account.go]: Using instance methods throughout now, so this is resolved 👍

File: exchanges/account/account.go [hunk 3]
```diff
@@ -37,29 +31,65 @@ var (
...
+	if s := global.Load(); s != nil {
+		return s
+	}
+	_ = global.CompareAndSwap(nil, NewStore())
+	return global.Load()
+}
+
+// MustNewAccounts returns an initialized Accounts store for use in isolation from a global exchange accounts Store
+// Any errors in mux ID generation will panic, so users should balance risk vs utility accordingly depending on use-case
+func MustNewAccounts(eName string, mux *dispatch.Mux) *Accounts {
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/account/account.go]: Covered 🫳

File: exchanges/account/account.go [hunk 4]
```diff
@@ -37,29 +31,65 @@ var (
...
-// initAccounts adds a new empty shared account accounts entry for an exchange
-// must be called with s.mu locked
-func (s *Service) initAccounts(exch string) (*Accounts, error) {
-	id, err := s.mux.GetID()
+var global atomic.Pointer[Store]
+
+// NewStore returns a new store with the default global dispatcher mux
+func NewStore() *Store {
+	return &Store{
+		exchangeAccounts: make(map[string]*Accounts),
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/account/account.go]: Done 👍

File: exchanges/account/account_types.go [hunk 5]
```diff
@@ -13,39 +12,48 @@ import (
...
 
-// Vars for the ticker package
-var (
-	service                 Service
-	errAccountBalancesIsNil = errors.New("account balances is nil")
-)
-
-// Service holds ticker information for each individual exchange
-type Service struct {
+// Store holds ticker information for each individual exchange
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/account/account_types.go]: Seriously delayed gratification

Fixed gbjk@a3b3618b3

File: exchanges/exchange.go [hunk 6]
```diff
@@ -1922,17 +1929,22 @@ func (b *Base) GetCachedOrderbook(p currency.Pair, assetType asset.Item) (*order
...
+	return b.Accounts.GetHoldings(creds, assetType)
 }
 
 // WebsocketSubmitOrder submits an order to the exchange via a websocket connection
 func (*Base) WebsocketSubmitOrder(context.Context, *order.Submit) (*order.SubmitResponse, error) {
 	return nil, common.ErrFunctionNotSupported
 }
+
+// SubscribeAccountHoldings returns a pipe to stream account holding updates
+func (b *Base) SubscribeAccountHoldings() (dispatch.Pipe, error) {
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/exchange.go]: Covered 🫳

File: engine/rpcserver.go [hunk 7]
```diff
@@ -4810,24 +4757,23 @@ func (s *RPCServer) GetCollateral(ctx context.Context, r *gctrpc.GetCollateralRe
...
 			CalculateOffline:   r.CalculateOffline,
-			CollateralCurrency: acc.Currencies[i].Currency,
+			CollateralCurrency: curr,
 			Asset:              a,
 			FreeCollateral:     free,
 			LockedCollateral:   total.Sub(free),
 		}
 		if r.CalculateOffline &&
-			!acc.Currencies[i].Currency.Equal(currency.USD) {
+			!curr.Equal(currency.USD) {
```
Comment (shazbert) [inline engine/rpcserver.go]: can be on the line above

File: exchange/accounts/store.go [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+	_ = global.CompareAndSwap(nil, NewStore())
+	return global.Load()
+}
+
+// GetExchangeAccounts returns accounts for a specific exchange
+func (s *Store) GetExchangeAccounts(e exchange) (a *Accounts, err error) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+	if w, ok := e.(exchangeWrapper); ok {
+		// Because SetupDefualts is called on Base, it's easiest to just use the Base pointer as the key
```
Comment (shazbert) [inline exchange/accounts/store.go]: SetupDefualts -> SetupDefaults

File: exchange/accounts/balance_test.go [hunk 9]
```diff
@@ -0,0 +1,147 @@
...
+		Currency:  currency.LTC,
+		Total:     4.2,
+		UpdatedAt: n,
+	}}
+
+	_, err = b.update(Balance{})
+	require.ErrorIs(t, err, errUpdatedAtIsZero)
+
+	_, err = b.update(Balance{UpdatedAt: n, Currency: currency.ETH})
+	assert.ErrorIs(t, err, errBalanceCurrencyMismatch)
```
Comment (samuael) [inline exchange/accounts/balance_test.go:124]: require?

File: exchange/accounts/balance_test.go [hunk 10]
```diff
@@ -0,0 +1,147 @@
...
+
+	n = time.Now()
+	u, err := b.update(Balance{UpdatedAt: n, Total: 4.2})
+	assert.NoError(t, err, "should not error when Currency is empty")
+	assert.Equal(t, n, b.internal.UpdatedAt, "should update UpdatedAt")
+	assert.False(t, u, "should not be updated when nothing really changed")
+
+	n = time.Now()
+	u, err = b.update(Balance{UpdatedAt: n, Currency: currency.LTC, Total: 4.2})
+	assert.NoError(t, err, "should not error when Currency matches")
```
Comment (samuael) [inline exchange/accounts/balance_test.go]: require?

File: exchange/accounts/balance_test.go [hunk 11]
```diff
@@ -0,0 +1,147 @@
...
+	assert.Equal(t, n, b.internal.UpdatedAt, "should update UpdatedAt")
+	assert.False(t, u, "should return not updated when only time changed")
+
+	n = time.Now()
+	u, err = b.update(Balance{UpdatedAt: n, Currency: currency.LTC, Total: 4.4})
+	assert.NoError(t, err, "should not error when Currency matches")
```
Comment (samuael) [inline exchange/accounts/balance_test.go]: require? since the code below is using `u`

File: exchange/accounts/balance_test.go [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+
+	_, err = b.update(Balance{UpdatedAt: n, Currency: currency.ETH})
+	assert.ErrorIs(t, err, errBalanceCurrencyMismatch)
+
+	_, err = b.update(Balance{UpdatedAt: n})
+	assert.ErrorIs(t, err, errOutOfSequence, "should error when time out of sequence")
+
+	n = time.Now()
+	u, err := b.update(Balance{UpdatedAt: n, Total: 4.2})
+	assert.NoError(t, err, "should not error when Currency is empty")
```
Comment (samuael) [inline exchange/accounts/balance_test.go]: require? because `u` is used below

File: exchange/accounts/balance_test.go (hunk 9 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go:124]: Don't think so - because if this fails it doesn't stop any subsequent tests working, and it's not a showstopper.
So if this fails we also want to see subsequent failures :)

File: exchange/accounts/balance_test.go (hunk 10 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go]: Agreed, thanks 🙏 

Fixed gbjk@af76bc254

File: exchange/accounts/balance_test.go (hunk 11 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go]: Agreed, thanks 🙏 

Fixed gbjk@10ebbf38f

File: exchange/accounts/balance_test.go (hunk 12 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go]: Agreed, thanks 👍 

Fixed gbjk@dacecb036

File: engine/rpcserver.go [hunk 13]
```diff
@@ -557,87 +556,81 @@ func (s *RPCServer) GetOrderbooks(_ context.Context, _ *gctrpc.GetOrderbooksRequ
...
 	}
 
-	exch, err := s.GetExchangeByName(r.Exchange)
+	e, err := s.GetExchangeByName(r.Exchange)
 	if err != nil {
 		return nil, err
 	}
 
-	err = checkParams(r.Exchange, exch, assetType, currency.EMPTYPAIR)
+	err = checkParams(r.Exchange, e, assetType, currency.EMPTYPAIR)
```
Comment (samuael) [inline engine/rpcserver.go]: can shorten this to `if err := ` too

File: engine/rpcserver.go [hunk 14]
```diff
@@ -4766,42 +4738,17 @@ func (s *RPCServer) GetCollateral(ctx context.Context, r *gctrpc.GetCollateralRe
...
 	if !a.IsFutures() {
 		return nil, fmt.Errorf("%s %w", a, futures.ErrNotFuturesAsset)
 	}
-	ai, err := exch.GetCachedAccountInfo(ctx, a)
-	if err != nil {
-		return nil, err
-	}
-	creds, err := exch.GetCredentials(ctx)
+	currBalances, err := exch.GetCachedCurrencyBalances(ctx, a)
+	fmt.Println("", err, "")
```
Comment (samuael) [inline engine/rpcserver.go]: rm

File: engine/rpcserver_test.go [hunk 15]
```diff
@@ -391,22 +396,14 @@ func (f fExchange) CalculateTotalCollateral(context.Context, *futures.TotalColla
...
-		Exchange: f.GetName(),
-		Accounts: []account.SubAccount{
-			{
-				ID:         "1337",
-				AssetType:  a,
-				Currencies: nil,
-			},
-		},
-	}, nil
+	accts := accounts.SubAccounts{accounts.NewSubAccount(a, "1337")}
```
Comment (samuael) [inline engine/rpcserver_test.go]:
```suggestion
	return accounts.SubAccounts{accounts.NewSubAccount(a, "1337")}, nil
```

File: internal/testing/exchange/exchange.go [hunk 16]
```diff
@@ -47,11 +47,14 @@ func Setup(e exchange.IBotExchange) error {
...
-	if err != nil {
+
+	if err = e.Setup(exchConf); err != nil {
 		return fmt.Errorf("Setup() error: %w", err)
 	}
-	return nil
+
+	b.Accounts = accounts.MustNewAccounts(b)
+
+	return err
```
Comment (samuael) [inline internal/testing/exchange/exchange.go]: No need to return err here since it is checked above

File: backtester/funding/funding.go [hunk 17]
```diff
@@ -564,30 +564,22 @@ func (f *FundManager) UpdateFundingFromLiveData(initialFundsSet bool) error {
...
 			}
-			for z := range acc.Accounts {
-				if !acc.Accounts[z].Credentials.Equal(creds) {
-					continue
-				}
-				for i := range acc.Accounts[z].Currencies {
-					err = f.SetFunding(exchanges[x].GetName(), assets[y], &acc.Accounts[z].Currencies[i], initialFundsSet)
+			for _, subAcct := range subAccts {
+				for _, bal := range subAcct.Balances {
+					err = f.SetFunding(eName, a, &bal, initialFundsSet)
```
Comment (samuael) [inline backtester/funding/funding.go]: can make it into a single like 
```suggestion
					if err = f.SetFunding(eName, a, &bal, initialFundsSet); err != nil {
```

**Review by samuael — COMMENTED** [review]
Just left minor reviews

**Comment by gbjk** [comment]
I'm seeing [data races in this PR](https://github.com/gbjk/gocryptotrader/actions/runs/16468500028/job/46551654404#step:11:199), but I've sniffed them locally and I'm confident I didn't cause them.
They have [happened on other master runs of merged PRs](https://github.com/thrasher-corp/gocryptotrader/actions/runs/16259232574/job/45900962328#step:11:500) recently too.

I'll sniff them separately

File: currency/forexprovider/currencylayer/currencylayer_types.go [hunk 18]
```diff
@@ -24,7 +24,7 @@ const (
 
 // CurrencyLayer is a foreign exchange rate provider at
 // https://currencylayer.com NOTE default base currency is USD when using a free
-// account. Has automatic upgrade to a SSL connection.
+// accounts. Has automatic upgrade to a SSL connection.
```
Comment (shazbert) [inline currency/forexprovider/currencylayer/currencylayer_types.go]: revert

File: exchange/accounts/balance.go [hunk 19]
```diff
@@ -0,0 +1,169 @@
...
+
+// CurrencyBalances provides a map of currencies to balances
+type CurrencyBalances map[currency.Code]Balance
+
+// currencyBalances provides a map of currencies to balances
+type currencyBalances map[currency.Code]*balance
+
+// Set will set a currency balance, overwriting any previous Balance
+// currency may be a string or a currency.Code
+func (c *CurrencyBalances) Set(cAny any, b Balance) { //nolint:gocritic // hugeparam not relevant; we want to store a value so we'd deref anyway
```
Comment (shazbert) [inline exchange/accounts/balance.go]: Is there a problem just going = *b? Because I would just pass by ref here. It should inline anyways? And below

File: exchanges/binanceus/binanceus_test.go [hunk 20]
```diff
@@ -862,7 +860,7 @@ func TestCancelOpenOrdersForSymbol(t *testing.T) {
 }
 
 // TestGetTrades test for fetching the list of
-// trades attached with this account.
+// trades attached with this accounts.
```
Comment (shazbert) [inline exchanges/binanceus/binanceus_test.go]: revert

File: exchanges/binanceus/binanceus_types.go [hunk 21]
```diff
@@ -348,7 +348,7 @@ type AssetDistributionHistories struct {
 	Total uint64         `json:"total"`
 }
 
-// SubAccount  holds a single sub account instance in a Binance US account.
+// SubAccount  holds a single sub account instance in a Binance US accounts.
```
Comment (shazbert) [inline exchanges/binanceus/binanceus_types.go]: revert

File: exchanges/bitmex/bitmex_parameters.go [hunk 22]
```diff
@@ -1018,7 +1018,7 @@ type UserRequestWithdrawalParams struct {
 	// a chance to confirm this via email.
 	Fee float64 `json:"fee,omitempty"`
 
-	// OtpToken - 2FA token. Required if 2FA is enabled on your account.
+	// OtpToken - 2FA token. Required if 2FA is enabled on your accounts.
```
Comment (shazbert) [inline exchanges/bitmex/bitmex_parameters.go]: revert

File: exchanges/bitmex/bitmex_wrapper.go [hunk 23]
```diff
@@ -444,49 +444,24 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-func (e *Exchange) UpdateAccountInfo(ctx context.Context, assetType asset.Item) (account.Holdings, error) {
-	var info account.Holdings
-
+// UpdateAccountBalances retrieves balances for all enabled currencies for the Bitmex exchange
+func (e *Exchange) UpdateAccountBalances(ctx context.Context, assetType asset.Item) (accounts.SubAccounts, error) {
+	var subAccts accounts.SubAccounts
 	userMargins, err := e.GetAllUserMargin(ctx)
 	if err != nil {
-		return info, err
+		return subAccts, err
```
Comment (shazbert) [inline exchanges/bitmex/bitmex_wrapper.go]: can return `nil, error` and hug subAccts below

File: exchanges/bybit/bybit.go [hunk 24]
```diff
@@ -1323,7 +1323,7 @@ func (e *Exchange) GetFeeRate(ctx context.Context, category, symbol, baseCoin st
 	return resp, e.SendAuthHTTPRequestV5(ctx, exchange.RestSpot, http.MethodGet, "/v5/account/fee-rate", params, nil, &resp, getAccountFeeEPL)
 }
 
-// GetAccountInfo retrieves the margin mode configuration of the account.
+// GetAccountInfo retrieves the margin mode configuration of the accounts.
```
Comment (shazbert) [inline exchanges/bybit/bybit.go]: revert

File: exchanges/bybit/bybit.go [hunk 25]
```diff
@@ -1510,7 +1510,7 @@ func fillCoinBalanceFetchParams(accountType, memberID, coin string, withBonus in
 	return params, nil
 }
 
-// GetAllCoinBalance retrieves all coin balance of all account types under the master account, and sub account.
+// GetAllCoinBalance retrieves all coin balance of all account types under the master account, and sub accounts.
```
Comment (shazbert) [inline exchanges/bybit/bybit.go]: revert

File: exchanges/bybit/bybit.go [hunk 26]
```diff
@@ -2004,13 +2004,13 @@ func (e *Exchange) DeleteSubUID(ctx context.Context, subMemberID string) error {
 	return e.SendAuthHTTPRequestV5(ctx, exchange.RestSpot, http.MethodPost, "/v5/user/del-submember", nil, arg, &resp, defaultEPL)
 }
 
-// DeleteMasterAPIKey delete the api key of master account.
+// DeleteMasterAPIKey delete the api key of master accounts.
```
Comment (shazbert) [inline exchanges/bybit/bybit.go]: revert

File: exchanges/bybit/bybit.go [hunk 27]
```diff
@@ -2004,13 +2004,13 @@ func (e *Exchange) DeleteSubUID(ctx context.Context, subMemberID string) error {
...
 // Use the api key pending to be delete to call the endpoint. Use master user's api key only.
 func (e *Exchange) DeleteMasterAPIKey(ctx context.Context) error {
 	return e.SendAuthHTTPRequestV5(ctx, exchange.RestSpot, http.MethodPost, "/v5/user/delete-api", nil, nil, &struct{}{}, userDeleteAPIEPL)
 }
 
-// DeleteSubAccountAPIKey delete the api key of sub account.
+// DeleteSubAccountAPIKey delete the api key of sub accounts.
```
Comment (shazbert) [inline exchanges/bybit/bybit.go]: revert

File: exchanges/bybit/bybit_types.go [hunk 28]
```diff
@@ -907,7 +907,7 @@ type WalletBalance struct {
 	} `json:"list"`
 }
 
-// UnifiedAccountUpgradeResponse represents a response parameter for update to unified account.
+// UnifiedAccountUpgradeResponse represents a response parameter for update to unified accounts.
```
Comment (shazbert) [inline exchanges/bybit/bybit_types.go]: I think I will stop mentioning the reverts now but there is more.

**Review by shazbert — CHANGES_REQUESTED** [review]
Quick look over new changes. Thanks! Will deep dive next time.

File: engine/rpcserver.go (hunk 7 above)
Comment (gbjk) [reply engine/rpcserver.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/d7805a04f

File: exchange/accounts/store.go (hunk 8 above)
Comment (gbjk) [reply exchange/accounts/store.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/29aa1dcdc

File: currency/forexprovider/currencylayer/currencylayer_types.go (hunk 18 above)
Comment (gbjk) [reply currency/forexprovider/currencylayer/currencylayer_types.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/1ac97012a

Note: Also removes the comment `Has automatic upgrade to a SSL connection`

File: exchange/accounts/balance.go (hunk 19 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: In terms of coding intention and immutability, I want to use pass-by-value when it's "the right thing to do".

I flip-flopped on this several times and wrote it with a reference and without, before settling on this.
I triple checked it again before adding `nolint`, and even half switched it back to *Balance before reverting.
I Iooked at all the places that call this, in the exchanges, and it jusyt doesn't make sense to make them all pass a reference just to dereference it in the function.

File: exchanges/binanceus/binanceus_test.go (hunk 20 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/1066cef29

File: exchanges/binanceus/binanceus_types.go (hunk 21 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus_types.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/0ad3019b8

File: exchanges/bitmex/bitmex_parameters.go (hunk 22 above)
Comment (gbjk) [reply exchanges/bitmex/bitmex_parameters.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/f084edda3

File: exchanges/bitmex/bitmex_wrapper.go (hunk 23 above)
Comment (gbjk) [reply exchanges/bitmex/bitmex_wrapper.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/633e30f64

File: exchanges/bybit/bybit.go (hunk 24 above)
Comment (gbjk) [reply exchanges/bybit/bybit.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/7a8d4232b

File: exchanges/bybit/bybit.go (hunk 25 above)
Comment (gbjk) [reply exchanges/bybit/bybit.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/fa4276984

File: exchanges/bybit/bybit.go (hunk 26 above)
Comment (gbjk) [reply exchanges/bybit/bybit.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/fa4276984

File: exchanges/bybit/bybit.go (hunk 27 above)
Comment (gbjk) [reply exchanges/bybit/bybit.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/fa4276984

File: exchanges/bybit/bybit_types.go (hunk 28 above)
Comment (gbjk) [reply exchanges/bybit/bybit_types.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/ec9604b1d

Pretty sure that's all of them.
Sorry, I thought I'd caught them all previously.

File: exchanges/yobit/yobit_wrapper.go [hunk 29]
```diff
@@ -236,46 +236,26 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
 	}
-	err = account.Process(&response, creds)
-	if err != nil {
-		return account.Holdings{}, err
+	for curr, bal := range resp.Funds {
+		subAccts[0].Balances.Add(curr, accounts.Balance{
+			Free: bal,
+			Hold: -bal, // FundsInclOrders balance - Funds balance
+		})
 	}
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/yobit/yobit_wrapper.go]: This code is correct. The Hold is set to ` on the first pass at line 249 and then `Add` is used to update it here.
The comments should make that clear.

File: exchanges/yobit/yobit_wrapper.go [hunk 30]
```diff
@@ -236,46 +236,26 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-	err = account.Process(&response, creds)
-	if err != nil {
-		return account.Holdings{}, err
+	for curr, bal := range resp.Funds {
+		subAccts[0].Balances.Add(curr, accounts.Balance{
+			Free: bal,
+			Hold: -bal, // FundsInclOrders balance - Funds balance
+		})
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/yobit/yobit_wrapper.go]: The code is correct. The method being called is `Add`, not `Set`.

File: exchanges/poloniex/poloniex_wrapper.go [hunk 31]
```diff
@@ -340,39 +340,17 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, pair currency.Pair, asse
...
-	if err != nil {
-		return account.Holdings{}, err
+		return nil, err
 	}
-	err = account.Process(&response, creds)
-	if err != nil {
-		return account.Holdings{}, err
+	subAccts := accounts.SubAccounts{accounts.NewSubAccount(assetType, "")}
+	for curr, bal := range resp.Currency {
+		subAccts[0].Balances.Set(curr, accounts.Balance{Total: bal})
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/poloniex/poloniex_wrapper.go:350]: I'm going to call this out-of-scope, since we didn't do that before.
I'll raise an issue for it.

File: engine/rpcserver.go (hunk 13 above)
Comment (gbjk) [reply engine/rpcserver.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/dddfa4a50

File: engine/rpcserver.go (hunk 14 above)
Comment (gbjk) [reply engine/rpcserver.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/df4f9d3f1

File: engine/rpcserver_test.go (hunk 15 above)
Comment (gbjk) [reply engine/rpcserver_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/58ecafed2

File: internal/testing/exchange/exchange.go (hunk 16 above)
Comment (gbjk) [reply internal/testing/exchange/exchange.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/e1c73d2ec

File: backtester/funding/funding.go (hunk 17 above)
Comment (gbjk) [reply backtester/funding/funding.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/2e4899c03

File: internal/testing/exchange/exchange.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (gbjk) [reply internal/testing/exchange/exchange.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/e1c73d2ec

File: exchanges/bybit/bybit_types.go (hunk 28 above)
Comment (gbjk) [reply exchanges/bybit/bybit_types.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/0cd6dadb0

That one was a slippery bugger and nearly escaped the net.

**Comment by gbjk** [comment]
Will rebase once reviewers are happy to resolve the conflict on gateio_test.

File: exchange/accounts/balance.go [hunk 32]
```diff
@@ -0,0 +1,169 @@
...
+type balance struct {
+	internal Balance
+	m        sync.RWMutex
+}
+
+// CurrencyBalances provides a map of currencies to balances
+type CurrencyBalances map[currency.Code]Balance
+
+// currencyBalances provides a map of currencies to balances
+type currencyBalances map[currency.Code]*balance
```
Comment (shazbert) [inline exchange/accounts/balance.go]:
```suggestion
type currencyBalances map[*currency.Item]*balance
```

reduce chance that there is a upper/lower case duplication

File: exchange/accounts/accounts.go [hunk 33]
```diff
@@ -0,0 +1,305 @@
...
+func (l SubAccounts) clone() (c SubAccounts) {
+	for _, s := range l {
+		c = append(c, &SubAccount{
+			ID:        s.ID,
+			AssetType: s.AssetType,
+			Balances:  s.Balances.clone(),
+		})
+	}
+	return c
+}
```
Comment (shazbert) [inline exchange/accounts/accounts.go]: Shift to test file as its not being used in the package only test

File: exchange/accounts/balance.go [hunk 34]
```diff
@@ -0,0 +1,169 @@
...
+	return c[curr]
+}
+
+func (c CurrencyBalances) clone() CurrencyBalances {
+	n := make(CurrencyBalances, len(c))
+	for curr, bal := range c {
+		n[curr] = bal
+	}
+	return n
+}
```
Comment (shazbert) [inline exchange/accounts/balance.go]: RM and rm test as its only being used in the other `(l SubAccounts) clone()` func which isn't being used outside of a test.

File: exchange/accounts/store.go [hunk 35]
```diff
@@ -0,0 +1,76 @@
...
+// registerExchange adds a new empty shared account accounts entry for an exchange
+// must be called with s.mu locked
+func (s *Store) registerExchange(e exchange) (*Accounts, error) {
+	if _, ok := s.exchangeAccounts[e]; ok {
+		return nil, errExchangeAlreadyExists
+	}
+	a, err := NewAccounts(e, s.mux)
+	s.exchangeAccounts[e] = a
+	return a, err
+}
```
Comment (shazbert) [inline exchange/accounts/store.go]: not being used can be rm'd

File: exchange/accounts/balance.go (hunk 19 above)
Comment (shazbert) [reply exchange/accounts/balance.go]: It doesn't inline so you added in an extra allocation, if your okay with that I am okay with that. I don't see that as an issue.

File: exchange/accounts/balance.go [hunk 36]
```diff
@@ -0,0 +1,169 @@
...
+	default:
+		panic(fmt.Errorf("%w: '%v'", currency.ErrCurrencyNotSupported, cAny))
+	}
+	b.Currency = curr
+	(*c)[curr] = b
+}
+
+// Add will add to a currency balance
+// currency may be a string or a currency.Code
+func (c *CurrencyBalances) Add(cAny any, b Balance) { //nolint:gocritic // hugeparam not relevant; we want to store a value so we'd deref anyway
```
Comment (shazbert) [inline exchange/accounts/balance.go]: String case seems to only be used in Yobit, I would just forced `c currency.Code` and the burden is shifted to the caller. I would do that for Set as well. It just reduces complexity/panic potential.

**Review by shazbert — CHANGES_REQUESTED** [review]
Another quick review, there is a test failure in accounts as well.

File: gctscript/wrappers/validator/validator_test.go [hunk 37]
```diff
@@ -60,19 +60,19 @@ func TestWrapper_IsEnabled(t *testing.T) {
...
 	if err != nil {
 		t.Fatal(err)
 	}
 
-	_, err = testWrapper.AccountInformation(t.Context(),
+	_, err = testWrapper.AccountBalances(t.Context(),
 		exchError.String(), asset.Spot)
 	if err == nil {
-		t.Fatal("expected AccountInformation to return error on invalid name")
+		t.Fatal("expected AccountHoldings to return error on invalid name")
```
[the remark this answers is not in the document]
Comment (gbjk) [reply gctscript/wrappers/validator/validator_test.go]: Fixed with Driveby

Fixed https://github.com/gbjk/gocryptotrader/commit/4c9694df4

File: exchanges/yobit/yobit_wrapper.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/yobit/yobit_wrapper.go]: Already replied to this.
Attempted to add hints to make AI happy in the comments.

Fixed https://github.com/gbjk/gocryptotrader/commit/788381f9d

File: exchanges/huobi/huobi_wrapper.go [hunk 38]
```diff
@@ -654,161 +654,99 @@ func (e *Exchange) GetAccountID(ctx context.Context) ([]Account, error) {
...
 				} else {
-					currencyDetails = append(currencyDetails,
-						account.Balance{
-							Currency: currency.NewCode(balances[j].Currency),
-							Total:    balances[j].Balance,
-						})
+					a.Balances.Set(balances[j].Currency, accounts.Balance{Total: balances[j].Balance})
 				}
+				subAccts = subAccts.Merge(a)
 			}
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchanges/huobi/huobi_wrapper.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/6c78af99a

File: exchange/accounts/balance.go (hunk 32 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: I'm not sure about this, but I've done it anyway.
I've kept the public version as `Code` and used `Item` internally.
Initially I switched to both being `*Item` around but it didn't taste right.

Fixed https://github.com/gbjk/gocryptotrader/commit/28a4c7845

File: exchange/accounts/accounts.go (hunk 33 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/0c6835a26

File: exchange/accounts/balance.go (hunk 34 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/b0df20ba6

File: exchange/accounts/store.go (hunk 35 above)
Comment (gbjk) [reply exchange/accounts/store.go]: Interesting that the test had a require.*should that was somehow skipping hooks and lint.

Fixed https://github.com/gbjk/gocryptotrader/commit/ccf85f84b

File: exchange/accounts/balance.go (hunk 36 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: Agreed.
I'll also shift the other panic out to the callers.

Bit of a rabbit hole; At first I made all the callers use `currency.NewCode`, but actually they should be adjusting their data types, mostly.

Comment (gbjk) [reply exchange/accounts/balance.go]: Huge footprint for this change, unfortunately. This is why I allowed both for Set.
But at the same time, it's the right thing to do.
Not too hard to review, hopefully.
Haven't sniffed the test impact from this in entirety, will do so in the morning.

Fixed https://github.com/gbjk/gocryptotrader/commit/f067874bb

File: exchanges/binance/binance_wrapper.go [hunk 39]
```diff
@@ -2505,7 +2505,7 @@ func (e *Exchange) GetFuturesPositionSummary(ctx context.Context, req *futures.P
 		for i := range ai.Assets {
 			// TODO: utilise contract data to discern the underlying currency
 			// instead of having a user provide it
-			if ai.Assets[i].Asset != req.UnderlyingPair.Base.Upper().String() {
+			if !ai.Assets[i].Asset.Equal(req.UnderlyingPair.Base.Upper()) {
```
Comment (shazbert) [inline exchanges/binance/binance_wrapper.go]:
```suggestion
			if !ai.Assets[i].Asset.Equal(req.UnderlyingPair.Base) {
```

Comment (gbjk) [reply exchanges/binance/binance_wrapper.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/5fabed47e

Comment (gbjk) [reply exchanges/binance/binance_wrapper.go]: Since this was tiny, I'm going to rebase down now.

**Review by shazbert — CHANGES_REQUESTED** [review]
LGTM. 

There is some build test issue [here](https://github.com/thrasher-corp/gocryptotrader/actions/runs/17090954213/job/48464437030?pr=1923#step:11:3588) 

Could you please check out and also there is a bunch of races which are happening now. Might not be to do with this though. 🙇

**Comment by gbjk** [comment]
> Could you please check out and also there is a bunch of races which are happening now. Might not be to do with this though. 🙇

I already reviewed them, and concluded they weren't related to these changes.
However I'll run it a few more times to be sure.
Kinda feels like I'll have to *fix* the race just to be able to assert with confidence that I didn't cause it.

**Comment by gbjk** [comment]
@shazbert 
The [data race](https://github.com/thrasher-corp/gocryptotrader/actions/runs/17090954213/job/48638736513?pr=1923#step:11:2827) I'm seeing is because ExchangeManager's Shutdown is touching `m.exchanges` in a goro protected by a separate private mutex.
I don't see any link to the changes in this PR yet.
I can keep sniffing it, and re-running it.

File: engine/portfolio_manager.go [hunk 40]
```diff
@@ -124,152 +124,91 @@ func (m *portfolioManager) processPortfolio() {
...
-	for x := range exchanges {
-		if !exchanges[x].IsEnabled() {
-			continue
-		}
-		if !exchanges[x].IsRESTAuthenticationSupported() {
-			if m.base.Verbose {
-				log.Debugf(log.PortfolioMgr,
-					"skipping %s due to disabled authenticated API support.\n",
-					exchanges[x].GetName())
+// updateExchangeAddressBalances transfer exchange account balances into porpfolio addresses for exchanges
```
Comment (gloriousCode) [inline engine/portfolio_manager.go]:
```suggestion
// updateExchangeAddressBalances transfer exchange account balances into portfolio addresses for exchanges
```

File: cmd/gctcli/commands.go [hunk 41]
```diff
@@ -706,24 +706,24 @@ func getAccountInfoStream(c *cli.Context) error {
...
 		&cli.StringFlag{
 			Name:  "asset",
-			Usage: "the asset type to get the account info for",
+			Usage: "the asset type to get the account balances for",
 		},
 	},
 }
 
-func updateAccountInfo(c *cli.Context) error {
+func updateAccountBalances(c *cli.Context) error {
```
Comment (gloriousCode) [inline cmd/gctcli/commands.go:728]: So one of the things that GCT allows is for context based credentials. We can see this with the GCT CLI params --apikey="" --apisecret="". One can make requests of an exchange with credentials that aren't the ones in the config. For simplicity right now, this is relevant for an exchange like Kraken, whose futures and spot api keys are separate.

I'm early in my review process of understanding the scope of your change, but I thought it would be good to highlight the following output early on:
```
gctcli % go run . --apikey="hello" --apisecret="moto" updateaccountbalances --exchange="kraken" --asset="futures"
2025/09/03 14:27:19 rpc error: code = Unknown desc = error updating balance for account ID "fi_xbtusd" [futures xbt]: balance currency does not match update currency, error updating balance for account ID "fi_xrpusd" [futures xrp]: balance currency does not match update currency," 
...
and it does this across all futures currencies
```

On master I can store both spot and futures account info where I can no longer do so on your branch - at least in this manner.

Since I'm early on, I cannot yet tell if its a bug or that for credential's sake, we won't be able to use context api credentials as easily now because your keys are exchanges rather than api keys, but thought I would highlight it.

File: engine/portfolio_manager.go (hunk 40 above)
Comment (gbjk) [reply engine/portfolio_manager.go]: A portfolio of porpoises

Fixed https://github.com/gbjk/gocryptotrader/commit/0b92139f4

File: cmd/gctcli/commands.go (hunk 41 above)
Comment (gbjk) [reply cmd/gctcli/commands.go:728]: This isn't about credentials 😮‍💨 
It's just currency code case.
Tested manually and it's working for me.

Fixed https://github.com/gbjk/gocryptotrader/commit/ea50e0549

**Comment by thrasher-** [comment]
@codex please review

File: exchange/accounts/accounts.go [hunk 42]
```diff
@@ -0,0 +1,296 @@
...
+			if assetType != asset.All && assetType != subAcctKey.Asset {
+				continue
+			}
+			for curr, bal := range balances {
+				if err := currs.Add(curr.Currency(), bal.Balance()); err != nil {
+					return nil, err // Should be impossible, so return immediately
+				}
+			}
+		}
+	}
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchange/accounts/accounts.go:133]: @codex Thanks.

Fixed gbjk@617b4810a

File: exchange/accounts/accounts.go [hunk 43]
```diff
@@ -0,0 +1,296 @@
...
+		for subAcctKey, balances := range subAccountsForCreds {
+			if assetType != asset.All && assetType != subAcctKey.Asset {
+				continue
+			}
+			subAccts = append(subAccts, &SubAccount{
+				ID:        subAcctKey.SubAccount,
+				AssetType: subAcctKey.Asset,
+				Balances:  balances.Public(),
+			})
+		}
```
[the remark this answers is not in the document]
Comment (gbjk) [reply exchange/accounts/accounts.go:170]: @codex Thanks

Fixed gbjk@617b4810a

**Comment by gbjk** [comment]
I won't rebase this until @gloriousCode has re-reviewed 🙂

**Comment by gbjk** [comment]
Rebasing now, to fold in changes from 2011.

**Comment by thrasher-** [comment]
@codex please review

**Comment by gbjk** [comment]
@cranktakular I've rebased on your coinbase changes, and made [these fixes](https://github.com/gbjk/gocryptotrader/commit/56a889eed).
Just FYI; I'm sure you'd sniff it sooner or later.

File: exchange/accounts/store.go [hunk 44]
```diff
@@ -0,0 +1,62 @@
...
+	}
+	_ = global.CompareAndSwap(nil, NewStore())
+	return global.Load()
+}
+
+// GetExchangeAccounts returns accounts for a specific exchange
+func (s *Store) GetExchangeAccounts(e exchange) (a *Accounts, err error) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+	if w, ok := e.(exchangeWrapper); ok {
```
Comment (shazbert) [inline exchange/accounts/store.go:52]: suggestion: adding GetBase() to the exchange interface can probably just call below and rm this if check. 

```go
a, ok := s.exchangeAccounts[e.GetBase()]
```

File: exchanges/binance/binance.go [hunk 45]
```diff
@@ -845,17 +845,14 @@ func getOfflineTradeFee(price, amount float64) float64 {
 
 // getMultiplier retrieves account based taker/maker fees
 func (e *Exchange) getMultiplier(ctx context.Context, isMaker bool) (float64, error) {
```
Comment (shazbert) [inline exchanges/binance/binance.go:822]: suggestion/oos: this should be getTradeFee? it conflicts with contract multiplier.

File: exchanges/binanceus/binanceus_wrapper.go [hunk 46]
```diff
@@ -353,41 +353,26 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, pair currency.Pair, asse
 	return orderbook.Get(e.Name, pair, assetType)
 }
 
-// UpdateAccountInfo retrieves balances for all enabled currencies
-func (e *Exchange) UpdateAccountInfo(ctx context.Context, assetType asset.Item) (account.Holdings, error) {
-	var info account.Holdings
-	var acc account.SubAccount
-	info.Exchange = e.Name
+// UpdateAccountBalances retrieves balances for all enabled currencies
+func (e *Exchange) UpdateAccountBalances(ctx context.Context, assetType asset.Item) (accounts.SubAccounts, error) {
```
Comment (shazbert) [inline exchanges/binanceus/binanceus_wrapper.go:339]: 🍺 seems like we can probably embed binance.Exchange on this type and then override what we need cutting down on a bunch of code.

File: exchanges/bitflyer/bitflyer_wrapper.go [hunk 47]
```diff
@@ -241,10 +241,9 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
 	return orderbook.Get(e.Name, fPair, assetType)
 }
 
-// UpdateAccountInfo retrieves balances for all enabled currencies on the
-// Bitflyer exchange
-func (e *Exchange) UpdateAccountInfo(_ context.Context, _ asset.Item) (account.Holdings, error) {
-	return account.Holdings{}, common.ErrNotYetImplemented
+// UpdateAccountBalances retrieves balances for all enabled currencies on the Bitflyer exchange
```
Comment (shazbert) [inline exchanges/bitflyer/bitflyer_wrapper.go]:
```suggestion
// UpdateAccountBalances retrieves balances for all enabled currencies 
```

Don't need to add the exchange verbosity and standardise across exchanges.

File: exchanges/bitflyer/bitflyer_wrapper.go [hunk 48]
```diff
@@ -384,7 +383,7 @@ func (e *Exchange) GetFeeByType(ctx context.Context, feeBuilder *exchange.FeeBui
 // ValidateAPICredentials validates current credentials used for wrapper
 // functionality
 func (e *Exchange) ValidateAPICredentials(ctx context.Context, assetType asset.Item) error {
```
Comment (shazbert) [inline exchanges/bitflyer/bitflyer_wrapper.go:383]: 🍺 I think this might be better to be a base function that takes in (ctx, exchange, asset) so that it can be rm'd on the wrappers.

File: exchanges/bybit/bybit_mock_test.go [hunk 49]
```diff
@@ -57,3 +48,18 @@ func TestMain(m *testing.M) {
 
 	os.Exit(m.Run())
 }
+
+func testInstance() *Exchange {
```
Comment (shazbert) [inline exchanges/bybit/bybit_mock_test.go:52]: suggstion: might be able to collapse this func to bybit_test.go and do an if check on mockTests but up to you resolve/ignore on all my dweeby suggestions

File: exchanges/bybit/bybit_test.go [hunk 50]
```diff
@@ -3164,19 +3148,19 @@ func TestWSHandleAuthenticatedData(t *testing.T) {
 			assert.Equal(t, 0.3374, v[0].Price, "price should be correct")
 			assert.Equal(t, 25.0, v[0].Amount, "amount should be correct")
 		default:
-			t.Errorf("Unexpected data received: %v", v)
+			t.Errorf("Unexpected data received: %T %v", v, v)
```
Comment (shazbert) [inline exchanges/bybit/bybit_test.go:3155]: assert.Fail?

File: exchanges/coinut/coinut.go [hunk 51]
```diff
@@ -277,7 +277,7 @@ func (e *Exchange) SendHTTPRequest(ctx context.Context, ep exchange.URL, apiRequ
 
 		headers := make(map[string]string)
 		if authenticated {
-			var creds *account.Credentials
+			var creds *accounts.Credentials
 			creds, err = e.GetCredentials(ctx)
```
Comment (shazbert) [inline exchanges/coinut/coinut.go]:
```suggestion
			creds, err := e.GetCredentials(ctx)
```

File: exchanges/coinut/coinut_test.go [hunk 52]
```diff
@@ -347,12 +347,12 @@ func TestCancelAllExchangeOrders(t *testing.T) {
 func TestGetAccountInfo(t *testing.T) {
 	t.Parallel()
 	if apiKey != "" || clientID != "" {
-		_, err := e.UpdateAccountInfo(t.Context(), asset.Spot)
+		_, err := e.UpdateAccountBalances(t.Context(), asset.Spot)
 		if err != nil {
 			t.Error("GetAccountInfo() error", err)
 		}
```
Comment (shazbert) [inline exchanges/coinut/coinut_test.go]: suggestion: require.noerror and below

File: exchanges/credentials.go [hunk 53]
```diff
@@ -98,10 +98,10 @@ func (b *Base) AreCredentialsValid(ctx context.Context) bool {
 
 // GetDefaultCredentials returns the exchange.Base api credentials loaded by
 // config.json
-func (b *Base) GetDefaultCredentials() *account.Credentials {
+func (b *Base) GetDefaultCredentials() *accounts.Credentials {
 	b.API.credMu.RLock()
 	defer b.API.credMu.RUnlock()
-	if b.API.credentials == (account.Credentials{}) {
+	if b.API.credentials == (accounts.Credentials{}) {
```
Comment (shazbert) [inline exchanges/credentials.go:104]: suggestion we might be able to just rm this? or just check for key instead of allocating an empty struct.

File: exchanges/credentials.go [hunk 54]
```diff
@@ -110,12 +110,12 @@ func (b *Base) GetDefaultCredentials() *account.Credentials {
 
 // GetCredentials checks and validates current credentials, context credentials
 // override default credentials, if no credentials found, will return an error.
-func (b *Base) GetCredentials(ctx context.Context) (*account.Credentials, error) {
-	value := ctx.Value(account.ContextCredentialsFlag)
+func (b *Base) GetCredentials(ctx context.Context) (*accounts.Credentials, error) {
+	value := ctx.Value(accounts.ContextCredentialsFlag)
 	if value != nil {
-		ctxCredStore, ok := value.(*account.ContextCredentialsStore)
+		ctxCredStore, ok := value.(*accounts.ContextCredentialsStore)
```
Comment (shazbert) [inline exchanges/credentials.go:116]: suggestion: could rm this check as it should be set by the deploy func correctly

File: exchanges/exchange.go [hunk 55]
```diff
@@ -600,7 +600,15 @@ func (b *Base) SetupDefaults(exch *config.Exchange) error {
 		log.Warnf(log.ExchangeSys, "%s orderbook verification has been bypassed via config.", b.Name)
 	}
 
+	if b.Accounts == nil {
```
Comment (shazbert) [inline exchanges/exchange.go:603]: suggestion: I think we can just rm this check and flush this if set defaults is called again.

File: exchanges/hitbtc/hitbtc.go [hunk 56]
```diff
@@ -211,7 +211,7 @@ func (e *Exchange) GetBalances(ctx context.Context) (map[string]Balance, error)
 		url.Values{},
 		otherRequests,
 		&result)
-	ret := make(map[string]Balance)
+	ret := make(map[currency.Code]Balance)
```
Comment (shazbert) [inline exchanges/hitbtc/hitbtc.go]: can you please move this below the err check? Or even just change the func signature to return []Balance

File: exchanges/interfaces.go [hunk 57]
```diff
@@ -151,9 +152,11 @@ type CurrencyStateManagement interface {
 
 // AccountManagement defines functionality for exchange account management
 type AccountManagement interface {
```
Comment (shazbert) [inline exchanges/interfaces.go:154]: suggestion: Could have this interface in accounts?

File: exchanges/kraken/kraken_test.go [hunk 58]
```diff
@@ -729,17 +729,17 @@ func TestCancelAllExchangeOrders(t *testing.T) {
...
+func TestUpdateAccountBalances(t *testing.T) {
 	t.Parallel()
 
 	for _, a := range []asset.Item{asset.Spot, asset.Futures} {
-		_, err := e.UpdateAccountInfo(t.Context(), a)
+		_, err := e.UpdateAccountBalances(t.Context(), a)
 
 		if sharedtestvalues.AreAPICredentialsSet(e) {
-			assert.NoErrorf(t, err, "UpdateAccountInfo should not error for asset %s", a) // Note Well: Spot and Futures have separate api keys
+			assert.NoErrorf(t, err, "UpdateAccountBalances should not error for asset %s", a) // Note Well: Spot and Futures have separate api keys
```
Comment (shazbert) [inline exchanges/kraken/kraken_test.go:740]: 🍺 Is this comment valid anymore? 😆

File: exchanges/kraken/kraken_wrapper.go [hunk 59]
```diff
@@ -512,69 +512,46 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-				log.Warnf(log.ExchangeSys, "%s unable to translate currency: %s\n",
-					e.Name,
-					key)
+			return nil, err
+		}
+		subAccts = accounts.SubAccounts{accounts.NewSubAccount(assetType, "")}
+		for key, bal := range resp {
+			c := assetTranslator.LookupAltName(key)
+			if c == "" {
+				log.Warnf(log.ExchangeSys, "%s unable to translate currency: %s\n", e.Name, key)
```
Comment (shazbert) [inline exchanges/kraken/kraken_wrapper.go]:
```suggestion
				log.Warnf(log.ExchangeSys, "%s unable to translate currency: %s", e.Name, key)
```

File: exchanges/kucoin/kucoin_types.go [hunk 60]
```diff
@@ -763,12 +763,12 @@ type StopOrder struct {
...
 type AccountInfo struct {
-	ID          string       `json:"id"`
-	Currency    string       `json:"currency"`
-	AccountType string       `json:"type"` // Account type:，main、trade、trade_hf、margin
-	Balance     types.Number `json:"balance"`
-	Available   types.Number `json:"available"`
-	Holds       types.Number `json:"holds"`
+	ID          string        `json:"id"`
+	Currency    currency.Code `json:"currency"`
+	AccountType string        `json:"type"` // Account type:，main、trade、trade_hf、margin
```
Comment (shazbert) [inline exchanges/kucoin/kucoin_types.go]:
```suggestion
	AccountType string        `json:"type"` // Account type: main, trade, trade_hf, margin
```

File: exchanges/poloniex/poloniex.go [hunk 61]
```diff
@@ -263,7 +263,7 @@ func (e *Exchange) GetBalances(ctx context.Context) (Balance, error) {
 	}
 
 	balance := Balance{
-		Currency: make(map[string]float64),
+		Currency: make(map[currency.Code]float64),
```
Comment (shazbert) [inline exchanges/poloniex/poloniex.go]: suggestion: Could just return the map instead of Balance or even have an unmarshaller but out of scope and up to you

**Review by shazbert — CHANGES_REQUESTED** [review]
Good stuff just some suggestions and minor nits after looking over everything again. 🚀

File: exchange/accounts/store.go (hunk 44 above)
Comment (gbjk) [reply exchange/accounts/store.go:52]: I see what you mean; Calling `*Base.GetBase()` returns the `*Base` in exchange.go
I didn't spot that. It's a tiny bit more expensive, but I don't think this is a very hot path, and we're only called from a `Base` in SetupDefaults I think.

So yeah, I'll do that.

Fixed https://github.com/gbjk/gocryptotrader/commit/92571ecee

File: exchanges/binance/binance.go (hunk 45 above)
Comment (gbjk) [reply exchanges/binance/binance.go:822]: 🗻 **Way** out of scope; Feel free to check and raise an issue though.

File: exchanges/binanceus/binanceus_wrapper.go (hunk 46 above)
Comment (gbjk) [reply exchanges/binanceus/binanceus_wrapper.go:339]: 🥃 Cheers. I agree. Or wait 3 months and BinanceUS will disappear again and Binance will take over.
Either way ... 🗻 OOS.

File: exchanges/bitflyer/bitflyer_wrapper.go (hunk 47 above)
Comment (gbjk) [reply exchanges/bitflyer/bitflyer_wrapper.go]: Agreed. I've been drive by removing this.
Hitting Bitfinex at the same time

Fixed https://github.com/gbjk/gocryptotrader/commit/c4cc66c79

File: exchanges/bitflyer/bitflyer_wrapper.go (hunk 48 above)
Comment (gbjk) [reply exchanges/bitflyer/bitflyer_wrapper.go:383]: 🥃 Agreed, but also OOSing 🗻 
Really wanna get this across the line 😁

File: exchanges/bybit/bybit_mock_test.go (hunk 49 above)
Comment (gbjk) [reply exchanges/bybit/bybit_mock_test.go:52]: Close call, but I'll leave it for now 👍

File: exchanges/bybit/bybit_test.go (hunk 50 above)
Comment (gbjk) [reply exchanges/bybit/bybit_test.go:3155]: Doesn't *feel* like it's worth it 👍 
But I've never used assert.Fail before.

File: exchanges/coinut/coinut.go (hunk 51 above)
Comment (gbjk) [reply exchanges/coinut/coinut.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/8f79da1d7

File: exchange/accounts/store.go (hunk 44 above)
Comment (gbjk) [reply exchange/accounts/store.go:52]: Whoops, didn't spot the error for some reason:
```
 cannot use b (variable of type *Base) as accounts.exchange value in argument to accounts.GetStore().GetExchangeAccounts: *Base does not implement accounts.exchange (wrong type for method
 GetBase)
         have GetBase() *Base
         want GetBase() accounts.exchange [InvalidIfaceAssign]
```
There's no way around this that I can think of.
The signature for `GetBase()` has to match I think, if you're using it from outside.

Feel free to find a way, but I'll revert and move on for now.

Reverted: gbjk@01993450c

File: exchanges/coinut/coinut_test.go (hunk 52 above)
Comment (gbjk) [reply exchanges/coinut/coinut_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/c7997ce3d

File: exchanges/credentials.go (hunk 53 above)
Comment (gbjk) [reply exchanges/credentials.go:104]: I didn't sniff the credentials section too hard, and I'm not touching it now, because I know it'll unravel into a lot of changes. This PR is already way overdue and merge hell.

File: exchanges/credentials.go (hunk 54 above)
Comment (gbjk) [reply exchanges/credentials.go:116]: Also not touching this if I don't have to 😄

File: exchanges/exchange.go (hunk 55 above)
Comment (gbjk) [reply exchanges/exchange.go:603]: Pretty sure this was deliberately to allow for testing, etc.

File: exchanges/hitbtc/hitbtc.go (hunk 56 above)
Comment (gbjk) [reply exchanges/hitbtc/hitbtc.go]: Sure. But won't change method signature 🙂 

Fixed https://github.com/gbjk/gocryptotrader/commit/d5dd7134f

File: exchanges/interfaces.go (hunk 57 above)
Comment (gbjk) [reply exchanges/interfaces.go:154]: Could do, but not seeing a big benefit to setting a precedent like that here 🙂

File: exchanges/kraken/kraken_test.go (hunk 58 above)
Comment (gbjk) [reply exchanges/kraken/kraken_test.go:740]: 🥃  I think it is, yes. Pretty sure it hit me at some point recently.

File: exchanges/kraken/kraken_wrapper.go (hunk 59 above)
Comment (gbjk) [reply exchanges/kraken/kraken_wrapper.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/d4c832fce

File: exchanges/kucoin/kucoin_types.go (hunk 60 above)
Comment (gbjk) [reply exchanges/kucoin/kucoin_types.go]: WTF was that 😳 

Fixed https://github.com/gbjk/gocryptotrader/commit/5420328bd

File: exchanges/poloniex/poloniex.go (hunk 61 above)
Comment (gbjk) [reply exchanges/poloniex/poloniex.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/38f1f9df0

**Review by shazbert — APPROVED** [review]
Thanks heaps looking good! 🚀

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go [hunk 62]
```diff
@@ -143,6 +144,10 @@ assets:
 		})
 	}
 	assetPairs = append(assetPairs, assetPair{})
+
+	err = dispatch.EnsureRunning(dispatch.DefaultMaxWorkers, dispatch.DefaultJobsLimit)
```
Comment (gloriousCode) [inline cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go]: Why is this placed here? It has no requirements for it to be per exchange, but its called in a loop.
Call this before the loop eg
```go
func TestAllExchangeWrappers(t *testing.T) {
	t.Parallel()
	cfg := config.GetConfig()
	err := cfg.LoadConfig("../../testdata/configtest.json", true)
	if err != nil {
		t.Fatal("load config error", err)
	}
	err = dispatch.EnsureRunning(dispatch.DefaultMaxWorkers, dispatch.DefaultJobsLimit)
	require.NoError(t, err, "dispatch.EnsureRunning must not error")
```

File: engine/portfolio_manager.go [hunk 63]
```diff
@@ -124,152 +124,91 @@ func (m *portfolioManager) processPortfolio() {
...
-	for x := range exchanges {
-		if !exchanges[x].IsEnabled() {
-			continue
-		}
-		if !exchanges[x].IsRESTAuthenticationSupported() {
-			if m.base.Verbose {
-				log.Debugf(log.PortfolioMgr,
-					"skipping %s due to disabled authenticated API support.\n",
-					exchanges[x].GetName())
+// updateExchangeAddressBalances transfer exchange account balances into portfolio addresses for exchanges
```
Comment (gloriousCode) [inline engine/portfolio_manager.go]: This comment could be improved as it sounds as though it performs transferring of funds. Not a good word choice when dealing with user funds.
```
// updateExchangeAddressBalances fetches and collates all account balances with their deposit address
```

File: exchange/accounts/balance.go [hunk 64]
```diff
@@ -0,0 +1,139 @@
...
+}
+
+// CurrencyBalances provides a map of currencies to balances
+type CurrencyBalances map[currency.Code]Balance
+
+// currencyBalances provides a map of currencies to balances
+type currencyBalances map[*currency.Item]*balance
+
+// Set will set a currency balance, overwriting any previous Balance
+func (c *CurrencyBalances) Set(curr currency.Code, b Balance) { //nolint:gocritic // hugeparam not relevant; we want to store a value so we'd deref anyway
```
Comment (gloriousCode) [inline exchange/accounts/balance.go]: Why not pass by pointer, remove all these lints, and then copy across values and make that explicit then?
Its about how its copying all the currency info that makes it a huge param, not the floats

File: exchange/accounts/store.go [hunk 65]
```diff
@@ -0,0 +1,62 @@
...
+type exchange interface {
+	GetName() string
+	GetCredentials(context.Context) (*Credentials, error)
+}
+
+type exchangeWrapper interface {
+	GetBase() exchange
+}
+
+var global atomic.Pointer[Store]
```
Comment (gloriousCode) [inline exchange/accounts/store.go:29]: Not a nit, but while this looks cool, why would you use this over just a global *Store?

File: engine/websocketroutine_manager.go [hunk 66]
```diff
@@ -329,15 +329,9 @@ func (m *WebsocketRoutineManager) websocketDataHandler(exchName string, data any
...
+	case []accounts.Change, accounts.Change:
 		if m.verbose {
-			m.printAccountHoldingsChangeSummary(exchName, d)
-		}
-	case []account.Change:
-		if m.verbose {
-			for x := range d {
-				m.printAccountHoldingsChangeSummary(exchName, d[x])
-			}
+			log.Debugf(log.WebsocketMgr, "%+v", d)
```
Comment (gloriousCode) [inline engine/websocketroutine_manager.go]: Please revert or make equivalent. This doesn't even include the exchange.

File: exchange/accounts/accounts.go [hunk 67]
```diff
@@ -0,0 +1,303 @@
...
+}
+
+// SubAccounts contains a list of public SubAccounts
+type SubAccounts []*SubAccount
+
+// MustNewAccounts returns an initialized Accounts store for use in isolation from a global exchange accounts store
+// mux is set to dispatch.GetNewMux(nil)
+// Any errors in mux ID generation will panic, so users should balance risk vs utility accordingly depending on use-case
+func MustNewAccounts(e exchange) *Accounts {
+	a, err := NewAccounts(e, dispatch.GetNewMux(nil))
```
Comment (gloriousCode) [inline exchange/accounts/accounts.go]: > // mux is set to dispatch.GetNewMux(nil)

You can see that its nil [because of the way it is](https://www.youtube.com/watch?v=_d8mjam7KG8). Rewrite that part please

File: exchange/accounts/store.go [hunk 68]
```diff
@@ -0,0 +1,62 @@
...
+	if w, ok := e.(exchangeWrapper); ok {
+		// Because SetupDefaults is called on Base, it's easiest to just use the Base pointer as the key
+		e = w.GetBase()
+	}
+	a, ok := s.exchangeAccounts[e]
+	if !ok {
+		a, err = NewAccounts(e, s.mux)
+		s.exchangeAccounts[e] = a
+	}
+	return a, err
```
Comment (gloriousCode) [inline exchange/accounts/store.go]:
```suggestion
	a, ok := s.exchangeAccounts[e]
	if !ok {
		a, err = NewAccounts(e, s.mux)
		if err != nil {
			return nil, err
		}
		s.exchangeAccounts[e] = a
	}
	return a, nil
```

File: exchange/accounts/store_test.go [hunk 69]
```diff
@@ -0,0 +1,47 @@
...
+}
+
+func TestGetStore(t *testing.T) {
+	t.Parallel()
+	// Initialize global in case of -count=N+; No other tests should be relying on it
+	global.Store(nil)
+	s := GetStore()
+	require.NotNil(t, s)
+	require.Same(t, global.Load(), s, "GetStore must initialize the store")
+	require.Same(t, s, GetStore(), "GetStore must return the global store on second call")
```
Comment (gloriousCode) [inline exchange/accounts/store_test.go:27]:
```suggestion
	s := GetStore()
	require.NotNil(t, s, "GetStore must initialize the store")
	require.Same(t, global.Load(), s, "Load must return global store")
	require.Same(t, s, GetStore(), "GetStore must return the global store on second call")
```

File: exchanges/exchange_test.go [hunk 70]
```diff
@@ -787,62 +784,31 @@ func TestSetupDefaults(t *testing.T) {
...
-		t.Fatal(err)
-	}
-	err = b.Websocket.Enable()
-	if err != nil {
-		t.Fatal(err)
-	}
-	if !b.IsWebsocketEnabled() {
-		t.Error("websocket should be enabled")
-	}
+	exp, err := accounts.GetStore().GetExchangeAccounts(&b)
```
Comment (gloriousCode) [inline exchanges/exchange_test.go]: Is there any chance of this having funky business with `TestGetCollateral` and `TestGetStore`?

File: exchange/accounts/accounts.go [hunk 71]
```diff
@@ -0,0 +1,303 @@
...
+// Credentials will be retrieved from ctx, Use DeployCredentialsToContext.
+// Changes to balances are published individually
+func (a *Accounts) Save(ctx context.Context, subAccts SubAccounts, isSnapshot bool) error {
+	if err := common.NilGuard(a); err != nil {
+		return fmt.Errorf("cannot save holdings: %w", err)
+	}
+	if err := common.NilGuard(a.subAccounts); err != nil {
+		return fmt.Errorf("cannot save holdings: %w", err)
+	}
+
```
Comment (gloriousCode) [inline exchange/accounts/accounts.go:229]:
```suggestion
	if err := common.NilGuard(a, a.subAccounts); err != nil {
		return fmt.Errorf("cannot save holdings: %w", err)
	}

```

File: exchange/accounts/accounts.go [hunk 72]
```diff
@@ -0,0 +1,303 @@
...
+		}
+	}
+
+	return errs
+}
+
+// Merge adds CurrencyBalances in s to the SubAccount in l with a matching AssetType and ID
+// If no SubAccount matches, s is appended
+// Duplicate Currency Balances are added together
+func (l SubAccounts) Merge(s *SubAccount) SubAccounts {
```
Comment (gloriousCode) [inline exchange/accounts/accounts.go:287]: Nilguard s

File: exchange/accounts/accounts.go [hunk 73]
```diff
@@ -0,0 +1,303 @@
...
+		accBalances := a.currencyBalances(creds, s.ID, s.AssetType)
+
+		updated := false
+		missing := maps.Clone(accBalances)
+		for curr, newBal := range s.Balances {
+			delete(missing, curr.Item)
+			if newBal.UpdatedAt.IsZero() {
+				newBal.UpdatedAt = time.Now()
+			}
+			if newBal.Currency == currency.EMPTYCODE {
```
Comment (gloriousCode) [inline exchange/accounts/accounts.go]:
```suggestion
			if newBal.Currency.IsEmpty() {
```
Is the most minor of all things

File: exchange/accounts/balance.go [hunk 74]
```diff
@@ -0,0 +1,139 @@
...
+	}
+	b.internal.UpdatedAt = change.UpdatedAt // Set just the time, and then can compare easily
+	if b.internal == change {
+		return false, nil
+	}
+	b.internal = change
+	return true, nil
+}
+
+// balance rutens a balance for a currency
```
Comment (gloriousCode) [inline exchange/accounts/balance.go]: > "Rutens" could refer to the ancient Gallic tribe of the Ruteni, who lived in the Massif Central of France during the Iron Age and Roman periods, or it could be a pluralization of the German word "Ruten" which refers to a village in Lower Saxony and several mountains in Norway

File: exchange/accounts/balance.go [hunk 75]
```diff
@@ -0,0 +1,139 @@
...
+func (c currencyBalances) balance(curr *currency.Item) *balance {
+	if _, ok := c[curr]; !ok {
+		c[curr] = &balance{internal: Balance{Currency: curr.Currency()}}
+	}
+	return c[curr]
```
Comment (gloriousCode) [inline exchange/accounts/balance.go]:
```suggestion
	if _, ok := c[curr]; !ok {
		bal := &balance{internal: Balance{Currency: curr.Currency()}}
		c[curr] = bal
		return bal
	}
	return c[curr]
```
Navel gazing about looking up a map multiple times

edit: No idea if this works:
```suggestion
	if butts, ok := c[curr]; !ok {
		butts = &balance{internal: Balance{Currency: curr.Currency()}}
		return butts
	}
	return c[curr]
```

File: exchange/accounts/balance.go [hunk 76]
```diff
@@ -0,0 +1,139 @@
...
+	b.internal.UpdatedAt = change.UpdatedAt // Set just the time, and then can compare easily
+	if b.internal == change {
+		return false, nil
+	}
+	b.internal = change
+	return true, nil
+}
+
+// balance rutens a balance for a currency
+func (c currencyBalances) balance(curr *currency.Item) *balance {
```
Comment (gloriousCode) [inline exchange/accounts/balance.go:141]: I'm not sure why you need to mix-match having a pointer receiver for the other func `Public()` and non for here. The other one looks like it isn't of use. Can resolve if necessary

File: exchanges/binance/binance_wrapper.go [hunk 77]
```diff
@@ -570,113 +570,79 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
 }
 
-// UpdateAccountInfo retrieves balances for all enabled currencies for the
-// Binance exchange
-func (e *Exchange) UpdateAccountInfo(ctx context.Context, assetType asset.Item) (account.Holdings, error) {
-	var info account.Holdings
-	var acc account.SubAccount
-	acc.AssetType = assetType
-	info.Exchange = e.Name
+// UpdateAccountBalances retrieves balances for all enabled currencies for the Binance exchange
```
Comment (gloriousCode) [inline exchanges/binance/binance_wrapper.go]: Comment is not technically true, since at no point do we check or care about the enabled currency

File: exchanges/deribit/deribit_wrapper.go [hunk 78]
```diff
@@ -337,34 +337,29 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-			return resp, err
+			return nil, err
 		}
-		var subAcc account.SubAccount
-		subAcc.Currencies = append(subAcc.Currencies, account.Balance{
-			Currency: currency.NewCode(currencies[x].Currency),
-			Total:    data.Balance,
-			Hold:     data.Balance - data.AvailableFunds,
+		subAccts[0].Balances.Set(currencies[i].Currency, accounts.Balance{
+			Total: resp.Balance,
```
Comment (gloriousCode) [inline exchanges/deribit/deribit_wrapper.go:358]: Have some squiggly lines on the lack of nil check for resp, but my heart isn't for it

File: exchanges/gateio/gateio_websocket.go [hunk 79]
```diff
@@ -546,29 +540,23 @@ func (e *Exchange) processMarginBalances(ctx context.Context, data []byte) error
...
-	if err != nil {
-		return err
-	}
-	creds, err := e.GetCredentials(ctx)
-	if err != nil {
+	if err := json.Unmarshal(data, &resp); err != nil {
 		return err
 	}
-	changes := make([]account.Change, len(resp.Result))
+	subAccts := accounts.SubAccounts{accounts.NewSubAccount(asset.Margin, "")}
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_websocket.go]: Why not use user like spot?

File: exchanges/gateio/gateio_websocket.go [hunk 80]
```diff
@@ -597,25 +585,21 @@ func (e *Exchange) processCrossMarginBalance(ctx context.Context, data []byte) e
...
-			Account:   resp.Result[x].User,
-			AssetType: asset.Margin,
-			Balance: &account.Balance{
-				Currency:  currency.NewCode(resp.Result[x].Currency),
-				Total:     resp.Result[x].Total.Float64(),
-				Free:      resp.Result[x].Available.Float64(),
-				UpdatedAt: resp.Result[x].Timestamp.Time(),
-			},
-		}
+		a := accounts.NewSubAccount(asset.Margin, resp.Result[x].User)
```
Comment (gloriousCode) [inline exchanges/gateio/gateio_websocket.go]:
```suggestion
		a := accounts.NewSubAccount(asset.CrossMargin, resp.Result[x].User)
```

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go (hunk 62 above)
Comment (gbjk) [reply cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go]: 🙏 

Fixed https://github.com/gbjk/gocryptotrader/commit/7ace9f102

File: engine/portfolio_manager.go (hunk 63 above)
Comment (gbjk) [reply engine/portfolio_manager.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/f603ebabd

File: exchange/accounts/balance.go (hunk 64 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: This was discussed previously; Here's what I said:

> In terms of coding intention and immutability, I want to use pass-by-value when it's "the right thing to do".
> I flip-flopped on this several times and wrote it with a reference and without, before settling on this.
> I triple checked it again before adding nolint, and even half switched it back to *Balance before reverting.
> I Iooked at all the places that call this, in the exchanges, and it just doesn't make sense to make them all pass a reference just to dereference it in the function.

File: exchange/accounts/store.go (hunk 65 above)
Comment (gbjk) [reply exchange/accounts/store.go:29]: Because we could never safely initialise it in `GetStore` if we can't `CompareAndSwap`.

File: engine/websocketroutine_manager.go (hunk 66 above)
Comment (gbjk) [reply engine/websocketroutine_manager.go]: * What did the function comment "deprecated when an account holdings update is done" mean? ( @shazbert )
* Should the accounts system be printing this instead, for all pathways, when verbose?
* And if so, I think we should ignore these types in the default data handler and just let other consumers pick them up if they want.

Just reverting for expediency, can switch to another solution depending on answers

Fixed https://github.com/gbjk/gocryptotrader/commit/0a24f9030

File: exchange/accounts/accounts.go (hunk 67 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: I do not agree about it being self-evident.
function comments tell godoc readers things they need to know that they can't see in the method signature.
We don't expect them to click to open the code to know more.

But at the same time: I was wrong to not just say that it's using the global dispatcher.
At the time I didn't want to copy over that information from GetNewMux, but it's right to.

Fixed https://github.com/gbjk/gocryptotrader/commit/eaca06dff

File: exchange/accounts/store.go (hunk 68 above)
Comment (gbjk) [reply exchange/accounts/store.go]: Okay. Didn't seem likely enough to worry about populating a blown `a`, but you're right.

Fixed https://github.com/gbjk/gocryptotrader/commit/fce7eaced

File: exchange/accounts/store_test.go (hunk 69 above)
Comment (gbjk) [reply exchange/accounts/store_test.go:27]: Sorry, I don't agree with these changes:
* The `NotNil` should actually be `must not return a nil Store`. And this is a unit test on that method, so we don't need to say that. I can add it anyway for you though.
* We're testing `s`, **not** Load. `Load` is the atomic pointer method. The original test comment was correct. But I'll add `global` to it to be clearer.

Fixed https://github.com/gbjk/gocryptotrader/commit/7c2f5e3be

File: exchanges/exchange_test.go (hunk 70 above)
Comment (gbjk) [reply exchanges/exchange_test.go]: Sorry, I don't understand this comment.
You're referring to `rpcserver_test.go`'s `TestGetCollateral`, right?

File: exchange/accounts/accounts.go (hunk 71 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:229]: This is not possible. It would panic on `a` being nil.
I tried in vein to solve this problem and never game up with a solution that wasn't insane.

File: exchange/accounts/accounts.go (hunk 72 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:287]: Fixed https://github.com/gbjk/gocryptotrader/commit/b889ed647

File: exchange/accounts/accounts.go (hunk 73 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/449a8bccf

File: exchange/accounts/balance.go (hunk 74 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/dc57451ee

File: exchange/accounts/balance.go (hunk 75 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: No, that wouldn't work.
But we're definitely wasting time on a double lookup in the "hotter path" for this func

Fixed https://github.com/gbjk/gocryptotrader/commit/6317c94b0

File: exchange/accounts/balance.go (hunk 76 above)
Comment (gbjk) [reply exchange/accounts/balance.go:141]: If c is a pointer here then the map lookups become messier, but in `Public` it didn't feel too bad for the 2 uses of `*c`

But now you point it out (hurr hurr) ... `Public` can just be a non-pointer.

Fixed https://github.com/gbjk/gocryptotrader/commit/8f5862d52

File: exchanges/binance/binance_wrapper.go (hunk 77 above)
Comment (gbjk) [reply exchanges/binance/binance_wrapper.go]: So I think this is a change to all exchanges, and to make it clean we just make the comment
```
// UpdateAccountBalances retrieves currency balances
```

Fixed https://github.com/gbjk/gocryptotrader/commit/fb6f4a2d3

File: exchanges/deribit/deribit_wrapper.go (hunk 78 above)
Comment (gbjk) [reply exchanges/deribit/deribit_wrapper.go:358]: I think it's okay to trust a value to not be nil if the method that returned it didn't return an error.
We do it everywhere.

File: exchanges/gateio/gateio_websocket.go (hunk 79 above)
Comment (gbjk) [reply exchanges/gateio/gateio_websocket.go]: 🤷 The code that was there before didn't use it. 
This seems right, though:

Fixed https://github.com/gbjk/gocryptotrader/commit/61f500242

> Why not use user like spot?

This took so many attempts to read 😂

File: exchanges/gateio/gateio_websocket.go (hunk 80 above)
Comment (gbjk) [reply exchanges/gateio/gateio_websocket.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/65edaa899

File: engine/websocketroutine_manager.go (hunk 66 above)
Comment (shazbert) [reply engine/websocketroutine_manager.go]: > What did the function comment "deprecated when an account holdings update is done" mean? ( @shazbert )

I am not sure, I was happy with its removal though 😆 

>Should the accounts system be printing this instead, for all pathways, when verbose?

 I am happy with it not doing anything like that
 
 > And if so, I think we should ignore these types in the default data handler and just let other consumers pick them up if they want.
 
 This handler is just a POC for library so being verbose for demonstration is okay and I think this can be overridden?

Comment (gloriousCode) [reply engine/websocketroutine_manager.go]: Revert was a poor choice on my part. All I really wanted was `("%s %+v", eName, data)` to give the log context. Users can override the response as Shazbert speculates. Mostly just an ACK log if verbose

File: exchange/accounts/store.go (hunk 65 above)
Comment (gloriousCode) [reply exchange/accounts/store.go:29]: Nice

File: exchange/accounts/balance.go (hunk 64 above)
Comment (gloriousCode) [reply exchange/accounts/balance.go]: I'll do some tracking and verify what you're saying 🌈

File: exchange/accounts/accounts.go (hunk 67 above)
Comment (gloriousCode) [reply exchange/accounts/accounts.go]: I agree with what youre saying, but I agree more with your outcome where you described it more effectively and was more trying to steer it that way... Poorly 😄

File: exchange/accounts/store_test.go (hunk 69 above)
Comment (gloriousCode) [reply exchange/accounts/store_test.go:27]: I think I fell for the classic trap of mixing `expected` and `received` around

File: exchanges/exchange_test.go (hunk 70 above)
Comment (gloriousCode) [reply exchanges/exchange_test.go]: It was mostly based on reading your other comment:
``` 
func TestGetStore(t *testing.T) {
	t.Parallel()
	// Initialize global in case of -count=N+; No other tests should be relying on it
```
Where I believed these three tests rely on the same global.  I'm less concerned after sleeping though, I'm not seeing the kinds of equality checks that could cause issue. Your comment doesn't even apply to how I was thinking about it anyway.

File: exchange/accounts/balance.go (hunk 75 above)
Comment (gloriousCode) [reply exchange/accounts/balance.go]: Yours is even better 🌈

File: engine/websocketroutine_manager.go (hunk 66 above)
Comment (gbjk) [reply engine/websocketroutine_manager.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/0329489f4 and  https://github.com/gbjk/gocryptotrader/commit/bf9cf5a2a

File: exchanges/exchange_test.go (hunk 70 above)
Comment (gbjk) [reply exchanges/exchange_test.go]: Yep, that's correct.
The comment in `TestGetStore` is saying why we're initialzing it, and that no other tests should be using it.
( Hopefully it makes sense on a second reading, right? )

However you've correctly highlighted that this *is* using it, when it shouldn't be.
`testexch.Setup` gives us an isolated Accounts Store for most use-cases.

But here SetupDefaults is trying to make sure we're using the actual global one as a default, and that'll race with us clobbering it in `TestGetStore`. I'm pretty sure that `TestGetStore` needed to initialize it once per run. 
You can't use `TestMain` or `init` for this, `-count=n+` won't trigger that.

TestSetupDefaults doesn't care *which* accounts store it gets. It just needs to make sure it gets the same one.

Anyway, this will cover us:

Fixed https://github.com/gbjk/gocryptotrader/commit/0d15aef1f

Comment (gloriousCode) [reply exchanges/exchange_test.go]: That has 404'd every time I click on it 😭

Comment (gbjk) [reply exchanges/exchange_test.go]: Soorrrrrrryyyyy 😬 
```
Unpushed to origin/bugfix/bybit_account_race (1)
0d15aef1f fixup! Accounts: Move singleton accounts service to exchange Accounts
```

Try now.

File: exchange/accounts/balance.go (hunk 64 above)
Comment (gloriousCode) [reply exchange/accounts/balance.go]: So after benchmarking the impact and what you've said I agree. The only thing I think I'd want you to reconsider is the comment itself. Its not so much that hugeparam is irrelevant and that you'd deref. You are only be derefing because you've made `CurrencyBalances` immutable. 
I feel like the message should be `// nolint: gocritic // ignoring hugeparam as Balance is intentionally Immutable` or something along those lines

edit: this may be less clear though. I think I only take issue with  hugeparam being called irrelevant, its that you're being intentional

File: gctscript/wrappers/gct/exchange/exchange_test.go [hunk 81]
```diff
@@ -123,7 +123,7 @@ func TestExchange_AccountInformation(t *testing.T) {
 	if !configureExchangeKeys() {
```
Comment (gloriousCode) [inline gctscript/wrappers/gct/exchange/exchange_test.go:123]: Update testname

**Review by gloriousCode — CHANGES_REQUESTED** [review]
The PR works, yay! Its a large update that reduces footprint and improves on it all. One nit on top of my request for you to reconsider the hugeparam comment. Its a real doozy of a change request

File: exchange/accounts/balance.go (hunk 64 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: > It's not so much that hugeparam is irrelevant and that you'd deref. You are only be derefing because you've made CurrencyBalances immutable.

I wouldn't say `CurrencyBalances` is immutable. This very function is a mutator for it.
What I mean by not relevant is that hugeparam warns us that we're copying a value, and even if we switched to using a pointer, we'd still be choosing to dereference it to get a copy. For more overhead, in fact.

Would this be acceptable/better:
```
// Set will set a currency balance, overwriting any previous Balance
//
//nolint:gocritic // Ignoring hugeparam because we want the convenience of callers passing by value
//nolint:gocritic // and we want to store a copy anyway so the hugeparam warning that this copies a value is not relevant
func (c *CurrencyBalances) Set(curr currency.Code, b Balance) {
```

Normally I'd just commit it anyway, but I'm really not sure in this instance.

File: gctscript/wrappers/gct/exchange/exchange_test.go (hunk 81 above)
Comment (gbjk) [reply gctscript/wrappers/gct/exchange/exchange_test.go:123]: Fixed https://github.com/gbjk/gocryptotrader/commit/98453e4de

Comment (gbjk) [reply gctscript/wrappers/gct/exchange/exchange_test.go:123]: Since this is a slam dunk, I'm going to take the opportunity to rebase again and squash.

File: exchange/accounts/balance.go (hunk 64 above)
Comment (gbjk) [reply exchange/accounts/balance.go]: Available if we want to cherry-pick if we want it.

[gbjk@refs/heads/orphans/gerald](https://github.com/gbjk/gocryptotrader/commit/df30d494e)

Comment (gloriousCode) [reply exchange/accounts/balance.go]: > even if we switched to using a pointer, we'd still be choosing to dereference it to get a copy

That's what I was trying to say in that you are doing that intentionally, you have chosen to use a non-pointer to store it, so huge param is raising an issue, but you have designed things in a way as that you want to store non-pointers
`//nolint:gocritic // Ignoring hugeparam because we store non-pointers in CurrencyBalances. Making the parameter a pointer will just be dereferenced`

edit: Its not as important versus just approving this though. I've learned what you meant from looking at how you're using it.

**Review by gloriousCode — APPROVED** [review]
tACK!

File: backtester/funding/funding.go [hunk 82]
```diff
@@ -564,31 +564,22 @@ func (f *FundManager) UpdateFundingFromLiveData(initialFundsSet bool) error {
...
-		var creds *account.Credentials
-		creds, err = exchanges[x].GetCredentials(context.TODO())
-		if err != nil {
-			return err
-		}
-		assets := exchanges[x].GetAssetTypes(false)
-		for y := range assets {
-			if assets[y].IsFutures() {
+	for _, e := range exchanges {
+		eName := e.GetName()
```
Comment (thrasher-) [inline backtester/funding/funding.go:568]: This can be moved down to before SetFunding or just inlined directly within the func call since this only used once.

Also indexing is preferred, there's caveats to this with regards to pointers but the less copy spam the better

File: dispatch/dispatch.go [hunk 83]
```diff
@@ -68,32 +76,25 @@ func IsRunning() bool {
...
+		return ErrDispatcherAlreadyRunning
 	}
 
 	d.running = true
 
 	if workers < 1 {
-		log.Warnf(log.DispatchMgr,
-			"workers cannot be zero, using default value %d\n",
-			DefaultMaxWorkers)
+		log.Warnf(log.DispatchMgr, "workers cannot be zero, using default value %d\n", DefaultMaxWorkers)
```
Comment (thrasher-) [inline dispatch/dispatch.go]: Wasn't your doing but since it was changed, noticed an inconsistency with these log messages (we use title case everywhere else for the first message) 

```suggestion
		log.Warnf(log.DispatchMgr, "Dispatcher workers cannot be zero, using default value %d\n", DefaultMaxWorkers)
```

File: dispatch/dispatch.go [hunk 84]
```diff
@@ -68,32 +76,25 @@ func IsRunning() bool {
...
 		workers = DefaultMaxWorkers
 	}
 	if channelCapacity < 1 {
-		log.Warnf(log.DispatchMgr,
-			"jobs limit cannot be zero, using default values %d\n",
-			DefaultJobsLimit)
+		log.Warnf(log.DispatchMgr, "jobs limit cannot be zero, using default values %d\n", DefaultJobsLimit)
```
Comment (thrasher-) [inline dispatch/dispatch.go]:
```suggestion
		log.Warnf(log.DispatchMgr, "Dispatcher jobs limit cannot be zero, using default value %d\n", DefaultJobsLimit)
```

File: engine/portfolio_manager.go [hunk 85]
```diff
@@ -124,152 +124,91 @@ func (m *portfolioManager) processPortfolio() {
 	}
 	m.m.Lock()
 	defer m.m.Unlock()
-	exchanges, err := m.exchangeManager.GetExchanges()
-	if err != nil {
-		log.Errorf(log.PortfolioMgr, "Portfolio manager cannot get exchanges: %v", err)
+	if err := m.updateExchangeBalances(); err != nil {
+		log.Errorln(log.PortfolioMgr, err)
```
Comment (thrasher-) [inline engine/portfolio_manager.go]: Prior error message 
```suggestion
		log.Errorf(log.PortfolioMgr, "Portfolio updateExchangeBalances error: %v", err)
```
```suggestion
		log.Errorln(log.PortfolioMgr, err)
```

File: exchange/accounts/accounts.go [hunk 86]
```diff
@@ -0,0 +1,306 @@
...
+	}
+
+	return errs
+}
+
+// Merge adds CurrencyBalances in s to the SubAccount in l with a matching AssetType and ID
+// If no SubAccount matches, s is appended
+// Duplicate Currency Balances are added together
+func (l SubAccounts) Merge(s *SubAccount) SubAccounts {
+	if err := common.NilGuard(s); err != nil {
```
Comment (thrasher-) [inline exchange/accounts/accounts.go:288]: Missing test coverage for this now (at 98.8% ATM) 👼

File: exchange/accounts/accounts_test.go [hunk 87]
```diff
@@ -0,0 +1,530 @@
...
+	creds2 = &Credentials{Key: "2"}
+	creds3 = &Credentials{Key: "3"}
+)
+
+func TestNewAccounts(t *testing.T) {
+	t.Parallel()
+	a, err := NewAccounts(&mockEx{"mocky"}, dispatch.GetNewMux(nil))
+	require.NoError(t, err)
+	require.NotNil(t, a)
+	assert.Equal(t, "mocky", a.Exchange.GetName(), "Exchange should set correctly")
```
Comment (thrasher-) [inline exchange/accounts/accounts_test.go]:
```suggestion
	assert.Equal(t, "mocky", a.Exchange.GetName(), "Exchange name should set correctly")
```

File: exchange/accounts/accounts_test.go [hunk 88]
```diff
@@ -0,0 +1,530 @@
...
+	assert.NotNil(t, a.subAccounts, "subAccounts should be initialized")
+	assert.NotEmpty(t, a.routingID, "ID should not be empty")
```
Comment (thrasher-) [inline exchange/accounts/accounts_test.go]:
```suggestion
	assert.NotEmpty(t, a.routingID, "routingID should not be empty")
```

File: exchange/accounts/accounts_test.go [hunk 89]
```diff
@@ -0,0 +1,530 @@
...
+	a := MustNewAccounts(&mockEx{"mocky"})
+	require.NotNil(t, a)
+	require.Panics(t, func() { _ = MustNewAccounts(nil) })
+}
+
+func TestNewSubAccount(t *testing.T) {
+	t.Parallel()
+	a := NewSubAccount(asset.Spot, "")
+	require.NotNil(t, a, "must not return nil with no id")
+	assert.Equal(t, asset.Spot, a.AssetType, "AssetType should correct")
```
Comment (thrasher-) [inline exchange/accounts/accounts_test.go]:
```suggestion
	assert.Equal(t, asset.Spot, a.AssetType, "AssetType should be correct")
```

File: exchange/accounts/accounts_test.go [hunk 90]
```diff
@@ -0,0 +1,530 @@
...
+							tc.post(t)
+						}
+					})
+				}
+			}
+		})
+	}
+}
+
+var skynetDate = time.Unix(872896440, 0)
```
Comment (thrasher-) [inline exchange/accounts/accounts_test.go:394]: Wait, it already has occurred?! 😆

File: exchange/accounts/accounts.go [hunk 91]
```diff
@@ -0,0 +1,306 @@
...
+type SubAccount struct {
+	ID        string
+	AssetType asset.Item
+	Balances  CurrencyBalances
+}
+
+// SubAccounts contains a list of public SubAccounts
+type SubAccounts []*SubAccount
+
+// MustNewAccounts returns an initialized Accounts store for use in isolation from a global exchange accounts store
```
Comment (thrasher-) [inline exchange/accounts/accounts.go]:
```suggestion
// MustNewAccounts returns an initialised Accounts store for use in isolation from a global exchange accounts store
```

File: exchange/accounts/accounts.go [hunk 92]
```diff
@@ -0,0 +1,306 @@
...
+// Any errors in mux ID generation will panic, so users should balance risk vs utility accordingly depending on use-case
+func MustNewAccounts(e exchange) *Accounts {
+	a, err := NewAccounts(e, dispatch.GetNewMux(nil))
+	if err != nil {
+		panic(err)
+	}
+	return a
+}
+
+// NewAccounts returns an initialized Accounts store for use in isolation from a global exchange accounts store
```
Comment (thrasher-) [inline exchange/accounts/accounts.go]:
```suggestion
// NewAccounts returns an initialised Accounts store for use in isolation from a global exchange accounts store
```

File: exchange/accounts/accounts_test.go [hunk 93]
```diff
@@ -0,0 +1,530 @@
...
+	creds3 = &Credentials{Key: "3"}
+)
+
+func TestNewAccounts(t *testing.T) {
+	t.Parallel()
+	a, err := NewAccounts(&mockEx{"mocky"}, dispatch.GetNewMux(nil))
+	require.NoError(t, err)
+	require.NotNil(t, a)
+	assert.Equal(t, "mocky", a.Exchange.GetName(), "Exchange should set correctly")
+	assert.NotNil(t, a.subAccounts, "subAccounts should be initialized")
```
Comment (thrasher-) [inline exchange/accounts/accounts_test.go]:
```suggestion
	assert.NotNil(t, a.subAccounts, "subAccounts should be initialised")
```

File: exchange/accounts/balance_test.go [hunk 94]
```diff
@@ -0,0 +1,149 @@
...
+	assert.Equal(t, b.internal, i)
+}
+
+// TestBalanceAdd exercises Balance.Add
+func TestBalanceAdd(t *testing.T) {
+	t.Parallel()
+	n1 := time.Now()
+	n2 := n1.Add(-2 * time.Minute)
+	b := new(Balance).Add(Balance{Total: 4.2, UpdatedAt: n2})
+	assert.Equal(t, 4.2, b.Total, "should initialize Total")
```
Comment (thrasher-) [inline exchange/accounts/balance_test.go]:
```suggestion
	assert.Equal(t, 4.2, b.Total, "should initialise Total")
```

File: exchanges/bithumb/bithumb_wrapper.go [hunk 95]
```diff
@@ -299,52 +299,29 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-	exchangeBalances := make([]account.Balance, 0, len(bal.Total))
-	for key, totalAmount := range bal.Total {
-		hold, ok := bal.InUse[key]
+	subAccts := accounts.SubAccounts{accounts.NewSubAccount(assetType, "")}
+	for k, totalAmount := range bal.Total {
+		hold, ok := bal.InUse[k]
 		if !ok {
-			return info, fmt.Errorf("getAccountInfo error - in use item not found for currency %s",
-				key)
+			return subAccts, fmt.Errorf("getAccountInfo error - in use item not found for currency %s", k)
```
Comment (thrasher-) [inline exchanges/bithumb/bithumb_wrapper.go]:
```suggestion
			return subAccts, fmt.Errorf("currency %s missing from InUse balances", k)
```

File: exchanges/exchange_test.go [hunk 96]
```diff
@@ -787,62 +784,36 @@ func TestSetupDefaults(t *testing.T) {
...
-	}
-	if !b.IsWebsocketEnabled() {
-		t.Error("websocket should be enabled")
-	}
+	exp, err := accountsStore.GetExchangeAccounts(&b)
+	require.NoError(t, err, "GetExchangeAccounts must not error")
+	assert.Same(t, exp, b.Accounts, "SetupDefaults should default accounts from the global accounts store")
+	b.Accounts = accounts.MustNewAccounts(&b)
+	a := b.Accounts
+	require.NoError(t, err, "NewAccounts must not error")
```
Comment (thrasher-) [inline exchanges/exchange_test.go]: This is currently testing nothing as `MustNewAccounts` would panic, so needs a panic check instead

File: exchange/accounts/fixture_test.go [hunk 97]
```diff
@@ -0,0 +1,41 @@
...
+}
+
+func (m *mockEx) GetCredentials(ctx context.Context) (*Credentials, error) {
+	if value := ctx.Value(ContextCredentialsFlag); value != nil {
+		if s, ok := value.(*ContextCredentialsStore); ok {
+			return s.Get(), nil
+		}
+		return nil, common.GetTypeAssertError("*accounts.ContextCredentialsStore", value)
+	}
+	return nil, nil
```
Comment (samuael) [inline exchange/accounts/fixture_test.go]: 😕 🤔 ?

File: exchanges/binance/binance_wrapper.go [hunk 98]
```diff
@@ -568,113 +568,79 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
+			return nil, err
 		}
-		var currencyDetails []account.Balance
-		for i := range accData.Assets {
-			currencyDetails = append(currencyDetails, account.Balance{
-				Currency: currency.NewCode(accData.Assets[i].Asset),
-				Total:    accData.Assets[i].WalletBalance,
-				Hold:     accData.Assets[i].WalletBalance - accData.Assets[i].AvailableBalance,
-				Free:     accData.Assets[i].AvailableBalance,
+		subAccts = accounts.SubAccounts{accounts.NewSubAccount(assetType, "")}
```
Comment (samuael) [inline exchanges/binance/binance_wrapper.go:586]: _(Optional)_ : Could you make `resp.Assets` to `[]*FuturesAccountAsset` and loop using the pointer like

`for _, ast := range resp.Assets {}`

File: exchanges/binance/binance_wrapper.go [hunk 99]
```diff
@@ -568,113 +568,79 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
...
-				},
-			)
+		resp, err := e.UAccountBalanceV2(ctx)
+		if err != nil {
+			return nil, err
 		}
-
-		if info.Accounts, err = account.CollectBalances(accountCurrencyDetails, assetType); err != nil {
-			return account.Holdings{}, err
+		subAccts = make(accounts.SubAccounts, 0, len(resp))
```
Comment (samuael) [inline exchanges/binance/binance_wrapper.go:599]: Same applies here

File: exchanges/bitflyer/bitflyer_wrapper.go [hunk 100]
```diff
@@ -240,10 +240,9 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
 	return orderbook.Get(e.Name, fPair, assetType)
 }
 
-// UpdateAccountInfo retrieves balances for all enabled currencies on the
-// Bitflyer exchange
-func (e *Exchange) UpdateAccountInfo(_ context.Context, _ asset.Item) (account.Holdings, error) {
-	return account.Holdings{}, common.ErrNotYetImplemented
+// UpdateAccountBalances retrieves currency balances
+func (e *Exchange) UpdateAccountBalances(_ context.Context, _ asset.Item) (accounts.SubAccounts, error) {
+	return accounts.SubAccounts{}, common.ErrNotYetImplemented
```
Comment (samuael) [inline exchanges/bitflyer/bitflyer_wrapper.go:245]: You can replace this with `common.ErrFunctionNotSupported` since you're here

File: exchange/accounts/balance_test.go [hunk 101]
```diff
@@ -0,0 +1,149 @@
...
+
+// TestCurrencyBalancesAdd exercises CurrencyBalances.Add
+func TestCurrencyBalancesAdd(t *testing.T) {
+	t.Parallel()
+
+	c := CurrencyBalances{}
+	err := c.Add(currency.BTC, Balance{Total: 4.2})
+	require.NoError(t, err)
+
+	assert.Contains(t, c, currency.BTC, "should add an entry to an uninitialised CurrencyBalances")
```
Comment (samuael) [inline exchange/accounts/balance_test.go]: `assert` -> `require`

File: exchange/accounts/balance_test.go [hunk 102]
```diff
@@ -0,0 +1,149 @@
...
+
+	_, err = b.update(Balance{UpdatedAt: n, Currency: currency.ETH})
+	assert.ErrorIs(t, err, errBalanceCurrencyMismatch)
+
+	_, err = b.update(Balance{UpdatedAt: n.Add(-time.Millisecond)})
+	assert.ErrorIs(t, err, errOutOfSequence, "should error when time out of sequence")
+
+	u, err := b.update(Balance{UpdatedAt: n, Total: 5.1})
+	require.NoError(t, err, "must not error when time is the same instant and currency is empty")
+	assert.Equal(t, 5.1, b.internal.Total, "Total should be correct")
```
Comment (samuael) [inline exchange/accounts/balance_test.go:131]: `require.NotNil(t, b.internal)`

File: exchange/accounts/store_test.go [hunk 103]
```diff
@@ -0,0 +1,47 @@
...
+
+	m = &mockEx{"new"}
+	got, err = s.GetExchangeAccounts(m)
+	require.NoError(t, err)
+	assert.Same(t, s.exchangeAccounts[m], got, "Should retrieve the new exchange")
+
+	w := &mockExBase{m}
+	got, err = s.GetExchangeAccounts(w)
+	require.NoError(t, err)
+	require.NotNil(t, got)
```
Comment (samuael) [inline exchange/accounts/store_test.go]: `assert`

**Review by samuael — COMMENTED** [review]
Nice work, sir.
I just left minor (most optional) comments.

File: backtester/funding/funding.go (hunk 82 above)
Comment (gbjk) [reply backtester/funding/funding.go:568]: > This can be moved down to before SetFunding or just inlined directly within the func call since this only used once.

Code line only written once, but runtime evaluated/called NxN.
Out of habit, I don't wanna call `GetName()`in a `for` of `for`.
It's not *that* conditional that we'll get to it. If nothing blows up, we should evaluate it at least once.
So I'd prefer to not move it 🙂  But will if you insist, obvs.

> Also indexing is preferred, there's caveats to this with regards to pointers but the less copy spam the better

Agreed in general, but not about assets: `asset.Item` is uint32. So in this specific case it's no worse than ranging a pointer.

The overlords confirmed:
> In Go, the range clause copies the element into the loop variable each iteration. With []asset.Item, you copy the concrete value each time; here asset.Item is just an alias for a small
  value (it’s implemented as an enum), so the copy is a few bytes and stays in registers—there’s essentially no memory pressure.
>  If the slice were []*asset.Item, the loop would copy only a pointer (also one machine word), but you’d now pay for keeping those asset.Item values somewhere else in memory. You’d introduce
  additional heap objects, more pointer chasing, and extra GC tracking. So despite the slightly smaller per-iteration copy, the pointer version usually costs more overall because of the
  extra allocations and indirection.
> Indexing the slice each time (asset.Items[i]) doesn’t allocate or retain anything new either—the value is read straight from the slice on every use. The trade‑off is a tiny extra load for
  every access. With small value types (like asset.Item, just an enum), the difference is negligible: the single copy you get from for _, item := range asset.Items is just as cheap, and you
  avoid repeating the index expression. Using pointers would actually introduce more GC and indirection overhead, **so the current ranged‑value pattern remains both simpler and friendlier to
  memory/cache.**

File: dispatch/dispatch.go (hunk 83 above)
Comment (gbjk) [reply dispatch/dispatch.go]: Agreed.
Noting at the same time it has it's own log type, but I still think prefixing is sane:
`[ERROR] | DISPATCH | 03/10/2025 08:59:39 | Penguins!`

Fixed https://github.com/gbjk/gocryptotrader/commit/08f964c20

File: dispatch/dispatch.go (hunk 84 above)
Comment (gbjk) [reply dispatch/dispatch.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/08f964c20

File: backtester/funding/funding.go (hunk 82 above)
Comment (thrasher-) [reply backtester/funding/funding.go:568]: I said move it down to before SetFunding **OR** inline it so its' clear where exactly it is being used. Understand the asset.Item but I'm talking about it from a generalised perspective. With larger data structures the difference is noticable (have benchmarked it out of curiosity in the past)

File: engine/portfolio_manager.go (hunk 85 above)
Comment (gbjk) [reply engine/portfolio_manager.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/25734b502

File: exchange/accounts/accounts.go (hunk 86 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:288]: Thanks 🙏 

Fixed https://github.com/gbjk/gocryptotrader/commit/7376856d8

Noting there's one line I really couldn't work out how to hit... but now I say that, I'll ask claudex about it.

File: exchange/accounts/accounts_test.go (hunk 89 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/90312cf31

File: exchange/accounts/accounts_test.go (hunk 88 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/90312cf31

File: exchange/accounts/accounts_test.go (hunk 87 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/90312cf31

File: exchange/accounts/accounts.go (hunk 92 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/be39e029f

File: exchange/accounts/accounts.go (hunk 91 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/be39e029f

File: exchange/accounts/accounts_test.go (hunk 93 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/94031f219

File: exchange/accounts/balance_test.go (hunk 94 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/8ecaf932b

And one more in store_test at the same time.

File: exchanges/bithumb/bithumb_wrapper.go (hunk 95 above)
Comment (gbjk) [reply exchanges/bithumb/bithumb_wrapper.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/8e84d49e4

File: exchanges/exchange_test.go (hunk 96 above)
Comment (gbjk) [reply exchanges/exchange_test.go]: Yikes, that was stupid!
Since it's not the responsibility of `TestSetupDefaults" to ensure `MustNewAccounts` doesn't panic, and `TestMustNewAccounts` already covers that, I'll just remove this line.

Fixed https://github.com/gbjk/gocryptotrader/commit/badda8287

File: backtester/funding/funding.go (hunk 82 above)
Comment (thrasher-) [reply backtester/funding/funding.go:568]: On second thoughts:
Always prefer indexing, unless a slice of pointers or a primitive data type where the cost of copying (small size) is negligable and makes no perf difference where the ease of usage is better:

Reference where large size is cooked:
https://gist.github.com/thrasher-/e5fc5270c902f9323af999ace6068f01

```
BenchmarkRangeCopy-8                2887            399793 ns/op               0 B/op          0 allocs/op
BenchmarkIndexing-8                46731             23145 ns/op               0 B/op          0 allocs/op
BenchmarkRangeIndexOnly-8          54997             21311 ns/op               0 B/op          0 allocs/op
PASS
```

Comment (gbjk) [reply backtester/funding/funding.go:568]: Inlined the GetAssetTypes call. Which is the only thing you didn't ask for 😂 

Fixed https://github.com/gbjk/gocryptotrader/commit/de2ce5ac7

Will inline `GetName` if required, but still I'm sticking to: I don't want to call it assets * SubAccounts * Balances.
It's declared outside those loops to avoid multiple executions.
Runtime will not optimise this into one call, I've checked.
( Because it can't trust / determine that e hasn't changed by anything else ).
[This change is on hot standby if you want it though](https://github.com/gbjk/gocryptotrader/commit/cf5044c7c)

**Review by thrasher- — APPROVED** [review]
Thanks for making those changes!

File: backtester/funding/funding.go (hunk 82 above)
Comment (thrasher-) [reply backtester/funding/funding.go:568]: Agree with your reasoning, GetName isn't inlined here and escapes the heap due to the exchanges interface so no need to adjust

File: exchange/accounts/fixture_test.go (hunk 97 above)
Comment (gbjk) [reply exchange/accounts/fixture_test.go]: If there's no credentials, we don't return credentials 🤷 
We didn't need anything else from this for the purpose of these tests.
I think it actually helped with a positive path.

File: exchanges/binance/binance_wrapper.go (hunk 98 above)
Comment (gbjk) [reply exchanges/binance/binance_wrapper.go:586]: This quickly got out of control.
I did it, and then had to do it to all the `for` calls in this func. Which meant making the same changes to other places. Which kinda felt I should be changing other types.

I'll decline to do this in isolation. Someone can Drive-By all the types for binance at once later 😄

File: exchanges/binance/binance_wrapper.go (hunk 99 above)
Comment (gbjk) [reply exchanges/binance/binance_wrapper.go:599]: Same response applies here.
Resolving this one, leaving the earlier one open for you to parse.

File: exchanges/bitflyer/bitflyer_wrapper.go (hunk 100 above)
Comment (gbjk) [reply exchanges/bitflyer/bitflyer_wrapper.go:245]: They have an api for this. We just ... haven't implemented it.
So ... Isn't this the correct error message?

File: exchange/accounts/balance_test.go (hunk 101 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go]: Thanks. Also needed to check we have LTC.

Fixed https://github.com/gbjk/gocryptotrader/commit/888793bee

File: exchange/accounts/balance_test.go (hunk 102 above)
Comment (gbjk) [reply exchange/accounts/balance_test.go:131]: But ... we know it's not nil. We just declared it above and actually put `internal` into it manually 🤷‍♂️

File: exchange/accounts/store_test.go (hunk 103 above)
Comment (gbjk) [reply exchange/accounts/store_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/8be28ab0b

File: exchange/accounts/accounts.go (hunk 86 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:288]: Behold: Coverage for the missing line.

Fixed https://github.com/gbjk/gocryptotrader/commit/15cb33471

File: exchange/accounts/accounts.go [hunk 104]
```diff
@@ -0,0 +1,306 @@
...
+	mu          sync.RWMutex
+	mux         *dispatch.Mux
+}
+
+type (
+	credSubAccounts map[Credentials]subAccounts
+	subAccounts     map[key.SubAccountAsset]currencyBalances
+)
+
+// SubAccount contains a account for an asset type and its balances
```
Comment (cranktakular) [inline exchange/accounts/accounts.go]: grammar: "a account" > "an account"

File: exchange/accounts/accounts.go [hunk 105]
```diff
@@ -0,0 +1,306 @@
...
+// The subAccount may be the main account depending on exchange structure
```
Comment (cranktakular) [inline exchange/accounts/accounts.go]: grammar: odd capitalisation for "subAccount" here; the type itself isn't capitalised like that.

File: exchange/accounts/accounts.go [hunk 106]
```diff
@@ -0,0 +1,306 @@
...
+type SubAccount struct {
+	ID        string
+	AssetType asset.Item
+	Balances  CurrencyBalances
+}
+
+// SubAccounts contains a list of public SubAccounts
+type SubAccounts []*SubAccount
```
Comment (cranktakular) [inline exchange/accounts/accounts.go:55]: Confirm that you've considered making this []SubAccount instead, and chosen the pointer version due to it having upside.

File: exchange/accounts/accounts.go [hunk 107]
```diff
@@ -0,0 +1,306 @@
...
+	return &SubAccount{
+		AssetType: a,
+		ID:        id,
+		Balances:  CurrencyBalances{},
+	}
+}
+
+// Subscribe subscribes to your exchange accounts
+func (a *Accounts) Subscribe() (dispatch.Pipe, error) {
+	return a.mux.Subscribe(a.routingID)
```
Comment (cranktakular) [inline exchange/accounts/accounts.go:100]: Panics when a is nil, is that fine?

File: exchange/accounts/accounts.go [hunk 108]
```diff
@@ -0,0 +1,306 @@
...
+		return nil, err
+	}
+	if !assetType.IsValid() && assetType != asset.All {
+		return nil, fmt.Errorf("%s %s %w", a.Exchange.GetName(), assetType, asset.ErrNotSupported)
+	}
+
+	a.mu.RLock()
+	defer a.mu.RUnlock()
+
+	currs := CurrencyBalances{}
```
Comment (cranktakular) [inline exchange/accounts/accounts.go]: I think this could be moved above the read lock for a slight optimisation.

Similar situations crop up in some other functions, here.

File: exchange/accounts/accounts.go [hunk 109]
```diff
@@ -0,0 +1,306 @@
...
+// If creds is nil, all credential SubAccounts will be collated
+// If assetType is asset.All, all assets will be collated
+func (a *Accounts) CurrencyBalances(creds *Credentials, assetType asset.Item) (CurrencyBalances, error) {
+	if err := common.NilGuard(a); err != nil {
+		return nil, err
+	}
+	if !assetType.IsValid() && assetType != asset.All {
+		return nil, fmt.Errorf("%s %s %w", a.Exchange.GetName(), assetType, asset.ErrNotSupported)
+	}
+
```
Comment (cranktakular) [inline exchange/accounts/accounts.go:113]: There's many blank newlines across the PR, which it may be a good idea to remove.

File: dispatch/dispatch.go [hunk 110]
```diff
@@ -226,18 +223,15 @@ func (d *Dispatcher) publish(id uuid.UUID, data any) error {
 	case d.jobs <- job{data, id}: // Push job into job channel.
 		return nil
 	default:
-		return fmt.Errorf(limitMessage,
-			errDispatcherJobsAtLimit,
-			len(d.jobs),
-			d.maxWorkers)
+		return fmt.Errorf(limitMessage, errDispatcherJobsAtLimit, len(d.jobs), d.maxWorkers)
```
Comment (cranktakular) [inline dispatch/dispatch.go:226]: I know you didn't generally design this, and it's been working fine for 6 years, but might we want to add a delay of ~50-3000 ms (during which we retry sending on the channel) before erroring out here, in case the channel gets full during a period of extreme load?

File: exchange/accounts/accounts_test.go [hunk 111]
```diff
@@ -0,0 +1,542 @@
...
+	t.Parallel()
+	err := dispatch.EnsureRunning(dispatch.DefaultMaxWorkers, dispatch.DefaultJobsLimit)
+	require.NoError(t, err, "dispatch.EnsureRunning must not error")
+	p, err := MustNewAccounts(&mockEx{}).Subscribe()
+	require.NoError(t, err)
+	require.NotNil(t, p, "Subscribe must return a pipe")
+	require.Empty(t, p.Channel(), "Pipe must be empty before Saving anything")
+}
+
+// TestAccountsCurrencyBalances exercises Accounts.CurrencyBalances
```
Comment (cranktakular) [inline exchange/accounts/accounts_test.go]: Are these test comments necessary? They seem pretty self-explanatory.

File: exchange/accounts/accounts_test.go [hunk 112]
```diff
@@ -0,0 +1,542 @@
...
+	assert.ErrorIs(t, err, asset.ErrNotSupported)
+
+	_, err = a.CurrencyBalances(creds3, asset.All)
+	require.ErrorIs(t, err, ErrNoBalances)
+
+	_, err = a.CurrencyBalances(creds3, asset.All)
+	assert.ErrorIs(t, err, ErrNoBalances)
+	assert.ErrorContains(t, err, "Key:[3")
+
+	// Add a balance with inconsistent currencies to cover err from to currs.Add
```
Comment (cranktakular) [inline exchange/accounts/accounts_test.go]: grammar: "from to" should probably just be "from", even if not, it should still be changed to something different.

File: exchange/accounts/accounts_test.go [hunk 113]
```diff
@@ -0,0 +1,542 @@
...
+	_, err = a.GetBalance("1a", creds1, asset.Spot, currency.DOGE)
+	assert.ErrorIs(t, err, ErrNoBalances)
+	assert.ErrorContains(t, err, `for mocky SubAccount "1a" spot DOGE`)
+
+	b, err := a.GetBalance("1b", creds1, asset.Spot, currency.BTC)
+	require.NoError(t, err)
+	assert.Equal(t, 2.0, b.Total, "Total should be correct")
+}
+
+type saveTestCase struct {
```
Comment (cranktakular) [inline exchange/accounts/accounts_test.go]: Not sure how much this matters, but since this type is only used within the one test function, it can be defined there instead.

File: exchange/accounts/accounts_test.go [hunk 114]
```diff
@@ -0,0 +1,542 @@
...
+func TestAccountsSave(t *testing.T) { //nolint:tparallel // Save's internal tests are sequential
+	t.Parallel()
+
+	a := accountsFixture(t)
+	relay := subscribeFixture(t, a)
+	beforeNow := time.Now()
+
+	ctx := t.Context()
+	assert.ErrorContains(t, (*Accounts)(nil).Save(ctx, nil, false), "nil pointer: *accounts.Accounts")
+	assert.ErrorContains(t, new(Accounts).Save(ctx, nil, false), "nil pointer: accounts.credSubAccounts")
```
Comment (cranktakular) [inline exchange/accounts/accounts_test.go:232]: Is making sure that the right object is triggering the nil pointer error, worth the risk to maintainability here, over using error.Is common.ErrNilPointer?

File: exchange/accounts/accounts_test.go [hunk 115]
```diff
@@ -0,0 +1,542 @@
...
+
+	tt := []saveTestCase{
```
Comment (cranktakular) [inline exchange/accounts/accounts_test.go]: This variable name, "tt", is pretty nondescriptive. I can't even tell what it's meant to stand for.

File: exchange/accounts/balance.go [hunk 116]
```diff
@@ -0,0 +1,144 @@
...
+		Total:                  b.Total + a.Total,
+		Hold:                   b.Hold + a.Hold,
+		Free:                   b.Free + a.Free,
+		AvailableWithoutBorrow: b.AvailableWithoutBorrow + a.AvailableWithoutBorrow,
+		Borrowed:               b.Borrowed + a.Borrowed,
+		UpdatedAt:              u,
+	}
+}
+
+func (c currencyBalances) Public() CurrencyBalances {
```
Comment (cranktakular) [inline exchange/accounts/balance.go:103]: Should this function have a comment?

File: exchange/accounts/store.go [hunk 117]
```diff
@@ -0,0 +1,65 @@
...
+
+import (
+	"context"
+	"sync"
+	"sync/atomic"
+
+	"github.com/thrasher-corp/gocryptotrader/dispatch"
+)
+
+// Store contains exchanges accounts
```
Comment (cranktakular) [inline exchange/accounts/store.go]: grammar: "exchanges" > "exchange's"

File: exchange/accounts/store.go [hunk 118]
```diff
@@ -0,0 +1,65 @@
...
+	}
+	a, ok := s.exchangeAccounts[e]
+	if !ok {
+		a, err = NewAccounts(e, s.mux)
+		if err != nil {
+			return nil, err
+		}
+		s.exchangeAccounts[e] = a
+	}
+	return a, err
```
Comment (cranktakular) [inline exchange/accounts/store.go]: This probably doesn't matter, but the error is already handled, so you could do return a, nil

Or, since the return values are part of the function signature, you can just do return

File: exchange/accounts/store.go [hunk 119]
```diff
@@ -0,0 +1,65 @@
...
+	defer s.mu.Unlock()
+	if w, ok := e.(exchangeWrapper); ok {
+		// Because SetupDefaults is called on Base, it's easiest to just use the Base pointer as the key
+		e = w.GetBase()
+	}
+	a, ok := s.exchangeAccounts[e]
+	if !ok {
+		a, err = NewAccounts(e, s.mux)
+		if err != nil {
+			return nil, err
```
Comment (cranktakular) [inline exchange/accounts/store.go:60]: Right now, NewAccounts returns a nil *Accounts whenever it returns an error, and the return values are part of the function signature, so you could just do return

Comment (cranktakular) [reply exchange/accounts/store.go:60]: Also, you're currently missing coverage of this line, which you can get rather easily.

File: exchange/accounts/fixture_test.go [hunk 120]
```diff
@@ -0,0 +1,41 @@
+package accounts
+
+import (
+	"context"
+
+	"github.com/thrasher-corp/gocryptotrader/common"
+)
+
+type mockEx struct {
```
Comment (cranktakular) [inline exchange/accounts/fixture_test.go]: Is it really worthwhile putting this stuff in its own file, rather than in the store_test.go file?

When first viewing the directory, this confused me a bit, since all other *_test.go files were testing their respective *.go files

File: exchanges/account/account.go [hunk 121]
```diff
@@ -1,461 +0,0 @@
...
-	b.updatedAt = change.UpdatedAt
-	b.notice.Alert()
-	return nil
-}
-
-// Wait waits for a change in amounts for an asset type. This will pause
-// indefinitely if no change ever occurs. Max wait will return true if it failed
-// to achieve a state change in the time specified. If Max wait is not specified
-// it will default to a minute wait time.
-func (b *ProtectedBalance) Wait(maxWait time.Duration) (wait <-chan bool, cancel chan<- struct{}, err error) {
```
Comment (cranktakular) [inline exchanges/account/account.go:423]: This functionality doesn't seem to exist any more; is that okay?

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go [hunk 122]
```diff
@@ -144,6 +145,7 @@ assets:
 		})
 	}
 	assetPairs = append(assetPairs, assetPair{})
+
```
Comment (cranktakular) [inline cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go:148]: Worse than a newline without practical implications, such a newline was added to otherwise untouched code!

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go [hunk 123]
```diff
@@ -643,7 +645,8 @@ var acceptableErrors = []error{
 	limits.ErrExchangeLimitNotLoaded,     // Is thrown when the limits aren't loaded for a particular exchange, asset, pair
 	limits.ErrOrderLimitNotFound,         // Is thrown when the order limit isn't found for a particular exchange, asset, pair
 	limits.ErrEmptyLevels,                // Is thrown if limits are not provided for the asset
-	account.ErrExchangeHoldingsNotFound,
+	accounts.ErrNoBalances,
+	accounts.ErrNoSubAccounts,
```
Comment (cranktakular) [inline cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go:649]: While this convention hasn't fully been adhered to, it seems like errors listed here are meant to have comments explaining why they're acceptable.

File: dispatch/dispatch.go [hunk 124]
```diff
@@ -68,32 +76,25 @@ func IsRunning() bool {
 	return dispatcher.isRunning()
 }
 
-// start compares atomic running value, sets defaults, overrides with
-// configuration, then spawns workers
+// start sets defaults and config and spawns workers
+// Does not enjoy locking protection
```
Comment (cranktakular) [inline dispatch/dispatch.go]: phrasing: This second comment seems incorrect? It enjoys (benefits from) locking protection, and in fact, needs another function providing it, right? The locks imposed in Start() and EnsureRunning() would still be in place while this function is being executed.

Which is to say, maybe use the word "provide" instead?

File: dispatch/dispatch.go [hunk 125]
```diff
@@ -41,23 +43,29 @@ func NewDispatcher() *Dispatcher {
...
+	dispatcher.m.Lock()
+	defer dispatcher.m.Unlock()
+	return dispatcher.start(workers, jobsLimit)
 }
 
-// Start starts the dispatch system by spawning workers and allocating memory
-func Start(workers, jobsLimit int) error {
+// EnsureRunning starts the global dispatcher if it's not already running
+func EnsureRunning(workers, jobsLimit int) error {
+	dispatcher.m.Lock()
```
Comment (cranktakular) [inline dispatch/dispatch.go:60]: Please add coverage for this function.

File: engine/portfolio_manager.go [hunk 126]
```diff
@@ -124,152 +124,91 @@ func (m *portfolioManager) processPortfolio() {
...
 	}
 	atomic.CompareAndSwapInt32(&m.processing, 1, 0)
 }
 
-// seedExchangeAccountInfo seeds account info
-func (m *portfolioManager) seedExchangeAccountInfo(accounts []account.Holdings) {
-	if len(accounts) == 0 {
-		return
+// updateExchangeBalances calls UpdateAccountBalance on each exchange, and transfers the account balances into portfolio
+func (m *portfolioManager) updateExchangeBalances() error {
```
Comment (cranktakular) [inline engine/portfolio_manager.go:144]: I think this function should get more testing coverage.

File: engine/portfolio_manager.go [hunk 127]
```diff
@@ -124,152 +124,91 @@ func (m *portfolioManager) processPortfolio() {
...
-		if !exchanges[x].IsEnabled() {
-			continue
-		}
-		if !exchanges[x].IsRESTAuthenticationSupported() {
-			if m.base.Verbose {
-				log.Debugf(log.PortfolioMgr,
-					"skipping %s due to disabled authenticated API support.\n",
-					exchanges[x].GetName())
+// updateExchangeAddressBalances fetches and collates all account balances with their deposit addresses
+func (m *portfolioManager) updateExchangeAddressBalances(e exchange.IBotExchange) error {
```
Comment (cranktakular) [inline engine/portfolio_manager.go:180]: This function should get tested.

File: exchanges/coinbase/coinbase_test.go [hunk 128]
```diff
@@ -121,13 +121,11 @@ func TestGetAccountByID(t *testing.T) {
...
-	assert.NoError(t, err)
+	require.NoError(t, err)
 	require.True(t, longResp != nil && len(longResp.Accounts) > 0, errExpectedNonEmpty)
 	shortResp, err := e.GetAccountByID(t.Context(), longResp.Accounts[0].UUID)
-	assert.NoError(t, err)
-	if *shortResp != longResp.Accounts[0] {
-		t.Errorf(errExpectMismatch, shortResp, longResp.Accounts[0])
-	}
+	require.NoError(t, err)
+	require.Equal(t, shortResp, longResp.Accounts[0])
```
Comment (cranktakular) [inline exchanges/coinbase/coinbase_test.go]: I'm morally opposed to this require. Even if more lines were added to this function, they're highly unlikely to be dependent on those two responses being the same, making this equality not really required.

File: exchange/accounts/balance.go [hunk 129]
```diff
@@ -0,0 +1,144 @@
...
+//nolint:gocritic // Ignoring hugeparam because we want the convenience of all callers passing by value
+//nolint:gocritic // and we want to store a copy anyway so the hugeparam warning that this copies a value is not relevant
+func (c *CurrencyBalances) Set(curr currency.Code, b Balance) {
+	b.Currency = curr
+	(*c)[curr] = b
+}
+
+// Add will add to a currency balance
+func (c *CurrencyBalances) Add(curr currency.Code, b Balance) error { //nolint:gocritic // hugeparam not relevant; we want to store a value so we'd deref anyway
+	if b.Currency != currency.EMPTYCODE && !b.Currency.Equal(curr) {
```
Comment (samuael) [inline exchange/accounts/balance.go:64]: We only checked if there is a currency mismatch. Not if the currency code is empty

Comment (samuael) [reply exchange/accounts/balance.go:64]: Screenshot 2025-10-07 at 9 48 12 in the morning

File: exchanges/coinbase/coinbase_types.go [hunk 130]
```diff
@@ -66,10 +66,10 @@ type Account struct {
 
 // AllAccountsResponse holds many Account structs, as well as pagination information, returned by ListAccounts
 type AllAccountsResponse struct {
-	Accounts []Account `json:"accounts"`
-	HasNext  bool      `json:"has_next"`
-	Cursor   Integer   `json:"cursor"`
-	Size     uint8     `json:"size"`
+	Accounts []*Account `json:"accounts"`
```
Comment (cranktakular) [inline exchanges/coinbase/coinbase_types.go:69]: What's the reason for this change? Removing it, and testing the relevant functions (ListAccounts & UpdateAccountBalances) didn't lead to any errors.

File: exchanges/binance/binance_test.go [hunk 131]
```diff
@@ -1712,9 +1712,11 @@ func TestCancelAllExchangeOrders(t *testing.T) {
 	}
 }
 
-func TestGetAccountInfo(t *testing.T) {
+func TestUpdateAccountBalances(t *testing.T) {
 	t.Parallel()
 	sharedtestvalues.SkipTestIfCredentialsUnset(t, e)
+	e := new(Exchange) //nolint:govet // Intentional shadow to avoid future copy/paste mistakes
+	require.NoError(t, testexch.Setup(e), "Test instance Setup must not error")
```
Comment (cranktakular) [inline exchanges/binance/binance_test.go:1714]: Why was this done? If I remove it, I seem to get no errors, and I seem to inexplicably go from 45.8% coverage to 45.9%. Certainly seems to do something, but it doesn't seem to be preventing an error or increasing coverage.

File: exchange/accounts/accounts.go (hunk 106 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:55]: This question implies that a slice of values is the default and pointers should be justified.
I don't agree with that premise.
I mostly default to pointers, and think quickly if it's dangerous or violates incapsulation.
We've been moving to slices of pointers quite regularly, because ranging them is cleaner, and it's lighter.
Here that's the case. Ranging is easier, and there's no downside.

File: cmd/gctcli/commands.go [hunk 132]
```diff
@@ -575,24 +575,24 @@ func getTickers(c *cli.Context) error {
...
 	Flags: []cli.Flag{
 		&cli.StringFlag{
 			Name:  "exchange",
-			Usage: "the exchange to get the account info for",
+			Usage: "the exchange to get the account balances for",
 		},
 		&cli.StringFlag{
 			Name:  "asset",
-			Usage: "the asset type to get the account info for",
+			Usage: "the asset type to get the account balances for",
```
Comment (samuael) [inline cmd/gctcli/commands.go]: since you are here. This is required field.
`Required: true,`

File: cmd/gctcli/commands.go [hunk 133]
```diff
@@ -575,24 +575,24 @@ func getTickers(c *cli.Context) error {
...
+	Name:      "getaccountbalances",
+	Usage:     "gets the exchange account balances",
 	ArgsUsage: "<exchange> <asset>",
-	Action:    getAccountInfo,
+	Action:    getAccountBalances,
 	Flags: []cli.Flag{
 		&cli.StringFlag{
 			Name:  "exchange",
-			Usage: "the exchange to get the account info for",
+			Usage: "the exchange to get the account balances for",
```
Comment (samuael) [inline cmd/gctcli/commands.go]: `Required: true,`

File: engine/rpcserver_test.go [hunk 134]
```diff
@@ -386,22 +391,13 @@ func (f fExchange) CalculateTotalCollateral(context.Context, *futures.TotalColla
...
 }
 
-// UpdateAccountInfo overrides testExchange's update account info function
+// UpdateAccountBalances overrides testExchange's update account info function
 // to do the bare minimum required with no API calls or credentials required
-func (f fExchange) UpdateAccountInfo(_ context.Context, a asset.Item) (account.Holdings, error) {
+func (f fExchange) UpdateAccountBalances(_ context.Context, a asset.Item) (accounts.SubAccounts, error) {
 	if a == asset.Futures {
-		return account.Holdings{}, asset.ErrNotSupported
+		return accounts.SubAccounts{}, asset.ErrNotSupported
```
Comment (samuael) [inline engine/rpcserver_test.go:398]:
```
if a != asset.Spot {
    return account.SubAccounts{}, fmt.Errorf("%w: %v", asset.ErrNotSupported, a)
}
```

Comment (samuael) [reply engine/rpcserver_test.go:398]: Optional.

File: exchange/accounts/accounts.go [hunk 135]
```diff
@@ -0,0 +1,306 @@
...
+			}
+		}
+	}
+	if len(currs) == 0 {
+		return nil, fmt.Errorf("%w for %s credentials %s asset %s", ErrNoBalances, a.Exchange.GetName(), creds, assetType)
+	}
+	return currs, nil
+}
+
+// SubAccounts returns the public SubAccounts and their balances
```
Comment (samuael) [inline exchange/accounts/accounts.go]: `public subAccounts`?

File: exchange/accounts/accounts.go [hunk 136]
```diff
@@ -0,0 +1,306 @@
...
+
+	if len(subAccts) == 0 {
+		return nil, fmt.Errorf("%w for %s credentials %s asset %s", ErrNoSubAccounts, a.Exchange.GetName(), creds, assetType)
+	}
+	return subAccts, nil
+}
+
+// GetBalance returns a copy of the balance for that asset item
+func (a *Accounts) GetBalance(subAccount string, creds *Credentials, aType asset.Item, c currency.Code) (Balance, error) {
+	if err := common.NilGuard(a); err != nil {
```
Comment (samuael) [inline exchange/accounts/accounts.go:181]: `NilGuard` should include `creds` too. to prevent nil pointer error below on Line 183

File: exchanges/bitfinex/bitfinex_test.go [hunk 137]
```diff
@@ -407,11 +407,8 @@ func TestGetLeaderboard(t *testing.T) {
 func TestGetAccountFees(t *testing.T) {
 	t.Parallel()
 	sharedtestvalues.SkipTestIfCredentialsUnset(t, e)
-
-	_, err := e.UpdateAccountInfo(t.Context(), asset.Spot)
-	if err != nil {
-		t.Error("GetAccountInfo error", err)
-	}
+	_, err := e.UpdateAccountBalances(t.Context(), asset.Spot)
+	require.NoError(t, err)
```
Comment (samuael) [inline exchanges/bitfinex/bitfinex_test.go]: `require` -> `assert`

File: exchanges/bitflyer/bitflyer_wrapper.go (hunk 100 above)
Comment (samuael) [reply exchanges/bitflyer/bitflyer_wrapper.go:245]: I see. Does bitflyer require significant update?

Comment (shazbert) [reply exchanges/bitflyer/bitflyer_wrapper.go:245]: Yeah, nobody here can get API keys to determine auth usage. So this can stay as is.

File: exchange/accounts/accounts.go (hunk 105 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/9c4c41f66

File: exchange/accounts/accounts.go (hunk 104 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/9c4c41f66

File: exchange/accounts/accounts.go (hunk 107 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:100]: Nope. Thanks for catching.

Fixed https://github.com/gbjk/gocryptotrader/commit/c9a1067ba

File: exchange/accounts/accounts.go (hunk 108 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Yeah, alright then.

Fixed https://github.com/gbjk/gocryptotrader/commit/4bb0673fe

File: exchange/accounts/accounts.go (hunk 109 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:113]: I garden my newlines explicitly for legibility. Sections that are doing something together, or unrelated, etc.
So I'm happy with what I see when I've looked here.

File: dispatch/dispatch.go (hunk 110 above)
Comment (gbjk) [reply dispatch/dispatch.go:226]: If someone reports it happening, we can consider then 👍 
But moving it to a backoff retry is actually moving your channel buffer into blocking/goros instead, and you'd be fanning those out instead.

File: exchange/accounts/accounts_test.go (hunk 111 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Agreed. Removing. Left the one about what the fixture is up to.

Fixed https://github.com/gbjk/gocryptotrader/commit/f6563761c

File: exchange/accounts/accounts_test.go (hunk 112 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/40c3da199

File: exchange/accounts/accounts_test.go (hunk 113 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: Agreed. Folded down the for loop too. It was borderline whether ir was legible enough or not, but in hindsight and with fresh eyes this works.

Fixed https://github.com/gbjk/gocryptotrader/commit/786b16041

File: exchange/accounts/accounts_test.go (hunk 114 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go:232]: Yes. Always. IMO.
One problem we've had in our codebase that I've seen a bunch of tests that check that errors happen in sequence, without really checking what the actual error was, assuming that each change would fix one thing until finally it's okay.
This isn't quite that, but it's similar.
If we want to test that it errors on credSubAccounts, we really need to see that.

File: exchange/accounts/accounts_test.go (hunk 115 above)
Comment (gbjk) [reply exchange/accounts/accounts_test.go]: I see where you're coming from, but Go is idiomatically not really that descriptive with var names, normally, preferring single characters.

`tc` is testCase and `tt` is `testTable`.

I'll use them pretty universally.
HTH - HopeThisHelps.

File: exchange/accounts/balance.go (hunk 116 above)
Comment (gbjk) [reply exchange/accounts/balance.go:103]: Yeah, go on then.

It doesn't have to, because the type it's on isn't public (har har), but if you're asking then needs one.

Fixed https://github.com/gbjk/gocryptotrader/commit/2c7fb403a

File: exchange/accounts/store.go (hunk 117 above)
Comment (gbjk) [reply exchange/accounts/store.go]: Thanks; Declining the specific change, since it'd be wrong IMHO.
`exchange's accounts` would be okay, but reads painfully.
Opting for `accounts for exchanges`

Fixed https://github.com/gbjk/gocryptotrader/commit/0c1d3ff11

File: exchange/accounts/store.go (hunk 118 above)
Comment (gbjk) [reply exchange/accounts/store.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/2c7d63a5f

> Or, since the return values are part of the function signature, you can just do return

Hard pass to not use naked returns ever, please.
Named return vars can be helpful and I personally like them, but I'm pretty sure we have a linter to stop you doing a bare return.

File: exchange/accounts/store.go (hunk 119 above)
Comment (gbjk) [reply exchange/accounts/store.go:60]: > Right now, NewAccounts returns a nil *Accounts whenever it returns an error, and the return values are part of the function signature, so you could just do return

Hard pass to not use naked returns ever, please.
Named return vars can be helpful and I personally like them, but I'm pretty sure we have a linter to stop you doing a bare return.

File: exchange/accounts/fixture_test.go (hunk 120 above)
Comment (gbjk) [reply exchange/accounts/fixture_test.go]: Agreed.

Fixed https://github.com/gbjk/gocryptotrader/commit/46b38d4d0

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go (hunk 122 above)
Comment (gbjk) [reply cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go:148]: Wasn't an accident. I'm not a puppy 😁 
I like it. Helped me read it. Can it stay?

File: cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go (hunk 123 above)
Comment (gbjk) [reply cmd/exchange_wrapper_standards/exchange_wrapper_standards_test.go:649]: Yeah... don't get me started.
🤏 This F close to removing them, but it felt like too much of a drive by.
They're not actually telling us anything.

Pass please, sir. 🫡

File: dispatch/dispatch.go (hunk 124 above)
Comment (gbjk) [reply dispatch/dispatch.go]: I've generally used "enjoy" to mean - benefit from directly.
But you've pointed out you didn't understand it, so it's not clear enough.

I prefer your suggestion. Thanks 🙏 

Fixed https://github.com/gbjk/gocryptotrader/commit/57e1df04d

File: exchange/accounts/store.go (hunk 119 above)
Comment (gbjk) [reply exchange/accounts/store.go:60]: > Also, you're currently missing coverage of this line, which you can get rather easily.

Fixed https://github.com/gbjk/gocryptotrader/commit/7fa0f9ca9

File: exchanges/account/account.go (hunk 121 above)
Comment (gbjk) [reply exchanges/account/account.go:423]: Yes, I believe so. I checked with shazbert as well.
Instead of having the complexity of a protected balance with wait, users can subscribe.

File: dispatch/dispatch.go (hunk 125 above)
Comment (gbjk) [reply dispatch/dispatch.go:60]: Fixed https://github.com/gbjk/gocryptotrader/commit/91cde1f15

File: exchanges/coinbase/coinbase_test.go (hunk 128 above)
Comment (gbjk) [reply exchanges/coinbase/coinbase_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/fa9ce08fd

File: exchanges/coinbase/coinbase_types.go (hunk 130 above)
Comment (gbjk) [reply exchanges/coinbase/coinbase_types.go:69]: We're making this change frequently to resp types, so that ranging the response doesn't copy vars.
Removing it won't lead to errors, but you should get linter warnings.

File: exchanges/binance/binance_test.go (hunk 131 above)
Comment (gbjk) [reply exchanges/binance/binance_test.go:1714]: Pretty sure it would have been to isolate the changes to this instance of Exchange from the rest of the test.
Otherwise it would race, and I probably hit one of them. That's usually why I'll isolate the test instance like this.
Try running your test with `-race -count 1,000,000,000,000` and you will probably see a failure.

File: exchange/accounts/balance.go (hunk 129 above)
Comment (gbjk) [reply exchange/accounts/balance.go:64]: Erm, yeah. I really didn't expect someone to actually call it explicitly with `EMPTYCODE`. But I guess it's possible.
Let's protect against it.

Fixed https://github.com/gbjk/gocryptotrader/commit/08190a3c2

File: cmd/gctcli/commands.go (hunk 132 above)
Comment (gbjk) [reply cmd/gctcli/commands.go]: Done, but **Please double check this for me.**

Fixed https://github.com/gbjk/gocryptotrader/commit/62f017d4c

File: cmd/gctcli/commands.go (hunk 133 above)
Comment (gbjk) [reply cmd/gctcli/commands.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/62f017d4c

File: engine/rpcserver_test.go (hunk 134 above)
Comment (gbjk) [reply engine/rpcserver_test.go:398]: Way outta scope for anything I'm thinking about - so unless you have skin in the game on this, I'll pass.
It's test code, after all.

File: exchange/accounts/accounts.go (hunk 135 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: I _think_ this comment is outdated and was fixed in the pass I just completed for crank.
Resolving

File: exchange/accounts/accounts.go (hunk 136 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:181]: I don't agree - look into `IsEmpty` - it checks for `nil` itself

File: exchanges/bitfinex/bitfinex_test.go (hunk 137 above)
Comment (gbjk) [reply exchanges/bitfinex/bitfinex_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/aa3eb7407

File: exchange/accounts/accounts.go (hunk 106 above)
Comment (cranktakular) [reply exchange/accounts/accounts.go:55]: But then you'd need to dereference more; on top of the mandatory one going from the slice to the backing array, you'd need to dereference every element you wish to use.

It doesn't seem to change the syntax of ranging (just the syntax of appends).

So I guess all that's left is which way results in more speed, but it seems like it would take a fair bit of effort to meaningfully benchmark that, for this situation.

File: exchange/accounts/store.go (hunk 117 above)
Comment (cranktakular) [reply exchange/accounts/store.go]: Typo in your fix; should be "accounts" not "acocunts".

File: exchanges/binance/binance_test.go (hunk 131 above)
Comment (cranktakular) [reply exchanges/binance/binance_test.go:1714]: Ran `go test -race -count 4 github.com/thrasher-corp/gocryptotrader/exchanges/binance`. Both before and after, the only error was TestRateLimit_LimitStatic complaining `cannot set up a new requester for rateLimitTest2: cannot reuse http client`.

I can't disprove it being a very intermittent failure (with it taking ~15 seconds to run all Binance tests, a trillion attempts would take far too long), but it doesn't seem too common.

File: exchange/accounts/accounts.go [hunk 138]
```diff
@@ -0,0 +1,312 @@
...
+	if !ok {
+		return Balance{}, fmt.Errorf("%w for %s SubAccount %q %s %s", ErrNoBalances, a.Exchange.GetName(), subAccount, aType, c)
+	}
+	return b.Balance(), nil
+}
+
+// Save updates the account balances
+// If isSnapshot is true any missing currencies will be removed
+// Credentials will be retrieved from ctx, Use DeployCredentialsToContext.
+// Changes to balances are published individually
```
Comment (cranktakular) [inline exchange/accounts/accounts.go]: Doc comments [should be full sentences](https://google.github.io/styleguide/go/decisions.html#doc-comments) with periods at the end. Important here in particular since VSCode removes newlines in comments, making the start of this read quite strangely ("updates the account balances If isSnapshot is true"?)

File: exchanges/bitmex/bitmex_wrapper.go [hunk 139]
```diff
@@ -442,49 +442,24 @@ func (e *Exchange) UpdateOrderbook(ctx context.Context, p currency.Pair, assetTy
 	return orderbook.Get(e.Name, p, assetType)
 }
 
-// UpdateAccountInfo retrieves balances for all enabled currencies for the
-// Bitmex exchange
-func (e *Exchange) UpdateAccountInfo(ctx context.Context, assetType asset.Item) (account.Holdings, error) {
-	var info account.Holdings
-
+// UpdateAccountBalances retrieves currency balances
+func (e *Exchange) UpdateAccountBalances(ctx context.Context, assetType asset.Item) (accounts.SubAccounts, error) {
```
Comment (cranktakular) [inline exchanges/bitmex/bitmex_wrapper.go:446]: This issue already existed in the code, so feel free to ignore.

assetType isn't used in any of the calls, so it's simply slapped onto the data the exchange sends, regardless of whether that's appropriate or not.

Also spotted this in Bitstamp, BTC Markets, BTSE, Coinbase, Coinut, Exmo, Gemini.

File: exchanges/bybit/bybit_websocket.go [hunk 140]
```diff
@@ -315,26 +315,21 @@ func (e *Exchange) wsProcessWalletPushData(ctx context.Context, resp []byte) err
...
+				Total:     result.Data[x].Coin[y].WalletBalance.Float64(),
+				Free:      result.Data[x].Coin[y].WalletBalance.Float64(),
+				UpdatedAt: result.CreationTime.Time(),
 			})
 		}
 	}
-	e.Websocket.DataHandler <- changes
-	return account.ProcessChange(e.Name, changes, creds)
+	if err := e.Accounts.Save(ctx, subAccts, false); err != nil {
+		return err
```
Comment (cranktakular) [inline exchanges/bybit/bybit_websocket.go:329]: If it's not removed (see other comment), is it plausible to get coverage of this line you added?

File: exchanges/bybit/bybit_test.go [hunk 141]
```diff
@@ -2779,44 +2779,50 @@ func TestGetBrokerEarning(t *testing.T) {
...
-			}
+	e := testInstance() //nolint:govet // Intentional shadow to avoid future copy/paste mistakes
+
+	subAccts, err := e.UpdateAccountBalances(t.Context(), asset.Spot)
+	require.NoError(t, err, "UpdateAccountBalances must not error")
+	require.NotEmpty(t, subAccts, "UpdateAccountBalances must return account info")
+
+	if mockTests {
+		require.Len(t, subAccts, 1, "Accounts must have 1 item")
+		subAcct := subAccts[0]
```
Comment (cranktakular) [inline exchanges/bybit/bybit_test.go]: This variable is only used twice; you could just replace those two uses with subAccts[0]. Compiles to the same thing, saves a line and a few bytes.

File: exchanges/bybit/bybit_websocket.go [hunk 142]
```diff
@@ -315,26 +315,21 @@ func (e *Exchange) wsProcessWalletPushData(ctx context.Context, resp []byte) err
...
+			subAccts[0].Balances.Set(result.Data[x].Coin[y].Coin, accounts.Balance{
+				Total:     result.Data[x].Coin[y].WalletBalance.Float64(),
+				Free:      result.Data[x].Coin[y].WalletBalance.Float64(),
+				UpdatedAt: result.CreationTime.Time(),
 			})
 		}
 	}
-	e.Websocket.DataHandler <- changes
-	return account.ProcessChange(e.Name, changes, creds)
+	if err := e.Accounts.Save(ctx, subAccts, false); err != nil {
```
Comment (cranktakular) [inline exchanges/bybit/bybit_websocket.go:328]: REST implementations of this function call Save on the return line, sending the subAccts to the caller regardless of whether or not Save returns an error.

Is it a good idea to change that functionality here?

Also spotted in Gateio.

File: exchanges/gateio/gateio_wrapper.go [hunk 143]
```diff
@@ -700,56 +700,43 @@ func (e *Exchange) UpdateOrderbookWithLimit(ctx context.Context, p currency.Pair
...
-					Total:    balances[i].Quote.Available.Float64() + balances[i].Quote.LockedAmount.Float64(),
-					Hold:     balances[i].Quote.LockedAmount.Float64(),
-					Free:     balances[i].Quote.Available.Float64(),
-				})
+			subAccts[0].Balances.Set(balances[i].Base.Currency, accounts.Balance{
+				Total: balances[i].Base.Available.Float64() + balances[i].Base.LockedAmount.Float64(),
+				Hold:  balances[i].Base.LockedAmount.Float64(),
+				Free:  balances[i].Base.Available.Float64(),
+			})
+			subAccts[0].Balances.Set(balances[i].Quote.Currency, accounts.Balance{
```
Comment (cranktakular) [inline exchanges/gateio/gateio_wrapper.go:705]: Worth checking with someone who knows for sure from experience with the exchange, but calling Set for both the base and quote currency, without any merging, seems like it could accidentally overwrite data. 

If the same base/quote currency is used in multiple balances, this will only save the value from the latest one to be processed, rather than summing them up. If the exchange actually splits those amounts, this will end up being inaccurate.

File: engine/portfolio_manager.go (hunk 126 above)
Comment (gbjk) [reply engine/portfolio_manager.go:144]: Fixed https://github.com/gbjk/gocryptotrader/commit/9c5880e73

File: engine/portfolio_manager.go (hunk 127 above)
Comment (gbjk) [reply engine/portfolio_manager.go:180]: Fixed https://github.com/gbjk/gocryptotrader/commit/9c5880e73

File: exchanges/binance/binance_test.go (hunk 131 above)
Comment (gbjk) [reply exchanges/binance/binance_test.go:1714]: Stupid question: Are you running with credentials?

But either way, isolating tests isn't a bad thing when they're touching shared values.
I'm close to just isolating all tests out of habit at this point.
`t.Parallel` + _touch a global var in its special places_  ➡️  👉👌

File: exchange/accounts/accounts.go (hunk 138 above)
Comment (gbjk) [reply exchange/accounts/accounts.go]: Yikes + Thanks. I'm gonna have to change my long held habit then.

I've extended this change request across everywhere I spotted I'd touched 🌴 

Fixed https://github.com/gbjk/gocryptotrader/commit/cea0fec4f

File: exchanges/bitmex/bitmex_wrapper.go (hunk 139 above)
Comment (gbjk) [reply exchanges/bitmex/bitmex_wrapper.go:446]: Good point. But I'll dodge this, since this PR is so overdue it's children are heading to university soon.

File: exchanges/bybit/bybit_test.go (hunk 141 above)
Comment (gbjk) [reply exchanges/bybit/bybit_test.go]: Fixed https://github.com/gbjk/gocryptotrader/commit/fd202e79b

File: exchanges/bybit/bybit_websocket.go (hunk 142 above)
Comment (gbjk) [reply exchanges/bybit/bybit_websocket.go:328]: Yes, I believe this change is a good idea.
* I considered both sides of it, and concluded that we should not be sending data to DataHandler that we failed to process.
So this change was very deliberate and proactive.

* This is not the same as the REST function, because the REST function returns an error.
I've assumed you mean that the DataHandler channel is acting the same as the return field in the REST.
If someone calls a function that has an error return, then they should check that before using any other values.
But the datahandler would get the data in isolation from the error, so it's not the same, or acceptable

File: exchanges/bybit/bybit_websocket.go (hunk 140 above)
Comment (gbjk) [reply exchanges/bybit/bybit_websocket.go:329]: It's plausible, but because of the way `TestWSHandleAuthenticatedData` is right now, it'd require quite a bit of work. I tried to see a failing state for wsAuth.json that was easy, but nothing in Save was easy to fangle with at all.

Since the error return value from `ProcessChange` wasn't being tested previously, while the new line is not covered, we're not reducing actual unit testing here.
That is: err was not checked before, and it's not checked now.

And now I realise you won't see this for a week, so I kinda have to do the coverage because waiting a week for you to reply "yes, I insist" would be a criminal waste of time 😢

Comment (gbjk) [reply exchanges/bybit/bybit_websocket.go:329]: Fixed https://github.com/gbjk/gocryptotrader/commit/4a014fd28

File: exchanges/gateio/gateio_wrapper.go (hunk 143 above)
Comment (gbjk) [reply exchanges/gateio/gateio_wrapper.go:705]: I don't think that's how it works.
There's no version of this I can think of where the balances wouldn't be the same.
When saying you have margin balance for ETH/USDT and BTC/USDT, it's gotta be the same balance for each. The _trades_ might have isolation, but the balances won't.

That said, I agree that we should be 100% sure, so I've asked others, and if nobody has quick access to data, I'll testnet it or do it live.

Comment (thrasher-) [reply exchanges/gateio/gateio_wrapper.go:705]: Crank is correct for isolated margin where assets are tied to a particular trading pair so the amounts would need to be merged. For cross margin gk is correct, where assets are pooled and shared across all positions in which case the assets can just be set. There's also unified accounts, which we're not currently using but that acts like cross too

Comment (gbjk) [reply exchanges/gateio/gateio_wrapper.go:705]: Having tested with and without unified accounts under testnet, the only isolated margin available is under perp futures, and that will come back under `asset.USDTMarginedFutures`
```
   (currency.Code) USDT: (accounts.Balance) {
    Currency: (currency.Code) USDT,
    Total: (float64) 999.8945371,
    Hold: (float64) 217.15920058749998,
    Free: (float64) 782.7353365125,
 ```

Cross margin for spot ... didn't show up in any of the responses at all.

I'll run another batch of tests once I work out how to downgrade back from unified account again.

Comment (gbjk) [reply exchanges/gateio/gateio_wrapper.go:705]: * All isolated and cross futures Hold balances come back in one entry for `usdtmarginedfutures`. Not related to these lines, though.
* Spot only has cross margin available for me

It's a bit difficult for me to proceed, because I can't verify for GateIO myself.

For now the best thing I think I can do is switch to using `Add` for these calls, and then hope to get some feedback on what various responses look like for a verified account from @gloriousCode on Monday.

Fixed https://github.com/gbjk/gocryptotrader/commit/78a85a271

Comment (thrasher-) [reply exchanges/gateio/gateio_wrapper.go:705]: I wonder if your account is geoblocked. I thought it might of been that you're using a unified account but from here I can access isolated margin and cross margin for spot pairs (separate to USDT margined futures) via web GUI:

image

Comment (gbjk) [reply exchanges/gateio/gateio_wrapper.go:705]: Yep, it was geolocked for both my location and my second attempt with VPN.
Using Au is fine.

Not available in testnet unfortunately, though.

We have the answer from @gloriousCode already:
The funds come back combined.
Here is 2 isolated margin spot loans for ARIA and 1INCH, where the separate 1 + 2 USDT amounts got combined:
```
(*accounts.SubAccount)(0x14000752e40)({
  ID: (string) "",
  AssetType: (asset.Item) margin,
  Balances: (accounts.CurrencyBalances) (len=3) {
   (currency.Code) ARIA: (accounts.Balance) {
    Currency: (currency.Code) ARIA,
    Total: (float64) 0,
    Hold: (float64) 0,
    Free: (float64) 0,
    AvailableWithoutBorrow: (float64) 0,
    Borrowed: (float64) 0,
    UpdatedAt: (time.Time) 2025-10-20 09:57:40.881756 +1100 AEDT m=+1.096338376
   },
   (currency.Code) USDT: (accounts.Balance) {
    Currency: (currency.Code) USDT,
    Total: (float64) 3,
    Hold: (float64) 0,
    Free: (float64) 3,
    AvailableWithoutBorrow: (float64) 0,
    Borrowed: (float64) 0,
    UpdatedAt: (time.Time) 2025-10-20 09:57:40.881754 +1100 AEDT m=+1.096335918
   },
   (currency.Code) 1INCH: (accounts.Balance) {
    Currency: (currency.Code) 1INCH,
    Total: (float64) 0,
    Hold: (float64) 0,
    Free: (float64) 0,
    AvailableWithoutBorrow: (float64) 0,
    Borrowed: (float64) 0,
    UpdatedAt: (time.Time) 2025-10-20 09:57:40.881755 +1100 AEDT m=+1.096337251
   }
  }
 })
}
```

So what we have now seems acceptable. Using `Add` should cope if we get a different response, but it also works fine for what we're getting today.

I'll let people review that fix and then resolve this thread

Comment (gbjk) [reply exchanges/gateio/gateio_wrapper.go:705]: I take it back. Writing code for a result we don't currently get is kinda dangerous.
Margin returns one result per currency.
We should Use `Set`.

Reverted https://github.com/gbjk/gocryptotrader/commit/58f050d37

Also drive-by fixed the test name: https://github.com/gbjk/gocryptotrader/commit/c7f658b3a

File: exchanges/binance/binance_test.go (hunk 131 above)
Comment (cranktakular) [reply exchanges/binance/binance_test.go:1714]: Oh doh, I am running without credentials.

My bad.

File: exchanges/huobi/huobi_wrapper.go [hunk 144]
```diff
@@ -653,161 +653,99 @@ func (e *Exchange) GetAccountID(ctx context.Context) ([]Account, error) {
...
-						})
+				if balances[j].Type == "frozen" {
+					a.Balances.Set(balances[j].Currency, accounts.Balance{Hold: balances[j].Balance})
 				} else {
-					currencyDetails = append(currencyDetails,
-						account.Balance{
-							Currency: currency.NewCode(balances[j].Currency),
-							Total:    balances[j].Balance,
-						})
+					a.Balances.Set(balances[j].Currency, accounts.Balance{Total: balances[j].Balance})
```
Comment (cranktakular) [inline exchanges/huobi/huobi_wrapper.go]: I believe this is a change in functionality. My apologies for the long-winded and confusing explanation that will ensue.

Previously, for each call of GetAccountBalance, it would range over balances. The first time a currency was encountered, it was appended with the appropriate hold/total set. The next time it was encountered, it would be found in the list, and have the hold/total set/overwritten. This let both hold and total be set for one currency.

Now, it still ranges over balances for each call of GetAccountBalance, but it always Set()s the balance. Since set chucks out whatever was there prior, hold and total cannot both be set for one currency. Setting one erases the other. The subaccts.Merge(a) at the end of this does not prevent that; it comes after the range over balances, and only gracefully combines ones which were set to subAccts in previous calls of GetAccountBalance.

In short, the effect is that previously hold and total could both be set for one currency, and now they can't be.

File: exchanges/kucoin/kucoin_websocket.go [hunk 145]
```diff
@@ -360,24 +360,18 @@ func (e *Exchange) processFuturesAccountBalanceEvent(ctx context.Context, respDa
...
-	if err != nil {
+	subAccts := accounts.SubAccounts{accounts.NewSubAccount(asset.Futures, "")}
+	subAccts[0].Balances.Set(resp.Currency, accounts.Balance{
+		Total:     resp.AvailableBalance + resp.HoldBalance,
+		Hold:      resp.HoldBalance,
+		Free:      resp.AvailableBalance,
+		UpdatedAt: resp.Timestamp.Time(),
+	})
+	if err := e.Accounts.Save(ctx, subAccts, false); err != nil {
 		return err
```
Comment (cranktakular) [inline exchanges/kucoin/kucoin_websocket.go:370]: Feel free to skip the work (as I will not insist) but here and in similar functions, this line is missing coverage.

See also: OKX & Poloniex

File: exchanges/poloniex/poloniex_websocket.go [hunk 146]
```diff
@@ -946,18 +946,26 @@ func (e *Exchange) processAccountBalanceUpdate(notification []any) error {
...
+	change := accounts.Change{
+		Account:   id,
 		AssetType: asset.Spot,
-		Balance: &account.Balance{
-			Currency: code,
-			Total:    amount,
-			Free:     amount,
-		},
+		Balance:   bal,
+	}
```
Comment (cranktakular) [inline exchanges/poloniex/poloniex_websocket.go]: When Bybit, KuCoin, and OKX handled account updates in their websockets, they simply sent the subAccts variable to the DataHandler; why are you deviating from that approach here?

File: exchanges/exchange.go [hunk 147]
```diff
@@ -1910,14 +1918,24 @@ func (b *Base) GetCachedOrderbook(p currency.Pair, assetType asset.Item) (*order
...
+	creds, err := b.GetCredentials(ctx)
+	if err != nil {
+		return nil, err
+	}
+	return b.Accounts.SubAccounts(creds, assetType)
+}
+
+// GetCachedCurrencyBalances retrieves cached balances for all SubAccounts grouped by currency
+// NOTE: Accounts.Save method should be called first to populate the local cache
+func (b *Base) GetCachedCurrencyBalances(ctx context.Context, assetType asset.Item) (accounts.CurrencyBalances, error) {
```
Comment (cranktakular) [inline exchanges/exchange.go:1933]: Please add testing for this function

File: exchanges/exchange.go [hunk 148]
```diff
@@ -1960,3 +1978,8 @@ func (*Base) WebsocketCancelOrder(context.Context, *order.Cancel) error {
 func (b *Base) MessageID() string {
 	return uuid.Must(uuid.NewV7()).String()
 }
+
+// SubscribeAccountBalances returns a pipe to stream account holding updates
+func (b *Base) SubscribeAccountBalances() (dispatch.Pipe, error) {
```
Comment (cranktakular) [inline exchanges/exchange.go:1989]: Please add a test for this function.

File: exchange/accounts/accounts.go (hunk 106 above)
Comment (gbjk) [reply exchange/accounts/accounts.go:55]: We benched it already. That's why we're using ranging slices of pointers more regularly.
And data types less than 4 bytes.
It's actually faster and less allocs.

I'm going to resolve this. I don't think we need to delay this particular PR for it 🙂 
Reopen if you disagree.

File: exchange/accounts/balance.go (hunk 129 above)
Comment (gbjk) [reply exchange/accounts/balance.go:64]: Assuming this and other threads have been reviewed now, so resolving unilaterally.

File: exchanges/huobi/huobi_wrapper.go (hunk 144 above)
Comment (gbjk) [reply exchanges/huobi/huobi_wrapper.go]: You had me at _This is wrong_ 😍 

Should have been using `Add`. Thanks for spotting.

Fixed https://github.com/gbjk/gocryptotrader/commit/b573df64a

File: exchanges/kucoin/kucoin_websocket.go (hunk 145 above)
Comment (gbjk) [reply exchanges/kucoin/kucoin_websocket.go:370]: My fault for not going hunting for more when I added coverage for the other one.
It's good to know you won't insist ... If I can do it easily I will. If it implies a lot of fixture scaffolding, I'll dodge it.

Comment (gbjk) [reply exchanges/kucoin/kucoin_websocket.go:370]: Kucoin Fixed https://github.com/gbjk/gocryptotrader/commit/6d2b8f868
Okx Fixed https://github.com/gbjk/gocryptotrader/commit/6b9c676e7
Poloniex Skipping due to the huge overhaul ongoing in #1351

File: exchanges/poloniex/poloniex_websocket.go (hunk 146 above)
Comment (gbjk) [reply exchanges/poloniex/poloniex_websocket.go]: Looks like I was just preserving what was there before.
Unlike the above, I'll actually change this, because the conflict against #1351 will be useful - Whichever merges first.

Fixed https://github.com/gbjk/gocryptotrader/commit/cc1592530

File: exchanges/exchange.go (hunk 147 above)
Comment (gbjk) [reply exchanges/exchange.go:1933]: Fixed https://github.com/gbjk/gocryptotrader/commit/638982db1

File: exchanges/exchange.go (hunk 148 above)
Comment (gbjk) [reply exchanges/exchange.go:1989]: Fixed https://github.com/gbjk/gocryptotrader/commit/24e72c8b1

File: exchanges/kucoin/kucoin_test.go [hunk 149]
```diff
@@ -2338,11 +2339,24 @@ func TestGetAuthenticatedServersInstances(t *testing.T) {
 
 func TestPushData(t *testing.T) {
 	t.Parallel()
-	ku := testInstance(t)
-	ku.SetCredentials("mock", "test", "test", "", "", "")
-	ku.API.AuthenticatedSupport = true
-	ku.API.AuthenticatedWebsocketSupport = true
-	testexch.FixtureToDataHandler(t, "testdata/wsHandleData.json", ku.wsHandleData)
+
+	e := testInstance(t)
```
Comment (cranktakular) [inline exchanges/kucoin/kucoin_test.go]: Linter's complaining about this shadow.

Comment (gbjk) [reply exchanges/kucoin/kucoin_test.go]: Just to explain why this isn't as insane as it seems:
Whether or not the linter thinks this is shadowing something isn't exactly deterministic.
It changes if you introduce other shadows, or move things around.
So sometimes the linter was fine, then you rebase, and then the linter isn't happy anymore.
I deep-dived into this in slack a while ago, frustrated by the inconsistency.

So anyway, now we have only 2 main ways we do this shadow in tests, I'll probably driveby a linter rule to exclude `testInstance` and `new(Exchange)`. Another PR though.

~Fixed https://github.com/gbjk/gocryptotrader/commit/06a9706b8~
Correction - added `ci skip`
Fixed https://github.com/gbjk/gocryptotrader/commit/67e75e028

Immediate rebase down too
