### PR TITLE
Bug-fixes: #459 #460

### LINKED ISSUE #459: Bitmex order validation broken
# New Issue

## Context

Bitmex order side invalid
exchanges/bitmex/bitmex_wrapper.go:443

Side is set in UPPERCASE but bitmex expects `Buy` and `Sell`

* Operating System: macosx

* GoCryptoTrader version (`gocryptotrader -version`):
b686cf2e0e7e6b55f3bf62e381386e33effc9f86

## Expected Behavior

Please describe the behavior you are expecting
To validate Bitmex's api validation

## Current Behavior

What is the current behavior?
 {"error":{"message":"Invalid side","name":"ValidationError"}}

## Failure Information (for bugs)

Please help by providing information about the failure. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

	submission := &order.Submit{
		Pair: currency.Pair{
			Base:  currency.XBT,
			Quote: currency.USD,
		},
		Side: order.Buy,
		Type: order.Limit,
		Price:     1,
		Amount:    1,
		ClientID:  "meowOrder",
	}

	result, err := exch.SubmitOrder(submission)

### Failure Logs

By default and if file logging is enabled, GoCryptoTrader stores its `log.txt` file in `%APPDATA%\GoCryptoTrader\logs` on Windows and `~/.gocryptotrader/logs` on Linux/Unix/macOS. Raw text or a link to a pastebin type site is preferred.

<nil> Bitmex unsuccessful HTTP status code: 400  raw response: {"error":{"message":"Invalid side","name":"ValidationError"}}

### PR DESCRIPTION
**Pull request by azhang**
# PR Description

Fixes #459 and #460 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: exchanges/order/orders.go [hunk 1]
```diff
@@ -349,6 +349,10 @@ func (t Type) Lower() string {
 	return strings.ToLower(string(t))
 }
 
+func (t Type) Title() string {
```
Comment (xtda) [inline exchanges/order/orders.go]: Please add a comment
